import * as Constants from '@/constants'
import Resource from '@IBuilderBase/resources/goldMine/resource.interface'
import Level from '@IBuilderBase/resources/goldMine/level.interface'
import BuilderHallDetails from '@IBuilderBase/builderHall/details.interface'

const goldMine: Resource = {
	name: 'Gold Mine',
	description:
		'The Gold Mine produces gold. Upgrade it to boost its production and gold storage capacity.',
	maxCount: 3,
	width: 3,
	height: 3,
	maxLevel: 10,
	ruinImgUrl:
		'https://static.wikia.nocookie.net/clashofclans/images/3/30/Gold_Mine_Ruin.png/revision/latest/scale-to-width-down/100?cb=20170609145915',
	builderHallDetails: [
		{
			builderHallLevel: 1,
			availableCount: 1,
			maxLevel: 1,
			stage1MaxCount: 0,
			stage2MaxCount: 0,
		},
		{
			builderHallLevel: 2,
			availableCount: 1,
			maxLevel: 3,
			stage1MaxCount: 0,
			stage2MaxCount: 0,
		},
		{
			builderHallLevel: 3,
			availableCount: 1,
			maxLevel: 3,
			stage1MaxCount: 0,
			stage2MaxCount: 0,
		},
		{
			builderHallLevel: 4,
			availableCount: 1,
			maxLevel: 4,
			stage1MaxCount: 0,
			stage2MaxCount: 0,
		},
		{
			builderHallLevel: 5,
			availableCount: 1,
			maxLevel: 5,
			stage1MaxCount: 0,
			stage2MaxCount: 0,
		},
		{
			builderHallLevel: 6,
			availableCount: 2,
			maxLevel: 6,
			stage1MaxCount: 1,
			stage2MaxCount: 1,
		},
		{
			builderHallLevel: 7,
			availableCount: 2,
			maxLevel: 7,
			stage1MaxCount: 1,
			stage2MaxCount: 1,
		},
		{
			builderHallLevel: 8,
			availableCount: 3,
			maxLevel: 8,
			stage1MaxCount: 1,
			stage2MaxCount: 2,
		},
		{
			builderHallLevel: 9,
			availableCount: 3,
			maxLevel: 9,
			stage1MaxCount: 1,
			stage2MaxCount: 2,
		},
		{
			builderHallLevel: 10,
			availableCount: 3,
			maxLevel: 10,
			stage1MaxCount: 1,
			stage2MaxCount: 2,
		},
	],
	achievement: [],
	levels: [
		{
			level: 1,
			capacity: 24000,
			productionRatePerHr: 1000,
			hitpoints: 300,
			timeToFillSec: 0,
			timeToFillMin: 0,
			timeToFillHour: 0,
			timeToFillDay: 1,
			buildCost: 1000,
			buildCostResource: Constants.elixir,
			buildTimeSec: 0,
			buildTimeMin: 10,
			buildTimeHour: 0,
			buildTimeDay: 0,
			exp: 24,
			townHallLevelRequired: 1,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/b/bf/Gold_Mine1.png/revision/latest/scale-to-width-down/100?cb=20180110120430',
		},
		{
			level: 2,
			capacity: 28800,
			productionRatePerHr: 1200,
			hitpoints: 350,
			timeToFillSec: 0,
			timeToFillMin: 0,
			timeToFillHour: 0,
			timeToFillDay: 1,
			buildCost: 5000,
			buildCostResource: Constants.elixir,
			buildTimeSec: 0,
			buildTimeMin: 20,
			buildTimeHour: 0,
			buildTimeDay: 0,
			exp: 34,
			townHallLevelRequired: 3,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/5/55/Gold_Mine2.png/revision/latest/scale-to-width-down/100?cb=20180110120444',
		},
		{
			level: 3,
			capacity: 36000,
			productionRatePerHr: 1500,
			hitpoints: 400,
			timeToFillSec: 0,
			timeToFillMin: 0,
			timeToFillHour: 0,
			timeToFillDay: 1,
			buildCost: 10000,
			buildCostResource: Constants.elixir,
			buildTimeSec: 0,
			buildTimeMin: 40,
			buildTimeHour: 0,
			buildTimeDay: 0,
			exp: 48,
			townHallLevelRequired: 3,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/e/e4/Gold_Mine3.png/revision/latest/scale-to-width-down/100?cb=20180110120457',
		},
		{
			level: 4,
			capacity: 43200,
			productionRatePerHr: 1800,
			hitpoints: 460,
			timeToFillSec: 0,
			timeToFillMin: 0,
			timeToFillHour: 0,
			timeToFillDay: 1,
			buildCost: 30000,
			buildCostResource: Constants.elixir,
			buildTimeSec: 0,
			buildTimeMin: 0,
			buildTimeHour: 2,
			buildTimeDay: 0,
			exp: 84,
			townHallLevelRequired: 4,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/9/97/Gold_Mine4.png/revision/latest/scale-to-width-down/100?cb=20180110120510',
		},
		{
			level: 5,
			capacity: 50400,
			productionRatePerHr: 2100,
			hitpoints: 550,
			timeToFillSec: 0,
			timeToFillMin: 0,
			timeToFillHour: 0,
			timeToFillDay: 1,
			buildCost: 60000,
			buildCostResource: Constants.elixir,
			buildTimeSec: 0,
			buildTimeMin: 0,
			buildTimeHour: 6,
			buildTimeDay: 0,
			exp: 134,
			townHallLevelRequired: 5,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/1a/Gold_Mine5.png/revision/latest/scale-to-width-down/100?cb=20180110120533',
		},
		{
			level: 6,
			capacity: 60000,
			productionRatePerHr: 2500,
			hitpoints: 650,
			timeToFillSec: 0,
			timeToFillMin: 0,
			timeToFillHour: 0,
			timeToFillDay: 1,
			buildCost: 100000,
			buildCostResource: Constants.elixir,
			buildTimeSec: 0,
			buildTimeMin: 0,
			buildTimeHour: 0,
			buildTimeDay: 1,
			exp: 293,
			townHallLevelRequired: 6,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/8/86/Gold_Mine6.png/revision/latest/scale-to-width-down/100?cb=20180110120552',
		},
		{
			level: 7,
			capacity: 72000,
			productionRatePerHr: 3000,
			hitpoints: 750,
			timeToFillSec: 0,
			timeToFillMin: 0,
			timeToFillHour: 0,
			timeToFillDay: 1,
			buildCost: 200000,
			buildCostResource: Constants.elixir,
			buildTimeSec: 0,
			buildTimeMin: 0,
			buildTimeHour: 12,
			buildTimeDay: 1,
			exp: 360,
			townHallLevelRequired: 7,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/11/Gold_Mine7.png/revision/latest/scale-to-width-down/100?cb=20180110120611',
		},
		{
			level: 8,
			capacity: 84000,
			productionRatePerHr: 3500,
			hitpoints: 850,
			timeToFillSec: 0,
			timeToFillMin: 0,
			timeToFillHour: 0,
			timeToFillDay: 1,
			buildCost: 300000,
			buildCostResource: Constants.elixir,
			buildTimeSec: 0,
			buildTimeMin: 0,
			buildTimeHour: 0,
			buildTimeDay: 2,
			exp: 415,
			townHallLevelRequired: 8,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/5/52/Gold_Mine8.png/revision/latest/scale-to-width-down/100?cb=20180110120627',
		},
		{
			level: 9,
			capacity: 96000,
			productionRatePerHr: 4000,
			hitpoints: 1000,
			timeToFillSec: 0,
			timeToFillMin: 0,
			timeToFillHour: 0,
			timeToFillDay: 1,
			buildCost: 400000,
			buildCostResource: Constants.elixir,
			buildTimeSec: 0,
			buildTimeMin: 0,
			buildTimeHour: 12,
			buildTimeDay: 2,
			exp: 464,
			townHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/b/bf/Gold_Mine9.png/revision/latest/scale-to-width-down/100?cb=20180110120642',
		},
		{
			level: 10,
			capacity: 108000,
			productionRatePerHr: 4500,
			hitpoints: 1150,
			timeToFillSec: 0,
			timeToFillMin: 0,
			timeToFillHour: 0,
			timeToFillDay: 1,
			buildCost: 800000,
			buildCostResource: Constants.elixir,
			buildTimeSec: 0,
			buildTimeMin: 0,
			buildTimeHour: 0,
			buildTimeDay: 3,
			exp: 509,
			townHallLevelRequired: 10,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/e/eb/Gold_Mine10.png/revision/latest/scale-to-width-down/100?cb=20180110120703',
		},
	],
	getSize(): string {
		return `${this.width}x${this.height}`
	},
	getLevel(level: number): Level | undefined {
		if (level >= 1 && level <= this.levels.length) {
			return this.levels[level - 1]
		} else {
			console.error(`Invalid ${this.name} level: ${level}`)
			return undefined
		}
	},
	getBuilderHallLevel(level: number): BuilderHallDetails | undefined {
		if (level >= 1 && level <= this.builderHallDetails.length) {
			return this.builderHallDetails[level - 1]
		} else {
			console.error(`Invalid Town Hall level: ${level}`)
			return undefined
		}
	},
}

export default goldMine
