import * as Constants from '@/constants'
import Army from '@IHomeVillage/troops/army.interface'
import { getLevel } from '@Utils/buildings.utility'

const troop: Army = {
	name: 'Diggy',
	description:
		"Diggy is an introvert and spends a lot of time hiding underground. Still when it comes to battle he'll do his part, coming up to attack buildings and aid his Hero. If his Hero's taken out he'll seek out a new one for support and scritches.",
	maxLevel: 10,
	buildingLevelRequired: 6,
	buildingName: Constants.petHouse,
	avatarImgUrl:
		'https://static.wikia.nocookie.net/clashofclans/images/6/6b/Avatar_Diggy.png/revision/latest/scale-to-width-down/120?cb=20221010075229',
	mode: {
		attackType: Constants.singleTarget,
		unitTypeTarget: Constants.ground,
		preferredTarget: Constants.herosTarget,
		minRange: 0,
		maxRange: 0.8,
		attackSpeed: 1.1,
		movementSpeed: 32,
		specialAbility: Constants.stunningSurprise,
	},
	levels: [
		{
			level: 1,
			damagePerSecond: 105,
			damagePerAttack: 115.5,
			stunDuration: 2,
			hitpoints: 3650,
			researchCost: 0,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 0,
			laboratoryLevelRequired: 6,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/3/32/Diggy_field.png/revision/latest/scale-to-width-down/100?cb=20221012063800',
		},
		{
			level: 2,
			damagePerSecond: 110,
			damagePerAttack: 121,
			stunDuration: 2,
			hitpoints: 3800,
			researchCost: 185000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 3,
			laboratoryLevelRequired: 6,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/3/32/Diggy_field.png/revision/latest/scale-to-width-down/100?cb=20221012063800',
		},
		{
			level: 3,
			damagePerSecond: 115,
			damagePerAttack: 126.5,
			stunDuration: 2,
			hitpoints: 3950,
			researchCost: 195000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 4,
			laboratoryLevelRequired: 6,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/3/32/Diggy_field.png/revision/latest/scale-to-width-down/100?cb=20221012063800',
		},
		{
			level: 4,
			damagePerSecond: 120,
			damagePerAttack: 132,
			stunDuration: 2,
			hitpoints: 4100,
			researchCost: 200000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 5,
			laboratoryLevelRequired: 6,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/3/32/Diggy_field.png/revision/latest/scale-to-width-down/100?cb=20221012063800',
		},
		{
			level: 5,
			damagePerSecond: 125,
			damagePerAttack: 137.5,
			stunDuration: 2.5,
			hitpoints: 4250,
			researchCost: 210000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 5,
			laboratoryLevelRequired: 6,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/3/32/Diggy_field.png/revision/latest/scale-to-width-down/100?cb=20221012063800',
		},
		{
			level: 6,
			damagePerSecond: 130,
			damagePerAttack: 143,
			stunDuration: 2.5,
			hitpoints: 4400,
			researchCost: 215000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 6,
			laboratoryLevelRequired: 6,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/3/32/Diggy_field.png/revision/latest/scale-to-width-down/100?cb=20221012063800',
		},
		{
			level: 7,
			damagePerSecond: 135,
			damagePerAttack: 148.5,
			stunDuration: 2.5,
			hitpoints: 4550,
			researchCost: 225000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 6,
			laboratoryLevelRequired: 6,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/3/32/Diggy_field.png/revision/latest/scale-to-width-down/100?cb=20221012063800',
		},
		{
			level: 8,
			damagePerSecond: 140,
			damagePerAttack: 154,
			stunDuration: 2.5,
			hitpoints: 4700,
			researchCost: 230000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 7,
			laboratoryLevelRequired: 6,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/3/32/Diggy_field.png/revision/latest/scale-to-width-down/100?cb=20221012063800',
		},
		{
			level: 9,
			damagePerSecond: 145,
			damagePerAttack: 159.5,
			stunDuration: 2.5,
			hitpoints: 4850,
			researchCost: 240000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 7,
			laboratoryLevelRequired: 6,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/3/32/Diggy_field.png/revision/latest/scale-to-width-down/100?cb=20221012063800',
		},
		{
			level: 10,
			damagePerSecond: 150,
			damagePerAttack: 165,
			stunDuration: 3,
			hitpoints: 5000,
			researchCost: 245000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			laboratoryLevelRequired: 6,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/3/32/Diggy_field.png/revision/latest/scale-to-width-down/100?cb=20221012063800',
		},
	],
	getLevel: (level: number) => getLevel(troop.levels, level, 'level'),
}

export default troop
