import * as Constants from '@/constants'
import Army from '@IHomeVillage/troops/army.interface'
import { getLevel } from '@Utils/buildings.utility'

const troop: Army = {
	name: 'Electro Owl',
	description:
		"Electro Owl zaps enemy defenses into dust from great distance. He's mostly made of feathers though, so better keep him well protected!",
	maxLevel: 15,
	buildingLevelRequired: 2,
	buildingName: Constants.petHouse,
	avatarImgUrl:
		'https://static.wikia.nocookie.net/clashofclans/images/6/6e/Avatar_Electro_Owl.png/revision/latest/scale-to-width-down/120?cb=20210413063517',
	mode: {
		attackType: Constants.chainLightning,
		unitTypeTarget: Constants.groundAndAir,
		preferredTarget: Constants.herosTarget,
		minRange: 0,
		maxRange: 6,
		attackSpeed: 1.4,
		movementSpeed: 20,
		numberOfTargets: 2,
		chainDamageDecay: -20,
		specialAbility: Constants.highVoltage,
	},
	levels: [
		{
			level: 1,
			damagePerSecond: 100,
			damagePerAttack: 140,
			hitpoints: 1600,
			researchCost: 0,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 0,
			laboratoryLevelRequired: 2,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/8/88/Electro_Owl_field.png/revision/latest/scale-to-width-down/100?cb=20210426085034',
		},
		{
			level: 2,
			damagePerSecond: 105,
			damagePerAttack: 147,
			hitpoints: 1700,
			researchCost: 115000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 3,
			laboratoryLevelRequired: 2,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/8/88/Electro_Owl_field.png/revision/latest/scale-to-width-down/100?cb=20210426085034',
		},
		{
			level: 3,
			damagePerSecond: 110,
			damagePerAttack: 154,
			hitpoints: 1800,
			researchCost: 130000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 4,
			laboratoryLevelRequired: 2,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/8/88/Electro_Owl_field.png/revision/latest/scale-to-width-down/100?cb=20210426085034',
		},
		{
			level: 4,
			damagePerSecond: 115,
			damagePerAttack: 161,
			hitpoints: 1900,
			researchCost: 140000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 4,
			laboratoryLevelRequired: 2,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/8/88/Electro_Owl_field.png/revision/latest/scale-to-width-down/100?cb=20210426085034',
		},
		{
			level: 5,
			damagePerSecond: 120,
			damagePerAttack: 168,
			hitpoints: 2000,
			researchCost: 155000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 5,
			laboratoryLevelRequired: 2,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/8/88/Electro_Owl_field.png/revision/latest/scale-to-width-down/100?cb=20210426085034',
		},
		{
			level: 6,
			damagePerSecond: 125,
			damagePerAttack: 175,
			hitpoints: 2100,
			researchCost: 165000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 5,
			laboratoryLevelRequired: 2,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/8/88/Electro_Owl_field.png/revision/latest/scale-to-width-down/100?cb=20210426085034',
		},
		{
			level: 7,
			damagePerSecond: 130,
			damagePerAttack: 182,
			hitpoints: 2200,
			researchCost: 180000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 6,
			laboratoryLevelRequired: 2,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/8/88/Electro_Owl_field.png/revision/latest/scale-to-width-down/100?cb=20210426085034',
		},
		{
			level: 8,
			damagePerSecond: 135,
			damagePerAttack: 189,
			hitpoints: 2300,
			researchCost: 190000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 6,
			laboratoryLevelRequired: 2,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/8/88/Electro_Owl_field.png/revision/latest/scale-to-width-down/100?cb=20210426085034',
		},
		{
			level: 9,
			damagePerSecond: 140,
			damagePerAttack: 196,
			hitpoints: 2400,
			researchCost: 205000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 7,
			laboratoryLevelRequired: 2,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/8/88/Electro_Owl_field.png/revision/latest/scale-to-width-down/100?cb=20210426085034',
		},
		{
			level: 10,
			damagePerSecond: 145,
			damagePerAttack: 203,
			hitpoints: 2500,
			researchCost: 215000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 7,
			laboratoryLevelRequired: 2,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/8/88/Electro_Owl_field.png/revision/latest/scale-to-width-down/100?cb=20210426085034',
		},
		{
			level: 11,
			damagePerSecond: 150,
			damagePerAttack: 210,
			hitpoints: 2600,
			researchCost: 230000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			laboratoryLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/8/88/Electro_Owl_field.png/revision/latest/scale-to-width-down/100?cb=20210426085034',
		},
		{
			level: 12,
			damagePerSecond: 155,
			damagePerAttack: 217,
			hitpoints: 2700,
			researchCost: 250000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			laboratoryLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/8/88/Electro_Owl_field.png/revision/latest/scale-to-width-down/100?cb=20210426085034',
		},
		{
			level: 13,
			damagePerSecond: 160,
			damagePerAttack: 224,
			hitpoints: 2800,
			researchCost: 265000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			laboratoryLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/8/88/Electro_Owl_field.png/revision/latest/scale-to-width-down/100?cb=20210426085034',
		},
		{
			level: 14,
			damagePerSecond: 165,
			damagePerAttack: 231,
			hitpoints: 2900,
			researchCost: 285000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			laboratoryLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/8/88/Electro_Owl_field.png/revision/latest/scale-to-width-down/100?cb=20210426085034',
		},
		{
			level: 15,
			damagePerSecond: 170,
			damagePerAttack: 238,
			hitpoints: 3000,
			researchCost: 300000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			laboratoryLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/8/88/Electro_Owl_field.png/revision/latest/scale-to-width-down/100?cb=20210426085034',
		},
	],
	getLevel: (level: number) => getLevel(troop.levels, level, 'level'),
}

export default troop
