import * as Constants from '@/constants'
import Army from '@IHomeVillage/troops/army.interface'
import { getLevel } from '@Utils/buildings.utility'

const troop: Army = {
	name: 'Frosty',
	description:
		'Frosty is the coolest pet... literally. Not only does his icy breath cause enemies to chill out, but he also releases swarms of Frostmites to further slow down defenses and help his Hero',
	maxLevel: 10,
	buildingLevelRequired: 5,
	buildingName: Constants.petHouse,
	avatarImgUrl:
		'https://static.wikia.nocookie.net/clashofclans/images/e/e6/Avatar_Frosty.png/revision/latest/scale-to-width-down/120?cb=20221010075232',
	mode: {
		attackType: Constants.singleTarget,
		unitTypeTarget: Constants.groundAndAir,
		preferredTarget: Constants.tilesHero45,
		minRange: 0,
		maxRange: 3.5,
		attackSpeed: 1.2,
		movementSpeed: 24,
		summonCooldown: 8,
		specialAbility: Constants.freezyFriends,
	},
	levels: [
		{
			level: 1,
			damagePerSecond: 94,
			damagePerAttack: 112.8,
			frostmitesPerSummon: 1,
			maxFrostmitesSummoned: 4,
			hitpoints: 2350,
			researchCost: 0,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 0,
			laboratoryLevelRequired: 5,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/8/8b/Frosty_field.png/revision/latest/scale-to-width-down/100?cb=20221012063801',
		},
		{
			level: 2,
			damagePerSecond: 98,
			damagePerAttack: 117.6,
			frostmitesPerSummon: 1,
			maxFrostmitesSummoned: 4,
			hitpoints: 2450,
			researchCost: 185000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 3,
			laboratoryLevelRequired: 5,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/8/8b/Frosty_field.png/revision/latest/scale-to-width-down/100?cb=20221012063801',
		},
		{
			level: 3,
			damagePerSecond: 102,
			damagePerAttack: 122.4,
			frostmitesPerSummon: 1,
			maxFrostmitesSummoned: 4,
			hitpoints: 2550,
			researchCost: 190000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 4,
			laboratoryLevelRequired: 5,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/8/8b/Frosty_field.png/revision/latest/scale-to-width-down/100?cb=20221012063801',
		},
		{
			level: 4,
			damagePerSecond: 106,
			damagePerAttack: 127.2,
			frostmitesPerSummon: 1,
			maxFrostmitesSummoned: 4,
			hitpoints: 2650,
			researchCost: 200000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 5,
			laboratoryLevelRequired: 5,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/8/8b/Frosty_field.png/revision/latest/scale-to-width-down/100?cb=20221012063801',
		},
		{
			level: 5,
			damagePerSecond: 110,
			damagePerAttack: 132,
			frostmitesPerSummon: 2,
			maxFrostmitesSummoned: 8,
			hitpoints: 2800,
			researchCost: 210000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 5,
			laboratoryLevelRequired: 5,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/8/8b/Frosty_field.png/revision/latest/scale-to-width-down/100?cb=20221012063801',
		},
		{
			level: 6,
			damagePerSecond: 114,
			damagePerAttack: 136.8,
			frostmitesPerSummon: 2,
			maxFrostmitesSummoned: 8,
			hitpoints: 2900,
			researchCost: 215000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 6,
			laboratoryLevelRequired: 5,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/8/8b/Frosty_field.png/revision/latest/scale-to-width-down/100?cb=20221012063801',
		},
		{
			level: 7,
			damagePerSecond: 118,
			damagePerAttack: 141.6,
			frostmitesPerSummon: 2,
			maxFrostmitesSummoned: 8,
			hitpoints: 3000,
			researchCost: 225000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 6,
			laboratoryLevelRequired: 5,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/8/8b/Frosty_field.png/revision/latest/scale-to-width-down/100?cb=20221012063801',
		},
		{
			level: 8,
			damagePerSecond: 122,
			damagePerAttack: 146.4,
			frostmitesPerSummon: 2,
			maxFrostmitesSummoned: 8,
			hitpoints: 3100,
			researchCost: 235000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 7,
			laboratoryLevelRequired: 5,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/8/8b/Frosty_field.png/revision/latest/scale-to-width-down/100?cb=20221012063801',
		},
		{
			level: 9,
			damagePerSecond: 126,
			damagePerAttack: 151.2,
			frostmitesPerSummon: 2,
			maxFrostmitesSummoned: 8,
			hitpoints: 3200,
			researchCost: 240000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 7,
			laboratoryLevelRequired: 5,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/8/8b/Frosty_field.png/revision/latest/scale-to-width-down/100?cb=20221012063801',
		},
		{
			level: 10,
			damagePerSecond: 130,
			damagePerAttack: 156,
			frostmitesPerSummon: 2,
			maxFrostmitesSummoned: 10,
			hitpoints: 3300,
			researchCost: 250000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			laboratoryLevelRequired: 5,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/8/8b/Frosty_field.png/revision/latest/scale-to-width-down/100?cb=20221012063801',
		},
	],
	getLevel: (level: number) => getLevel(troop.levels, level, 'level'),
}

export default troop
