import * as Constants from '@/constants'
import Army from '@IHomeVillage/troops/army.interface'
import { getLevel } from '@Utils/buildings.utility'

const troop: Army = {
	name: 'L.A.S.S.I',
	description:
		'The trustiest hound to ever roam the village proper, L.A.S.S.I chases enemies with unrelenting fury. Unless they fly, in which case she just observes them intently.',
	maxLevel: 15,
	buildingLevelRequired: 1,
	buildingName: Constants.petHouse,
	baseImgUrl:
		'https://static.wikia.nocookie.net/clashofclans/images/6/62/Avatar_L.A.S.S.I.png/revision/latest/scale-to-width-down/120?cb=20210413063518',
	mode: {
		attackType: Constants.singleTarget,
		unitTypeTarget: Constants.ground,
		preferredTarget: Constants.tilesHero25,
		minRange: 0,
		maxRange: 0.6,
		attackSpeed: 0.9,
		movementSpeed: 32,
		specialAbility: Constants.highJumper,
	},
	levels: [
		{
			level: 1,
			damagePerSecond: 150,
			damagePerAttack: 135,
			hitpoints: 2700,
			researchCost: 0,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 0,
			laboratoryLevelRequired: 1,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/5/5a/LASSI_field.png/revision/latest/scale-to-width-down/100?cb=20210414082702',
		},
		{
			level: 2,
			damagePerSecond: 160,
			damagePerAttack: 144,
			hitpoints: 2800,
			researchCost: 100000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 3,
			laboratoryLevelRequired: 1,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/5/5a/LASSI_field.png/revision/latest/scale-to-width-down/100?cb=20210414082702',
		},
		{
			level: 3,
			damagePerSecond: 170,
			damagePerAttack: 153,
			hitpoints: 2900,
			researchCost: 110000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 4,
			laboratoryLevelRequired: 1,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/5/5a/LASSI_field.png/revision/latest/scale-to-width-down/100?cb=20210414082702',
		},
		{
			level: 4,
			damagePerSecond: 180,
			damagePerAttack: 162,
			hitpoints: 3000,
			researchCost: 125000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 4,
			laboratoryLevelRequired: 1,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/5/5a/LASSI_field.png/revision/latest/scale-to-width-down/100?cb=20210414082702',
		},
		{
			level: 5,
			damagePerSecond: 190,
			damagePerAttack: 171,
			hitpoints: 3100,
			researchCost: 135000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 5,
			laboratoryLevelRequired: 1,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/5/5a/LASSI_field.png/revision/latest/scale-to-width-down/100?cb=20210414082702',
		},
		{
			level: 6,
			damagePerSecond: 200,
			damagePerAttack: 180,
			hitpoints: 3200,
			researchCost: 150000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 5,
			laboratoryLevelRequired: 1,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/5/5a/LASSI_field.png/revision/latest/scale-to-width-down/100?cb=20210414082702',
		},
		{
			level: 7,
			damagePerSecond: 210,
			damagePerAttack: 189,
			hitpoints: 3300,
			researchCost: 160000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 6,
			laboratoryLevelRequired: 1,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/5/5a/LASSI_field.png/revision/latest/scale-to-width-down/100?cb=20210414082702',
		},
		{
			level: 8,
			damagePerSecond: 220,
			damagePerAttack: 198,
			hitpoints: 3400,
			researchCost: 175000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 6,
			laboratoryLevelRequired: 1,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/5/5a/LASSI_field.png/revision/latest/scale-to-width-down/100?cb=20210414082702',
		},
		{
			level: 9,
			damagePerSecond: 230,
			damagePerAttack: 207,
			hitpoints: 3500,
			researchCost: 185000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 7,
			laboratoryLevelRequired: 1,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/5/5a/LASSI_field.png/revision/latest/scale-to-width-down/100?cb=20210414082702',
		},
		{
			level: 10,
			damagePerSecond: 240,
			damagePerAttack: 216,
			hitpoints: 3600,
			researchCost: 200000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 7,
			laboratoryLevelRequired: 1,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/5/5a/LASSI_field.png/revision/latest/scale-to-width-down/100?cb=20210414082702',
		},
		{
			level: 11,
			damagePerSecond: 250,
			damagePerAttack: 225,
			hitpoints: 3700,
			researchCost: 215000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			laboratoryLevelRequired: 5,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/5/5a/LASSI_field.png/revision/latest/scale-to-width-down/100?cb=20210414082702',
		},
		{
			level: 12,
			damagePerSecond: 260,
			damagePerAttack: 234,
			hitpoints: 3800,
			researchCost: 230000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			laboratoryLevelRequired: 5,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/5/5a/LASSI_field.png/revision/latest/scale-to-width-down/100?cb=20210414082702',
		},
		{
			level: 13,
			damagePerSecond: 270,
			damagePerAttack: 243,
			hitpoints: 3900,
			researchCost: 245000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			laboratoryLevelRequired: 5,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/5/5a/LASSI_field.png/revision/latest/scale-to-width-down/100?cb=20210414082702',
		},
		{
			level: 14,
			damagePerSecond: 280,
			damagePerAttack: 252,
			hitpoints: 4000,
			researchCost: 260000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			laboratoryLevelRequired: 5,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/5/5a/LASSI_field.png/revision/latest/scale-to-width-down/100?cb=20210414082702',
		},
		{
			level: 15,
			damagePerSecond: 290,
			damagePerAttack: 261,
			hitpoints: 4100,
			researchCost: 275000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			laboratoryLevelRequired: 5,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/5/5a/LASSI_field.png/revision/latest/scale-to-width-down/100?cb=20210414082702',
		},
	],
	getLevel: (level: number) => getLevel(troop.levels, level, 'level'),
}

export default troop
