import * as Constants from '@/constants'
import Army from '@IHomeVillage/troops/army.interface'
import { getLevel } from '@Utils/buildings.utility'

const troop: Army = {
	name: 'Mighty Yak',
	description:
		'Built like a Siege Machine, the Mighty Yak has a knack for knocking down Walls it comes in contact with. It also flies into a rage if you knock out its companion.',
	maxLevel: 15,
	buildingLevelRequired: 3,
	buildingName: Constants.petHouse,
	avatarImgUrl:
		'https://static.wikia.nocookie.net/clashofclans/images/0/03/Avatar_Mighty_Yak.png/revision/latest/scale-to-width-down/120?cb=20210413063519',
	mode: {
		attackType: Constants.singleTarget,
		unitTypeTarget: Constants.ground,
		preferredTarget: Constants.tilesHero7,
		minRange: 0,
		maxRange: 1.2,
		attackSpeed: 2.1,
		movementSpeed: 20,
		specialAbility: Constants.wallBuster,
		rageDuration: 8,
		rageSpeedIncrease: 16,
		rageDamageIncrease: 70,
	},
	levels: [
		{
			level: 1,
			damagePerSecond: 60,
			damagePerAttack: 126,
			damageVsWalls: 2520,
			hitpoints: 3750,
			researchCost: 0,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 0,
			laboratoryLevelRequired: 3,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/66/Mighty_Yak_field.png/revision/latest/scale-to-width-down/100?cb=20210414082711',
		},
		{
			level: 2,
			damagePerSecond: 64,
			damagePerAttack: 134.4,
			damageVsWalls: 2688,
			hitpoints: 4000,
			researchCost: 140000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 3,
			laboratoryLevelRequired: 3,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/66/Mighty_Yak_field.png/revision/latest/scale-to-width-down/100?cb=20210414082711',
		},
		{
			level: 3,
			damagePerSecond: 68,
			damagePerAttack: 142.8,
			damageVsWalls: 2856,
			hitpoints: 4250,
			researchCost: 155000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 4,
			laboratoryLevelRequired: 3,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/66/Mighty_Yak_field.png/revision/latest/scale-to-width-down/100?cb=20210414082711',
		},
		{
			level: 4,
			damagePerSecond: 72,
			damagePerAttack: 151.2,
			damageVsWalls: 3024,
			hitpoints: 4500,
			researchCost: 175000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 4,
			laboratoryLevelRequired: 3,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/66/Mighty_Yak_field.png/revision/latest/scale-to-width-down/100?cb=20210414082711',
		},
		{
			level: 5,
			damagePerSecond: 76,
			damagePerAttack: 159.6,
			damageVsWalls: 3192,
			hitpoints: 4750,
			researchCost: 190000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 5,
			laboratoryLevelRequired: 3,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/66/Mighty_Yak_field.png/revision/latest/scale-to-width-down/100?cb=20210414082711',
		},
		{
			level: 6,
			damagePerSecond: 80,
			damagePerAttack: 168,
			damageVsWalls: 3360,
			hitpoints: 4950,
			researchCost: 210000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 5,
			laboratoryLevelRequired: 3,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/66/Mighty_Yak_field.png/revision/latest/scale-to-width-down/100?cb=20210414082711',
		},
		{
			level: 7,
			damagePerSecond: 84,
			damagePerAttack: 176.4,
			damageVsWalls: 3528,
			hitpoints: 5100,
			researchCost: 215000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 6,
			laboratoryLevelRequired: 3,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/66/Mighty_Yak_field.png/revision/latest/scale-to-width-down/100?cb=20210414082711',
		},
		{
			level: 8,
			damagePerSecond: 88,
			damagePerAttack: 184.8,
			damageVsWalls: 3696,
			hitpoints: 5250,
			researchCost: 225000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 6,
			laboratoryLevelRequired: 3,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/66/Mighty_Yak_field.png/revision/latest/scale-to-width-down/100?cb=20210414082711',
		},
		{
			level: 9,
			damagePerSecond: 92,
			damagePerAttack: 193.2,
			damageVsWalls: 3864,
			hitpoints: 5400,
			researchCost: 230000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 7,
			laboratoryLevelRequired: 3,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/66/Mighty_Yak_field.png/revision/latest/scale-to-width-down/100?cb=20210414082711',
		},
		{
			level: 10,
			damagePerSecond: 96,
			damagePerAttack: 201.6,
			damageVsWalls: 4032,
			hitpoints: 5550,
			researchCost: 240000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 7,
			laboratoryLevelRequired: 3,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/66/Mighty_Yak_field.png/revision/latest/scale-to-width-down/100?cb=20210414082711',
		},
		{
			level: 11,
			damagePerSecond: 100,
			damagePerAttack: 210,
			damageVsWalls: 4200,
			hitpoints: 5700,
			researchCost: 250000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			laboratoryLevelRequired: 7,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/66/Mighty_Yak_field.png/revision/latest/scale-to-width-down/100?cb=20210414082711',
		},
		{
			level: 12,
			damagePerSecond: 104,
			damagePerAttack: 218.4,
			damageVsWalls: 4368,
			hitpoints: 5850,
			researchCost: 260000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			laboratoryLevelRequired: 7,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/66/Mighty_Yak_field.png/revision/latest/scale-to-width-down/100?cb=20210414082711',
		},
		{
			level: 13,
			damagePerSecond: 108,
			damagePerAttack: 226.8,
			damageVsWalls: 4536,
			hitpoints: 6000,
			researchCost: 270000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			laboratoryLevelRequired: 7,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/66/Mighty_Yak_field.png/revision/latest/scale-to-width-down/100?cb=20210414082711',
		},
		{
			level: 14,
			damagePerSecond: 112,
			damagePerAttack: 235.2,
			damageVsWalls: 4704,
			hitpoints: 6150,
			researchCost: 280000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			laboratoryLevelRequired: 7,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/66/Mighty_Yak_field.png/revision/latest/scale-to-width-down/100?cb=20210414082711',
		},
		{
			level: 15,
			damagePerSecond: 116,
			damagePerAttack: 243.6,
			damageVsWalls: 4872,
			hitpoints: 6300,
			researchCost: 290000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			laboratoryLevelRequired: 7,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/66/Mighty_Yak_field.png/revision/latest/scale-to-width-down/100?cb=20210414082711',
		},
	],
	getLevel: (level: number) => getLevel(troop.levels, level, 'level'),
}

export default troop
