import * as Constants from '@/constants'
import Army from '@IHomeVillage/troops/army.interface'
import { getLevel } from '@Utils/buildings.utility'

const troop: Army = {
	name: 'Phoenix',
	description:
		'A true friend will egg you on when things get rough. Phoenix starts the battle as a helpless egg, but at the moment her Hero might go down, she hatches. The furious fiery fowl then gives temporary invulnerability to its Hero and engages nearby enemies.',
	maxLevel: 10,
	buildingLevelRequired: 8,
	buildingName: Constants.petHouse,
	avatarImgUrl:
		'https://static.wikia.nocookie.net/clashofclans/images/4/4f/Avatar_Phoenix.png/revision/latest/scale-to-width-down/120?cb=20221010075232',
	eggImgUrl:
		'https://static.wikia.nocookie.net/clashofclans/images/7/7c/Phoenix_egg.png/revision/latest/scale-to-width-down/40?cb=20221012063802',
	mode: {
		attackType: Constants.areaSplash,
		unitTypeTarget: Constants.groundAndAir,
		preferredTarget: Constants.herosTarget,
		minRange: 0,
		maxRange: 2.5,
		attackSpeed: 1,
		movementSpeed: 16,
		specialAbility: Constants.fieryFinale,
	},
	levels: [
		{
			level: 1,
			damagePerSecond: 178,
			damagePerAttack: 178,
			reviveDuration: 6,
			hitpoints: 3120,
			researchCost: 0,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 0,
			laboratoryLevelRequired: 8,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/d/db/Phoenix_field.png/revision/latest/scale-to-width-down/100?cb=20221012063804',
		},
		{
			level: 2,
			damagePerSecond: 186,
			damagePerAttack: 186,
			reviveDuration: 6,
			hitpoints: 3240,
			researchCost: 195000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 3,
			laboratoryLevelRequired: 8,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/d/db/Phoenix_field.png/revision/latest/scale-to-width-down/100?cb=20221012063804',
		},
		{
			level: 3,
			damagePerSecond: 194,
			damagePerAttack: 194,
			reviveDuration: 6,
			hitpoints: 3360,
			researchCost: 205000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 4,
			laboratoryLevelRequired: 8,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/d/db/Phoenix_field.png/revision/latest/scale-to-width-down/100?cb=20221012063804',
		},
		{
			level: 4,
			damagePerSecond: 202,
			damagePerAttack: 202,
			reviveDuration: 6,
			hitpoints: 3480,
			researchCost: 210000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 5,
			laboratoryLevelRequired: 8,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/d/db/Phoenix_field.png/revision/latest/scale-to-width-down/100?cb=20221012063804',
		},
		{
			level: 5,
			damagePerSecond: 210,
			damagePerAttack: 210,
			reviveDuration: 7,
			hitpoints: 3600,
			researchCost: 220000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 5,
			laboratoryLevelRequired: 8,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/d/db/Phoenix_field.png/revision/latest/scale-to-width-down/100?cb=20221012063804',
		},
		{
			level: 6,
			damagePerSecond: 218,
			damagePerAttack: 218,
			reviveDuration: 7,
			hitpoints: 3720,
			researchCost: 225000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 6,
			laboratoryLevelRequired: 8,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/d/db/Phoenix_field.png/revision/latest/scale-to-width-down/100?cb=20221012063804',
		},
		{
			level: 7,
			damagePerSecond: 226,
			damagePerAttack: 226,
			reviveDuration: 7,
			hitpoints: 3840,
			researchCost: 235000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 6,
			laboratoryLevelRequired: 8,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/d/db/Phoenix_field.png/revision/latest/scale-to-width-down/100?cb=20221012063804',
		},
		{
			level: 8,
			damagePerSecond: 234,
			damagePerAttack: 234,
			reviveDuration: 7,
			hitpoints: 3960,
			researchCost: 240000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 7,
			laboratoryLevelRequired: 8,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/d/db/Phoenix_field.png/revision/latest/scale-to-width-down/100?cb=20221012063804',
		},
		{
			level: 9,
			damagePerSecond: 242,
			damagePerAttack: 242,
			reviveDuration: 7,
			hitpoints: 4080,
			researchCost: 250000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 7,
			laboratoryLevelRequired: 8,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/d/db/Phoenix_field.png/revision/latest/scale-to-width-down/100?cb=20221012063804',
		},
		{
			level: 10,
			damagePerSecond: 250,
			damagePerAttack: 250,
			reviveDuration: 8,
			hitpoints: 4200,
			researchCost: 255000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			laboratoryLevelRequired: 8,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/d/db/Phoenix_field.png/revision/latest/scale-to-width-down/100?cb=20221012063804',
		},
	],
	getLevel: (level: number) => getLevel(troop.levels, level, 'level'),
}

export default troop
