import * as Constants from '@/constants'
import Army from '@IHomeVillage/troops/army.interface'
import { getLevel } from '@Utils/buildings.utility'

const troop: Army = {
	name: 'Spirit Fox',
	description:
		"An extremely shy creature, who's happiest alone in the woods outside the Village. When called to battle, Spirit Fox fights fiercely alongside their hero and helps them with a little invisibility.",
	maxLevel: 10,
	buildingLevelRequired: 9,
	buildingName: Constants.petHouse,
	baseImgUrl:
		'https://static.wikia.nocookie.net/clashofclans/images/5/52/Avatar_Spirit_Fox.png/revision/latest/scale-to-width-down/120?cb=20231213215131',
	mode: {
		attackType: Constants.singleTarget,
		unitTypeTarget: Constants.ground,
		preferredTarget: Constants.tilesHero45,
		minRange: 0,
		maxRange: 2.5,
		attackSpeed: 1.6,
		movementSpeed: 24,
		specialAbility: Constants.spiritWalk,
	},
	levels: [
		{
			level: 1,
			damagePerSecond: 108,
			damagePerAttack: 172.8,
			invisibilityDuration: 3,
			hitpoints: 1900,
			researchCost: 0,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 0,
			laboratoryLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/0/06/Spirit_Fox_field.png/revision/latest/scale-to-width-down/100?cb=20231211145946',
		},
		{
			level: 2,
			damagePerSecond: 116,
			damagePerAttack: 185.6,
			invisibilityDuration: 3,
			hitpoints: 2000,
			researchCost: 225000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 3,
			laboratoryLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/0/06/Spirit_Fox_field.png/revision/latest/scale-to-width-down/100?cb=20231211145946',
		},
		{
			level: 3,
			damagePerSecond: 124,
			damagePerAttack: 198.4,
			invisibilityDuration: 3,
			hitpoints: 2100,
			researchCost: 235000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 4,
			laboratoryLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/0/06/Spirit_Fox_field.png/revision/latest/scale-to-width-down/100?cb=20231211145946',
		},
		{
			level: 4,
			damagePerSecond: 132,
			damagePerAttack: 211.2,
			invisibilityDuration: 3,
			hitpoints: 2200,
			researchCost: 245000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 5,
			laboratoryLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/0/06/Spirit_Fox_field.png/revision/latest/scale-to-width-down/100?cb=20231211145946',
		},
		{
			level: 5,
			damagePerSecond: 140,
			damagePerAttack: 224,
			invisibilityDuration: 3.5,
			hitpoints: 2300,
			researchCost: 255000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 5,
			laboratoryLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/0/06/Spirit_Fox_field.png/revision/latest/scale-to-width-down/100?cb=20231211145946',
		},
		{
			level: 6,
			damagePerSecond: 148,
			damagePerAttack: 236.8,
			invisibilityDuration: 3.5,
			hitpoints: 2400,
			researchCost: 265000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 6,
			laboratoryLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/0/06/Spirit_Fox_field.png/revision/latest/scale-to-width-down/100?cb=20231211145946',
		},
		{
			level: 7,
			damagePerSecond: 156,
			damagePerAttack: 249.6,
			invisibilityDuration: 3.5,
			hitpoints: 2500,
			researchCost: 275000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 6,
			laboratoryLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/0/06/Spirit_Fox_field.png/revision/latest/scale-to-width-down/100?cb=20231211145946',
		},
		{
			level: 8,
			damagePerSecond: 164,
			damagePerAttack: 262.4,
			invisibilityDuration: 3.5,
			hitpoints: 2600,
			researchCost: 285000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 7,
			laboratoryLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/0/06/Spirit_Fox_field.png/revision/latest/scale-to-width-down/100?cb=20231211145946',
		},
		{
			level: 9,
			damagePerSecond: 172,
			damagePerAttack: 275.6,
			invisibilityDuration: 3.5,
			hitpoints: 2700,
			researchCost: 295000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 7,
			laboratoryLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/0/06/Spirit_Fox_field.png/revision/latest/scale-to-width-down/100?cb=20231211145946',
		},
		{
			level: 10,
			damagePerSecond: 180,
			damagePerAttack: 288,
			invisibilityDuration: 4,
			hitpoints: 2800,
			researchCost: 315000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			laboratoryLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/0/06/Spirit_Fox_field.png/revision/latest/scale-to-width-down/100?cb=20231211145946',
		},
	],
	getLevel: (level: number) => getLevel(troop.levels, level, 'level'),
}

export default troop
