import * as Constants from '@/constants'
import Army from '@IHomeVillage/troops/army.interface'
import { getLevel } from '@Utils/buildings.utility'

const troop: Army = {
	name: 'Unicorn',
	description:
		"Unicorns have severe trust issues, but overcoming them with love and patience is totally worth it. They'll heal up any minor or major scrapes as well as any Healer!",
	maxLevel: 10,
	buildingLevelRequired: 4,
	buildingName: Constants.petHouse,
	avatarImgUrl:
		'https://static.wikia.nocookie.net/clashofclans/images/a/ac/Avatar_Unicorn.png/revision/latest/scale-to-width-down/120?cb=20210413063520',
	mode: {
		attackType: Constants.singleTarget,
		unitTypeTarget: Constants.groundAndAir,
		preferredTarget: Constants.hero,
		minRange: 0,
		maxRange: 2.5,
		healingSpeed: 1,
		movementSpeed: 16,
		specialAbility: Constants.personalHealer,
	},
	levels: [
		{
			level: 1,
			healingPerSecond: 50,
			healingPerPulse: 50,
			hitpoints: 1400,
			researchCost: 0,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 0,
			laboratoryLevelRequired: 4,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/67/Unicorn_field.png/revision/latest/scale-to-width-down/100?cb=20210414082649',
		},
		{
			level: 2,
			healingPerSecond: 53,
			healingPerPulse: 53,
			hitpoints: 1450,
			researchCost: 180000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 3,
			laboratoryLevelRequired: 4,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/67/Unicorn_field.png/revision/latest/scale-to-width-down/100?cb=20210414082649',
		},
		{
			level: 3,
			healingPerSecond: 56,
			healingPerPulse: 56,
			hitpoints: 1500,
			researchCost: 190000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 4,
			laboratoryLevelRequired: 4,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/67/Unicorn_field.png/revision/latest/scale-to-width-down/100?cb=20210414082649',
		},
		{
			level: 4,
			healingPerSecond: 58,
			healingPerPulse: 58,
			hitpoints: 1550,
			researchCost: 200000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 4,
			laboratoryLevelRequired: 4,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/67/Unicorn_field.png/revision/latest/scale-to-width-down/100?cb=20210414082649',
		},
		{
			level: 5,
			healingPerSecond: 60,
			healingPerPulse: 60,
			hitpoints: 1600,
			researchCost: 210000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 5,
			laboratoryLevelRequired: 4,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/67/Unicorn_field.png/revision/latest/scale-to-width-down/100?cb=20210414082649',
		},
		{
			level: 6,
			healingPerSecond: 62,
			healingPerPulse: 62,
			hitpoints: 1675,
			researchCost: 220000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 5,
			laboratoryLevelRequired: 4,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/67/Unicorn_field.png/revision/latest/scale-to-width-down/100?cb=20210414082649',
		},
		{
			level: 7,
			healingPerSecond: 64,
			healingPerPulse: 64,
			hitpoints: 1725,
			researchCost: 230000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 6,
			laboratoryLevelRequired: 4,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/67/Unicorn_field.png/revision/latest/scale-to-width-down/100?cb=20210414082649',
		},
		{
			level: 8,
			healingPerSecond: 66,
			healingPerPulse: 66,
			hitpoints: 1800,
			researchCost: 240000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 6,
			laboratoryLevelRequired: 4,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/67/Unicorn_field.png/revision/latest/scale-to-width-down/100?cb=20210414082649',
		},
		{
			level: 9,
			healingPerSecond: 68,
			healingPerPulse: 68,
			hitpoints: 1875,
			researchCost: 250000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 7,
			laboratoryLevelRequired: 4,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/67/Unicorn_field.png/revision/latest/scale-to-width-down/100?cb=20210414082649',
		},
		{
			level: 10,
			healingPerSecond: 70,
			healingPerPulse: 70,
			hitpoints: 1950,
			researchCost: 260000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 7,
			laboratoryLevelRequired: 4,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/67/Unicorn_field.png/revision/latest/scale-to-width-down/100?cb=20210414082649',
		},
	],
	getLevel: (level: number) => getLevel(troop.levels, level, 'level'),
}

export default troop
