import * as Constants from '@/constants'
import Army from '@IHomeVillage/troops/army.interface'
import { getLevel, getHallLevel } from '@Utils/buildings.utility'

const troop: Army = {
	name: 'Archer Queen',
	description:
		'Towering above all other archers, this graceful huntress is a master of destructive force, Alhough her health is modest, she snipes targets from afar with her powerful X-bow. As a defender she guards the village with a vengeance.',
	maxLevel: 95,
	avatarImgUrl:
		'https://static.wikia.nocookie.net/clashofclans/images/b/b6/Avatar_Hero_Archer_Queen.png/revision/latest/scale-to-width-down/100?cb=20200913051658',
	mode: {
		attackType: Constants.ranged,
		unitTypeTarget: Constants.groundAndAir,
		preferredTarget: Constants.any,
		minRange: 0,
		maxRange: 5,
		attackSpeed: 0.75,
		movementSpeed: 24,
		searchRadius: 10,
	},
	townHallDetails: [
		{ townHallLevel: 1, availableCount: 0, maxLevel: 0 },
		{ townHallLevel: 2, availableCount: 0, maxLevel: 0 },
		{ townHallLevel: 3, availableCount: 0, maxLevel: 0 },
		{ townHallLevel: 4, availableCount: 0, maxLevel: 0 },
		{ townHallLevel: 5, availableCount: 0, maxLevel: 0 },
		{ townHallLevel: 6, availableCount: 0, maxLevel: 0 },
		{ townHallLevel: 7, availableCount: 0, maxLevel: 0 },
		{ townHallLevel: 8, availableCount: 0, maxLevel: 0 },
		{ townHallLevel: 9, availableCount: 1, maxLevel: 30 },
		{ townHallLevel: 10, availableCount: 1, maxLevel: 40 },
		{ townHallLevel: 11, availableCount: 1, maxLevel: 50 },
		{ townHallLevel: 12, availableCount: 1, maxLevel: 65 },
		{ townHallLevel: 13, availableCount: 1, maxLevel: 75 },
		{ townHallLevel: 14, availableCount: 1, maxLevel: 80 },
		{ townHallLevel: 15, availableCount: 1, maxLevel: 90 },
		{ townHallLevel: 16, availableCount: 1, maxLevel: 95 },
	],
	levels: [
		{
			level: 1,
			damagePerSecond: 136,
			damagePerAttack: 102,
			hitpoints: 580,
			healthRecovery: 115,
			regenTime: 10,
			researchCost: 10000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 0,
			townHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/7/72/Archer_Queen1.png/revision/latest?cb=20170811230321',
		},
		{
			level: 2,
			damagePerSecond: 139,
			damagePerAttack: 104.25,
			hitpoints: 592,
			healthRecovery: 115,
			regenTime: 10,
			researchCost: 10000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 4,
			researchTimeDay: 0,
			townHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/7/72/Archer_Queen1.png/revision/latest?cb=20170811230321',
		},
		{
			level: 3,
			damagePerSecond: 143,
			damagePerAttack: 107.25,
			hitpoints: 604,
			healthRecovery: 115,
			regenTime: 10,
			researchCost: 11000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 6,
			researchTimeDay: 0,
			townHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/7/72/Archer_Queen1.png/revision/latest?cb=20170811230321',
		},
		{
			level: 4,
			damagePerSecond: 146,
			damagePerAttack: 109.5,
			hitpoints: 617,
			healthRecovery: 115,
			regenTime: 10,
			researchCost: 12000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 8,
			researchTimeDay: 0,
			townHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/7/72/Archer_Queen1.png/revision/latest?cb=20170811230321',
		},
		{
			level: 5,
			damagePerSecond: 150,
			damagePerAttack: 112.5,
			hitpoints: 630,
			healthRecovery: 130,
			regenTime: 12,
			researchCost: 13000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 10,
			researchTimeDay: 0,
			townHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/7/72/Archer_Queen1.png/revision/latest?cb=20170811230321',
		},
		{
			level: 6,
			damagePerSecond: 154,
			damagePerAttack: 115.5,
			hitpoints: 643,
			healthRecovery: 130,
			regenTime: 12,
			researchCost: 14000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 0,
			townHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/7/72/Archer_Queen1.png/revision/latest?cb=20170811230321',
		},
		{
			level: 7,
			damagePerSecond: 157,
			damagePerAttack: 117.75,
			hitpoints: 657,
			healthRecovery: 130,
			regenTime: 12,
			researchCost: 15000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 14,
			researchTimeDay: 0,
			townHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/7/72/Archer_Queen1.png/revision/latest?cb=20170811230321',
		},
		{
			level: 8,
			damagePerSecond: 162,
			damagePerAttack: 121.5,
			hitpoints: 670,
			healthRecovery: 130,
			regenTime: 12,
			researchCost: 16000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 16,
			researchTimeDay: 0,
			townHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/7/72/Archer_Queen1.png/revision/latest?cb=20170811230321',
		},
		{
			level: 9,
			damagePerSecond: 165,
			damagePerAttack: 123.75,
			hitpoints: 685,
			healthRecovery: 130,
			regenTime: 12,
			researchCost: 17000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 18,
			researchTimeDay: 0,
			townHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/7/72/Archer_Queen1.png/revision/latest?cb=20170811230321',
		},
		{
			level: 10,
			damagePerSecond: 169,
			damagePerAttack: 126.75,
			hitpoints: 699,
			healthRecovery: 145,
			regenTime: 14,
			researchCost: 18000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 20,
			researchTimeDay: 0,
			townHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/3/3b/Archer_Queen10.png/revision/latest?cb=20170811230341',
		},
		{
			level: 11,
			damagePerSecond: 173,
			damagePerAttack: 129.75,
			hitpoints: 714,
			healthRecovery: 145,
			regenTime: 14,
			researchCost: 19000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 22,
			researchTimeDay: 0,
			townHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/3/3b/Archer_Queen10.png/revision/latest?cb=20170811230341',
		},
		{
			level: 12,
			damagePerSecond: 178,
			damagePerAttack: 133.5,
			hitpoints: 729,
			healthRecovery: 145,
			regenTime: 14,
			researchCost: 20000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 1,
			townHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/3/3b/Archer_Queen10.png/revision/latest?cb=20170811230341',
		},
		{
			level: 13,
			damagePerSecond: 183,
			damagePerAttack: 137.25,
			hitpoints: 744,
			healthRecovery: 145,
			regenTime: 14,
			researchCost: 21000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 1,
			townHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/3/3b/Archer_Queen10.png/revision/latest?cb=20170811230341',
		},
		{
			level: 14,
			damagePerSecond: 187,
			damagePerAttack: 140.25,
			hitpoints: 759,
			healthRecovery: 145,
			regenTime: 14,
			researchCost: 22000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 1,
			townHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/3/3b/Archer_Queen10.png/revision/latest?cb=20170811230341',
		},
		{
			level: 15,
			damagePerSecond: 192,
			damagePerAttack: 144,
			hitpoints: 775,
			healthRecovery: 160,
			regenTime: 16,
			researchCost: 23000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 1,
			townHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/3/3b/Archer_Queen10.png/revision/latest?cb=20170811230341',
		},
		{
			level: 16,
			damagePerSecond: 196,
			damagePerAttack: 147,
			hitpoints: 792,
			healthRecovery: 160,
			regenTime: 16,
			researchCost: 24000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 1,
			townHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/3/3b/Archer_Queen10.png/revision/latest?cb=20170811230341',
		},
		{
			level: 17,
			damagePerSecond: 201,
			damagePerAttack: 150.75,
			hitpoints: 808,
			healthRecovery: 160,
			regenTime: 16,
			researchCost: 25000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 1,
			townHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/3/3b/Archer_Queen10.png/revision/latest?cb=20170811230341',
		},
		{
			level: 18,
			damagePerSecond: 207,
			damagePerAttack: 155.25,
			hitpoints: 826,
			healthRecovery: 160,
			regenTime: 16,
			researchCost: 27000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 1,
			townHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/3/3b/Archer_Queen10.png/revision/latest?cb=20170811230341',
		},
		{
			level: 19,
			damagePerSecond: 212,
			damagePerAttack: 159,
			hitpoints: 842,
			healthRecovery: 160,
			regenTime: 16,
			researchCost: 28000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 1,
			townHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/3/3b/Archer_Queen10.png/revision/latest?cb=20170811230341',
		},
		{
			level: 20,
			damagePerSecond: 217,
			damagePerAttack: 162.75,
			hitpoints: 861,
			healthRecovery: 175,
			regenTime: 18,
			researchCost: 30000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 2,
			townHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/a/a6/Archer_Queen20.png/revision/latest?cb=20170811230403',
		},
		{
			level: 21,
			damagePerSecond: 223,
			damagePerAttack: 167.25,
			hitpoints: 878,
			healthRecovery: 175,
			regenTime: 18,
			researchCost: 31000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 2,
			townHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/a/a6/Archer_Queen20.png/revision/latest?cb=20170811230403',
		},
		{
			level: 22,
			damagePerSecond: 228,
			damagePerAttack: 171,
			hitpoints: 897,
			healthRecovery: 175,
			regenTime: 18,
			researchCost: 33000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 2,
			townHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/a/a6/Archer_Queen20.png/revision/latest?cb=20170811230403',
		},
		{
			level: 23,
			damagePerSecond: 234,
			damagePerAttack: 175.5,
			hitpoints: 916,
			healthRecovery: 175,
			regenTime: 18,
			researchCost: 34000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 2,
			townHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/a/a6/Archer_Queen20.png/revision/latest?cb=20170811230403',
		},
		{
			level: 24,
			damagePerSecond: 240,
			damagePerAttack: 180,
			hitpoints: 935,
			healthRecovery: 175,
			regenTime: 18,
			researchCost: 36000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 2,
			townHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/a/a6/Archer_Queen20.png/revision/latest?cb=20170811230403',
		},
		{
			level: 25,
			damagePerSecond: 246,
			damagePerAttack: 184.5,
			hitpoints: 954,
			healthRecovery: 190,
			regenTime: 20,
			researchCost: 37000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 2,
			townHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/a/a6/Archer_Queen20.png/revision/latest?cb=20170811230403',
		},
		{
			level: 26,
			damagePerSecond: 252,
			damagePerAttack: 189,
			hitpoints: 974,
			healthRecovery: 190,
			regenTime: 20,
			researchCost: 39000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 2,
			townHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/a/a6/Archer_Queen20.png/revision/latest?cb=20170811230403',
		},
		{
			level: 27,
			damagePerSecond: 258,
			damagePerAttack: 193.5,
			hitpoints: 995,
			healthRecovery: 190,
			regenTime: 20,
			researchCost: 40000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 2,
			townHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/a/a6/Archer_Queen20.png/revision/latest?cb=20170811230403',
		},
		{
			level: 28,
			damagePerSecond: 264,
			damagePerAttack: 198,
			hitpoints: 1016,
			healthRecovery: 190,
			regenTime: 20,
			researchCost: 42000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 2,
			townHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/a/a6/Archer_Queen20.png/revision/latest?cb=20170811230403',
		},
		{
			level: 29,
			damagePerSecond: 271,
			damagePerAttack: 203.25,
			hitpoints: 1038,
			healthRecovery: 190,
			regenTime: 20,
			researchCost: 43000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 2,
			townHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/a/a6/Archer_Queen20.png/revision/latest?cb=20170811230403',
		},
		{
			level: 30,
			damagePerSecond: 278,
			damagePerAttack: 208.5,
			hitpoints: 1059,
			healthRecovery: 205,
			regenTime: 22,
			researchCost: 45000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 3,
			townHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/a/a6/Archer_Queen20.png/revision/latest?cb=20170811230403',
		},
		{
			level: 31,
			damagePerSecond: 285,
			damagePerAttack: 213.75,
			hitpoints: 1082,
			healthRecovery: 205,
			regenTime: 22,
			researchCost: 47000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 3,
			townHallLevelRequired: 10,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/a/a6/Archer_Queen20.png/revision/latest?cb=20170811230403',
		},
		{
			level: 32,
			damagePerSecond: 292,
			damagePerAttack: 219,
			hitpoints: 1104,
			healthRecovery: 205,
			regenTime: 22,
			researchCost: 49000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 3,
			townHallLevelRequired: 10,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/a/a6/Archer_Queen20.png/revision/latest?cb=20170811230403',
		},
		{
			level: 33,
			damagePerSecond: 299,
			damagePerAttack: 224.25,
			hitpoints: 1127,
			healthRecovery: 205,
			regenTime: 22,
			researchCost: 51000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 3,
			townHallLevelRequired: 10,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/a/a6/Archer_Queen20.png/revision/latest?cb=20170811230403',
		},
		{
			level: 34,
			damagePerSecond: 307,
			damagePerAttack: 230.25,
			hitpoints: 1151,
			healthRecovery: 205,
			regenTime: 22,
			researchCost: 53000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 3,
			townHallLevelRequired: 10,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/a/a6/Archer_Queen20.png/revision/latest?cb=20170811230403',
		},
		{
			level: 35,
			damagePerSecond: 315,
			damagePerAttack: 236.25,
			hitpoints: 1175,
			healthRecovery: 220,
			regenTime: 24,
			researchCost: 55000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 3,
			townHallLevelRequired: 10,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/a/a6/Archer_Queen20.png/revision/latest?cb=20170811230403',
		},
		{
			level: 36,
			damagePerSecond: 322,
			damagePerAttack: 241.5,
			hitpoints: 1200,
			healthRecovery: 220,
			regenTime: 24,
			researchCost: 57000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 3,
			townHallLevelRequired: 10,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/a/a6/Archer_Queen20.png/revision/latest?cb=20170811230403',
		},
		{
			level: 37,
			damagePerSecond: 331,
			damagePerAttack: 248.25,
			hitpoints: 1226,
			healthRecovery: 220,
			regenTime: 24,
			researchCost: 59000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 3,
			townHallLevelRequired: 10,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/a/a6/Archer_Queen20.png/revision/latest?cb=20170811230403',
		},
		{
			level: 38,
			damagePerSecond: 338,
			damagePerAttack: 253.5,
			hitpoints: 1251,
			healthRecovery: 220,
			regenTime: 24,
			researchCost: 61000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 3,
			townHallLevelRequired: 10,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/a/a6/Archer_Queen20.png/revision/latest?cb=20170811230403',
		},
		{
			level: 39,
			damagePerSecond: 347,
			damagePerAttack: 260.25,
			hitpoints: 1278,
			healthRecovery: 220,
			regenTime: 24,
			researchCost: 63000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 3,
			townHallLevelRequired: 10,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/a/a6/Archer_Queen20.png/revision/latest?cb=20170811230403',
		},
		{
			level: 40,
			damagePerSecond: 356,
			damagePerAttack: 267,
			hitpoints: 1304,
			healthRecovery: 235,
			regenTime: 26,
			researchCost: 65000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 4,
			townHallLevelRequired: 10,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/a/a6/Archer_Queen20.png/revision/latest?cb=20170811230403',
		},
		{
			level: 41,
			damagePerSecond: 365,
			damagePerAttack: 273.75,
			hitpoints: 1331,
			healthRecovery: 235,
			regenTime: 26,
			researchCost: 68000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 4,
			townHallLevelRequired: 11,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 42,
			damagePerSecond: 374,
			damagePerAttack: 280.5,
			hitpoints: 1359,
			healthRecovery: 235,
			regenTime: 26,
			researchCost: 72000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 4,
			townHallLevelRequired: 11,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 43,
			damagePerSecond: 383,
			damagePerAttack: 287.25,
			hitpoints: 1388,
			healthRecovery: 235,
			regenTime: 26,
			researchCost: 75000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 4,
			townHallLevelRequired: 11,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 44,
			damagePerSecond: 393,
			damagePerAttack: 294.75,
			hitpoints: 1417,
			healthRecovery: 235,
			regenTime: 26,
			researchCost: 79000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 4,
			townHallLevelRequired: 11,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 45,
			damagePerSecond: 403,
			damagePerAttack: 302.25,
			hitpoints: 1447,
			healthRecovery: 250,
			regenTime: 28,
			researchCost: 82000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 5,
			townHallLevelRequired: 11,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 46,
			damagePerSecond: 413,
			damagePerAttack: 309.75,
			hitpoints: 1478,
			healthRecovery: 250,
			regenTime: 28,
			researchCost: 86000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 5,
			townHallLevelRequired: 11,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 47,
			damagePerSecond: 423,
			damagePerAttack: 317.25,
			hitpoints: 1508,
			healthRecovery: 250,
			regenTime: 28,
			researchCost: 89000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 5,
			townHallLevelRequired: 11,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 48,
			damagePerSecond: 434,
			damagePerAttack: 325.5,
			hitpoints: 1540,
			healthRecovery: 250,
			regenTime: 28,
			researchCost: 93000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 5,
			townHallLevelRequired: 11,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 49,
			damagePerSecond: 445,
			damagePerAttack: 333.75,
			hitpoints: 1572,
			healthRecovery: 250,
			regenTime: 28,
			researchCost: 98000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 5,
			townHallLevelRequired: 11,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 50,
			damagePerSecond: 456,
			damagePerAttack: 342,
			hitpoints: 1606,
			healthRecovery: 265,
			regenTime: 30,
			researchCost: 103000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 5,
			townHallLevelRequired: 11,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 51,
			damagePerSecond: 465,
			damagePerAttack: 348.75,
			hitpoints: 1646,
			healthRecovery: 265,
			regenTime: 30,
			researchCost: 108000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 5,
			townHallLevelRequired: 12,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 52,
			damagePerSecond: 474,
			damagePerAttack: 355.5,
			hitpoints: 1688,
			healthRecovery: 265,
			regenTime: 30,
			researchCost: 113000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 5,
			townHallLevelRequired: 12,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 53,
			damagePerSecond: 485,
			damagePerAttack: 363.75,
			hitpoints: 1730,
			healthRecovery: 265,
			regenTime: 30,
			researchCost: 118000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 5,
			townHallLevelRequired: 12,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 54,
			damagePerSecond: 495,
			damagePerAttack: 371.25,
			hitpoints: 1774,
			healthRecovery: 265,
			regenTime: 30,
			researchCost: 123000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 5,
			townHallLevelRequired: 12,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 55,
			damagePerSecond: 505,
			damagePerAttack: 378.75,
			hitpoints: 1819,
			healthRecovery: 280,
			regenTime: 32,
			researchCost: 128000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 5,
			townHallLevelRequired: 12,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 56,
			damagePerSecond: 515,
			damagePerAttack: 386.25,
			hitpoints: 1865,
			healthRecovery: 280,
			regenTime: 32,
			researchCost: 133000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 18,
			researchTimeDay: 5,
			townHallLevelRequired: 12,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 57,
			damagePerSecond: 526,
			damagePerAttack: 394.5,
			hitpoints: 1912,
			healthRecovery: 280,
			regenTime: 32,
			researchCost: 138000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 18,
			researchTimeDay: 5,
			townHallLevelRequired: 12,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 58,
			damagePerSecond: 537,
			damagePerAttack: 402.75,
			hitpoints: 1960,
			healthRecovery: 280,
			regenTime: 32,
			researchCost: 143000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 18,
			researchTimeDay: 5,
			townHallLevelRequired: 12,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 59,
			damagePerSecond: 548,
			damagePerAttack: 411,
			hitpoints: 2010,
			healthRecovery: 280,
			regenTime: 32,
			researchCost: 148000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 18,
			researchTimeDay: 5,
			townHallLevelRequired: 12,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 60,
			damagePerSecond: 559,
			damagePerAttack: 419.25,
			hitpoints: 2060,
			healthRecovery: 295,
			regenTime: 34,
			researchCost: 153000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 18,
			researchTimeDay: 5,
			townHallLevelRequired: 12,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 61,
			damagePerSecond: 570,
			damagePerAttack: 427.5,
			hitpoints: 2111,
			healthRecovery: 295,
			regenTime: 34,
			researchCost: 158000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 6,
			townHallLevelRequired: 12,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 62,
			damagePerSecond: 581,
			damagePerAttack: 435.75,
			hitpoints: 2164,
			healthRecovery: 295,
			regenTime: 34,
			researchCost: 163000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 6,
			townHallLevelRequired: 12,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 63,
			damagePerSecond: 593,
			damagePerAttack: 444.75,
			hitpoints: 2218,
			healthRecovery: 295,
			regenTime: 34,
			researchCost: 168000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 6,
			townHallLevelRequired: 12,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 64,
			damagePerSecond: 605,
			damagePerAttack: 453.75,
			hitpoints: 2274,
			healthRecovery: 295,
			regenTime: 34,
			researchCost: 173000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 6,
			townHallLevelRequired: 12,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 65,
			damagePerSecond: 617,
			damagePerAttack: 462.75,
			hitpoints: 2330,
			healthRecovery: 310,
			regenTime: 36,
			researchCost: 178000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 6,
			townHallLevelRequired: 12,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 66,
			damagePerSecond: 628,
			damagePerAttack: 471,
			hitpoints: 2384,
			healthRecovery: 310,
			regenTime: 36,
			researchCost: 183000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 6,
			townHallLevelRequired: 13,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 67,
			damagePerSecond: 638,
			damagePerAttack: 478.5,
			hitpoints: 2432,
			healthRecovery: 310,
			regenTime: 36,
			researchCost: 188000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 6,
			townHallLevelRequired: 13,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 68,
			damagePerSecond: 648,
			damagePerAttack: 486,
			hitpoints: 2476,
			healthRecovery: 310,
			regenTime: 36,
			researchCost: 193000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 6,
			townHallLevelRequired: 13,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 69,
			damagePerSecond: 656,
			damagePerAttack: 492,
			hitpoints: 2516,
			healthRecovery: 310,
			regenTime: 36,
			researchCost: 198000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 6,
			townHallLevelRequired: 13,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 70,
			damagePerSecond: 664,
			damagePerAttack: 498,
			hitpoints: 2552,
			healthRecovery: 325,
			regenTime: 38,
			researchCost: 203000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 6,
			townHallLevelRequired: 13,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 71,
			damagePerSecond: 671,
			damagePerAttack: 503.25,
			hitpoints: 2584,
			healthRecovery: 325,
			regenTime: 38,
			researchCost: 208000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 7,
			townHallLevelRequired: 13,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 72,
			damagePerSecond: 677,
			damagePerAttack: 507.75,
			hitpoints: 2616,
			healthRecovery: 325,
			regenTime: 38,
			researchCost: 214000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 7,
			townHallLevelRequired: 13,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 73,
			damagePerSecond: 682,
			damagePerAttack: 511.5,
			hitpoints: 2648,
			healthRecovery: 325,
			regenTime: 38,
			researchCost: 221000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 7,
			townHallLevelRequired: 13,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 74,
			damagePerSecond: 687,
			damagePerAttack: 515.25,
			hitpoints: 2680,
			healthRecovery: 325,
			regenTime: 38,
			researchCost: 229000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 7,
			townHallLevelRequired: 13,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 75,
			damagePerSecond: 692,
			damagePerAttack: 519,
			hitpoints: 2712,
			healthRecovery: 340,
			regenTime: 40,
			researchCost: 234000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 7,
			townHallLevelRequired: 13,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 76,
			damagePerSecond: 697,
			damagePerAttack: 522.75,
			hitpoints: 2740,
			healthRecovery: 340,
			regenTime: 40,
			researchCost: 239000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 7,
			townHallLevelRequired: 14,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 77,
			damagePerSecond: 701,
			damagePerAttack: 525.75,
			hitpoints: 2768,
			healthRecovery: 340,
			regenTime: 40,
			researchCost: 244000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 7,
			townHallLevelRequired: 14,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 78,
			damagePerSecond: 706,
			damagePerAttack: 529.5,
			hitpoints: 2796,
			healthRecovery: 340,
			regenTime: 40,
			researchCost: 249000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 7,
			townHallLevelRequired: 14,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 79,
			damagePerSecond: 710,
			damagePerAttack: 532.5,
			hitpoints: 2824,
			healthRecovery: 340,
			regenTime: 40,
			researchCost: 254000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 7,
			townHallLevelRequired: 14,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 80,
			damagePerSecond: 714,
			damagePerAttack: 535.5,
			hitpoints: 2852,
			healthRecovery: 355,
			regenTime: 42,
			researchCost: 259000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 7,
			townHallLevelRequired: 14,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 81,
			damagePerSecond: 717,
			damagePerAttack: 537.75,
			hitpoints: 2880,
			healthRecovery: 355,
			regenTime: 42,
			researchCost: 264000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			townHallLevelRequired: 15,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 82,
			damagePerSecond: 721,
			damagePerAttack: 540.75,
			hitpoints: 2904,
			healthRecovery: 355,
			regenTime: 42,
			researchCost: 268000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			townHallLevelRequired: 15,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 83,
			damagePerSecond: 724,
			damagePerAttack: 543,
			hitpoints: 2928,
			healthRecovery: 355,
			regenTime: 42,
			researchCost: 272000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			townHallLevelRequired: 15,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 84,
			damagePerSecond: 728,
			damagePerAttack: 546,
			hitpoints: 2952,
			healthRecovery: 355,
			regenTime: 42,
			researchCost: 276000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			townHallLevelRequired: 15,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 85,
			damagePerSecond: 731,
			damagePerAttack: 548.25,
			hitpoints: 2976,
			healthRecovery: 370,
			regenTime: 44,
			researchCost: 280000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			townHallLevelRequired: 15,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 86,
			damagePerSecond: 734,
			damagePerAttack: 550.5,
			hitpoints: 3000,
			healthRecovery: 370,
			regenTime: 44,
			researchCost: 282000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			townHallLevelRequired: 15,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 87,
			damagePerSecond: 738,
			damagePerAttack: 553.5,
			hitpoints: 3024,
			healthRecovery: 370,
			regenTime: 44,
			researchCost: 284000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			townHallLevelRequired: 15,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 88,
			damagePerSecond: 741,
			damagePerAttack: 555.75,
			hitpoints: 3048,
			healthRecovery: 370,
			regenTime: 44,
			researchCost: 286000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			townHallLevelRequired: 15,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 89,
			damagePerSecond: 745,
			damagePerAttack: 558.75,
			hitpoints: 3072,
			healthRecovery: 370,
			regenTime: 44,
			researchCost: 288000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			townHallLevelRequired: 15,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 90,
			damagePerSecond: 748,
			damagePerAttack: 561,
			hitpoints: 3096,
			healthRecovery: 385,
			regenTime: 46,
			researchCost: 290000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			townHallLevelRequired: 15,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 91,
			damagePerSecond: 751,
			damagePerAttack: 563.25,
			hitpoints: 3120,
			healthRecovery: 385,
			regenTime: 46,
			researchCost: 300000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			townHallLevelRequired: 16,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 92,
			damagePerSecond: 755,
			damagePerAttack: 566.25,
			hitpoints: 3144,
			healthRecovery: 385,
			regenTime: 46,
			researchCost: 310000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			townHallLevelRequired: 16,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 93,
			damagePerSecond: 758,
			damagePerAttack: 568.5,
			hitpoints: 3168,
			healthRecovery: 385,
			regenTime: 46,
			researchCost: 320000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			townHallLevelRequired: 16,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 94,
			damagePerSecond: 762,
			damagePerAttack: 571.5,
			hitpoints: 3192,
			healthRecovery: 385,
			regenTime: 46,
			researchCost: 330000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			townHallLevelRequired: 16,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
		{
			level: 95,
			damagePerSecond: 765,
			damagePerAttack: 573.75,
			hitpoints: 3216,
			healthRecovery: 400,
			regenTime: 48,
			researchCost: 340000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			townHallLevelRequired: 16,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6a/Archer_Queen41.png/revision/latest?cb=20170811230426',
		},
	],
	getLevel: (level: number) => getLevel(troop.levels, level, 'level'),
	getTownHallLevel: (level: number) => getHallLevel(troop.townHallDetails, level, 'townHallLevel'),
}

export default troop
