import * as Constants from '@/constants'
import Army from '@IHomeVillage/troops/army.interface'
import { getLevel, getHallLevel } from '@Utils/buildings.utility'

const troop: Army = {
	name: 'Barbarian King',
	description:
		'Biggest and bravest of all barbarians, this colossal menace soaks up huge amounts of damage and smashes anything in his path with his sword. He guards his territory fiercely when defending.',
	maxLevel: 95,
	mode: {
		attackType: Constants.melee,
		unitTypeTarget: Constants.ground,
		preferredTarget: Constants.none,
		minRange: 0,
		maxRange: 1,
		attackSpeed: 1.2,
		movementSpeed: 16,
		searchRadius: 9,
	},
	townHallDetails: [
		{ townHallLevel: 1, availableCount: 0, maxLevel: 0 },
		{ townHallLevel: 2, availableCount: 0, maxLevel: 0 },
		{ townHallLevel: 3, availableCount: 0, maxLevel: 0 },
		{ townHallLevel: 4, availableCount: 0, maxLevel: 0 },
		{ townHallLevel: 5, availableCount: 0, maxLevel: 0 },
		{ townHallLevel: 6, availableCount: 0, maxLevel: 0 },
		{ townHallLevel: 7, availableCount: 1, maxLevel: 10 },
		{ townHallLevel: 8, availableCount: 1, maxLevel: 20 },
		{ townHallLevel: 9, availableCount: 1, maxLevel: 30 },
		{ townHallLevel: 10, availableCount: 1, maxLevel: 40 },
		{ townHallLevel: 11, availableCount: 1, maxLevel: 50 },
		{ townHallLevel: 12, availableCount: 1, maxLevel: 65 },
		{ townHallLevel: 13, availableCount: 1, maxLevel: 75 },
		{ townHallLevel: 14, availableCount: 1, maxLevel: 80 },
		{ townHallLevel: 15, availableCount: 1, maxLevel: 90 },
		{ townHallLevel: 16, availableCount: 1, maxLevel: 95 },
	],
	levels: [
		{
			level: 1,
			damagePerSecond: 102,
			damagePerAttack: 122.4,
			hitpoints: 1445,
			healthRecovery: 200,
			regenTime: 10,
			researchCost: 5000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 0,
			townHallLevelRequired: 7,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/f/fd/Barbarian_King1.png/revision/latest?cb=20170812112657',
		},
		{
			level: 2,
			damagePerSecond: 104,
			damagePerAttack: 124.8,
			hitpoints: 1481,
			healthRecovery: 200,
			regenTime: 10,
			researchCost: 5000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 4,
			researchTimeDay: 0,
			townHallLevelRequired: 7,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/f/fd/Barbarian_King1.png/revision/latest?cb=20170812112657',
		},
		{
			level: 3,
			damagePerSecond: 105,
			damagePerAttack: 126,
			hitpoints: 1518,
			healthRecovery: 200,
			regenTime: 10,
			researchCost: 6000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 6,
			researchTimeDay: 0,
			townHallLevelRequired: 7,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/f/fd/Barbarian_King1.png/revision/latest?cb=20170812112657',
		},
		{
			level: 4,
			damagePerSecond: 108,
			damagePerAttack: 129.6,
			hitpoints: 1556,
			healthRecovery: 200,
			regenTime: 10,
			researchCost: 7000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 8,
			researchTimeDay: 0,
			townHallLevelRequired: 7,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/f/fd/Barbarian_King1.png/revision/latest?cb=20170812112657',
		},
		{
			level: 5,
			damagePerSecond: 110,
			damagePerAttack: 132,
			hitpoints: 1595,
			healthRecovery: 250,
			regenTime: 12,
			researchCost: 8000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 10,
			researchTimeDay: 0,
			townHallLevelRequired: 7,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/f/fd/Barbarian_King1.png/revision/latest?cb=20170812112657',
		},
		{
			level: 6,
			damagePerSecond: 112,
			damagePerAttack: 134.4,
			hitpoints: 1635,
			healthRecovery: 250,
			regenTime: 12,
			researchCost: 9000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 0,
			townHallLevelRequired: 7,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/f/fd/Barbarian_King1.png/revision/latest?cb=20170812112657',
		},
		{
			level: 7,
			damagePerSecond: 115,
			damagePerAttack: 138,
			hitpoints: 1675,
			healthRecovery: 250,
			regenTime: 12,
			researchCost: 10000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 14,
			researchTimeDay: 0,
			townHallLevelRequired: 7,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/f/fd/Barbarian_King1.png/revision/latest?cb=20170812112657',
		},
		{
			level: 8,
			damagePerSecond: 116,
			damagePerAttack: 139.2,
			hitpoints: 1717,
			healthRecovery: 250,
			regenTime: 12,
			researchCost: 11000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 16,
			researchTimeDay: 0,
			townHallLevelRequired: 7,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/f/fd/Barbarian_King1.png/revision/latest?cb=20170812112657',
		},
		{
			level: 9,
			damagePerSecond: 119,
			damagePerAttack: 142.8,
			hitpoints: 1760,
			healthRecovery: 250,
			regenTime: 12,
			researchCost: 12000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 18,
			researchTimeDay: 0,
			townHallLevelRequired: 7,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/f/fd/Barbarian_King1.png/revision/latest?cb=20170812112657',
		},
		{
			level: 10,
			damagePerSecond: 122,
			damagePerAttack: 146.4,
			hitpoints: 1805,
			healthRecovery: 310,
			regenTime: 14,
			researchCost: 13000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 20,
			researchTimeDay: 0,
			townHallLevelRequired: 7,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/b/b3/Barbarian_King10.png/revision/latest?cb=20170812112715',
		},
		{
			level: 11,
			damagePerSecond: 124,
			damagePerAttack: 148.8,
			hitpoints: 1850,
			healthRecovery: 310,
			regenTime: 14,
			researchCost: 14000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 22,
			researchTimeDay: 0,
			townHallLevelRequired: 8,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/b/b3/Barbarian_King10.png/revision/latest?cb=20170812112715',
		},
		{
			level: 12,
			damagePerSecond: 127,
			damagePerAttack: 152.4,
			hitpoints: 1896,
			healthRecovery: 310,
			regenTime: 14,
			researchCost: 15000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 1,
			townHallLevelRequired: 8,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/b/b3/Barbarian_King10.png/revision/latest?cb=20170812112715',
		},
		{
			level: 13,
			damagePerSecond: 129,
			damagePerAttack: 154.8,
			hitpoints: 1943,
			healthRecovery: 310,
			regenTime: 14,
			researchCost: 16000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 1,
			townHallLevelRequired: 8,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/b/b3/Barbarian_King10.png/revision/latest?cb=20170812112715',
		},
		{
			level: 14,
			damagePerSecond: 132,
			damagePerAttack: 158.4,
			hitpoints: 1992,
			healthRecovery: 310,
			regenTime: 14,
			researchCost: 17000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 1,
			townHallLevelRequired: 8,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/b/b3/Barbarian_King10.png/revision/latest?cb=20170812112715',
		},
		{
			level: 15,
			damagePerSecond: 134,
			damagePerAttack: 160.8,
			hitpoints: 2042,
			healthRecovery: 375,
			regenTime: 16,
			researchCost: 18500,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 1,
			townHallLevelRequired: 8,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/b/b3/Barbarian_King10.png/revision/latest?cb=20170812112715',
		},
		{
			level: 16,
			damagePerSecond: 137,
			damagePerAttack: 164.4,
			hitpoints: 2093,
			healthRecovery: 375,
			regenTime: 16,
			researchCost: 20000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 1,
			townHallLevelRequired: 8,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/b/b3/Barbarian_King10.png/revision/latest?cb=20170812112715',
		},
		{
			level: 17,
			damagePerSecond: 139,
			damagePerAttack: 166.8,
			hitpoints: 2145,
			healthRecovery: 375,
			regenTime: 16,
			researchCost: 21500,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 1,
			townHallLevelRequired: 8,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/b/b3/Barbarian_King10.png/revision/latest?cb=20170812112715',
		},
		{
			level: 18,
			damagePerSecond: 143,
			damagePerAttack: 171.6,
			hitpoints: 2198,
			healthRecovery: 375,
			regenTime: 16,
			researchCost: 23000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 1,
			townHallLevelRequired: 8,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/b/b3/Barbarian_King10.png/revision/latest?cb=20170812112715',
		},
		{
			level: 19,
			damagePerSecond: 145,
			damagePerAttack: 174,
			hitpoints: 2253,
			healthRecovery: 375,
			regenTime: 16,
			researchCost: 24500,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 1,
			townHallLevelRequired: 8,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/b/b3/Barbarian_King10.png/revision/latest?cb=20170812112715',
		},
		{
			level: 20,
			damagePerSecond: 148,
			damagePerAttack: 177.6,
			hitpoints: 2309,
			healthRecovery: 450,
			regenTime: 18,
			researchCost: 26000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 2,
			townHallLevelRequired: 8,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/f/fa/Barbarian_King20.png/revision/latest?cb=20170812112734',
		},
		{
			level: 21,
			damagePerSecond: 151,
			damagePerAttack: 181.2,
			hitpoints: 2367,
			healthRecovery: 450,
			regenTime: 18,
			researchCost: 28000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 2,
			townHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/f/fa/Barbarian_King20.png/revision/latest?cb=20170812112734',
		},
		{
			level: 22,
			damagePerSecond: 154,
			damagePerAttack: 184.8,
			hitpoints: 2427,
			healthRecovery: 450,
			regenTime: 18,
			researchCost: 29000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 2,
			townHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/f/fa/Barbarian_King20.png/revision/latest?cb=20170812112734',
		},
		{
			level: 23,
			damagePerSecond: 157,
			damagePerAttack: 188.4,
			hitpoints: 2487,
			healthRecovery: 450,
			regenTime: 18,
			researchCost: 31000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 2,
			townHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/f/fa/Barbarian_King20.png/revision/latest?cb=20170812112734',
		},
		{
			level: 24,
			damagePerSecond: 161,
			damagePerAttack: 193.2,
			hitpoints: 2549,
			healthRecovery: 450,
			regenTime: 18,
			researchCost: 32000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 2,
			townHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/f/fa/Barbarian_King20.png/revision/latest?cb=20170812112734',
		},
		{
			level: 25,
			damagePerSecond: 164,
			damagePerAttack: 196.8,
			hitpoints: 2613,
			healthRecovery: 525,
			regenTime: 20,
			researchCost: 34000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 2,
			townHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/f/fa/Barbarian_King20.png/revision/latest?cb=20170812112734',
		},
		{
			level: 26,
			damagePerSecond: 167,
			damagePerAttack: 200.4,
			hitpoints: 2678,
			healthRecovery: 525,
			regenTime: 20,
			researchCost: 35000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 2,
			townHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/f/fa/Barbarian_King20.png/revision/latest?cb=20170812112734',
		},
		{
			level: 27,
			damagePerSecond: 170,
			damagePerAttack: 204,
			hitpoints: 2746,
			healthRecovery: 525,
			regenTime: 20,
			researchCost: 37000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 2,
			townHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/f/fa/Barbarian_King20.png/revision/latest?cb=20170812112734',
		},
		{
			level: 28,
			damagePerSecond: 173,
			damagePerAttack: 207.6,
			hitpoints: 2814,
			healthRecovery: 525,
			regenTime: 20,
			researchCost: 38000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 2,
			townHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/f/fa/Barbarian_King20.png/revision/latest?cb=20170812112734',
		},
		{
			level: 29,
			damagePerSecond: 177,
			damagePerAttack: 212.4,
			hitpoints: 2885,
			healthRecovery: 525,
			regenTime: 20,
			researchCost: 40000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 2,
			townHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/f/fa/Barbarian_King20.png/revision/latest?cb=20170812112734',
		},
		{
			level: 30,
			damagePerSecond: 181,
			damagePerAttack: 217.2,
			hitpoints: 2956,
			healthRecovery: 625,
			regenTime: 22,
			researchCost: 41000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 3,
			townHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/f/fa/Barbarian_King20.png/revision/latest?cb=20170812112734',
		},
		{
			level: 31,
			damagePerSecond: 184,
			damagePerAttack: 220.8,
			hitpoints: 3030,
			healthRecovery: 625,
			regenTime: 22,
			researchCost: 43000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 3,
			townHallLevelRequired: 10,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/f/fa/Barbarian_King20.png/revision/latest?cb=20170812112734',
		},
		{
			level: 32,
			damagePerSecond: 188,
			damagePerAttack: 225.6,
			hitpoints: 3107,
			healthRecovery: 625,
			regenTime: 22,
			researchCost: 44000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 3,
			townHallLevelRequired: 10,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/f/fa/Barbarian_King20.png/revision/latest?cb=20170812112734',
		},
		{
			level: 33,
			damagePerSecond: 192,
			damagePerAttack: 230.4,
			hitpoints: 3184,
			healthRecovery: 625,
			regenTime: 22,
			researchCost: 46000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 3,
			townHallLevelRequired: 10,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/f/fa/Barbarian_King20.png/revision/latest?cb=20170812112734',
		},
		{
			level: 34,
			damagePerSecond: 196,
			damagePerAttack: 235.2,
			hitpoints: 3264,
			healthRecovery: 625,
			regenTime: 22,
			researchCost: 47000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 3,
			townHallLevelRequired: 10,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/f/fa/Barbarian_King20.png/revision/latest?cb=20170812112734',
		},
		{
			level: 35,
			damagePerSecond: 200,
			damagePerAttack: 240,
			hitpoints: 3346,
			healthRecovery: 725,
			regenTime: 24,
			researchCost: 49000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 3,
			townHallLevelRequired: 10,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/f/fa/Barbarian_King20.png/revision/latest?cb=20170812112734',
		},
		{
			level: 36,
			damagePerSecond: 203,
			damagePerAttack: 243.6,
			hitpoints: 3429,
			healthRecovery: 725,
			regenTime: 24,
			researchCost: 50000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 3,
			townHallLevelRequired: 10,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/f/fa/Barbarian_King20.png/revision/latest?cb=20170812112734',
		},
		{
			level: 37,
			damagePerSecond: 207,
			damagePerAttack: 248.4,
			hitpoints: 3515,
			healthRecovery: 725,
			regenTime: 24,
			researchCost: 52000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 3,
			townHallLevelRequired: 10,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/f/fa/Barbarian_King20.png/revision/latest?cb=20170812112734',
		},
		{
			level: 38,
			damagePerSecond: 212,
			damagePerAttack: 254.4,
			hitpoints: 3602,
			healthRecovery: 725,
			regenTime: 24,
			researchCost: 53000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 3,
			townHallLevelRequired: 10,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/f/fa/Barbarian_King20.png/revision/latest?cb=20170812112734',
		},
		{
			level: 39,
			damagePerSecond: 216,
			damagePerAttack: 259.2,
			hitpoints: 3692,
			healthRecovery: 725,
			regenTime: 24,
			researchCost: 55000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 3,
			townHallLevelRequired: 10,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/f/fa/Barbarian_King20.png/revision/latest?cb=20170812112734',
		},
		{
			level: 40,
			damagePerSecond: 220,
			damagePerAttack: 264,
			hitpoints: 3785,
			healthRecovery: 850,
			regenTime: 26,
			researchCost: 56000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 4,
			townHallLevelRequired: 10,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/f/fa/Barbarian_King20.png/revision/latest?cb=20170812112734',
		},
		{
			level: 41,
			damagePerSecond: 234,
			damagePerAttack: 280.8,
			hitpoints: 3879,
			healthRecovery: 850,
			regenTime: 26,
			researchCost: 60000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 4,
			townHallLevelRequired: 11,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 42,
			damagePerSecond: 239,
			damagePerAttack: 286.8,
			hitpoints: 3976,
			healthRecovery: 850,
			regenTime: 26,
			researchCost: 64000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 4,
			townHallLevelRequired: 11,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 43,
			damagePerSecond: 244,
			damagePerAttack: 292.8,
			hitpoints: 4076,
			healthRecovery: 850,
			regenTime: 26,
			researchCost: 68000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 4,
			townHallLevelRequired: 11,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 44,
			damagePerSecond: 249,
			damagePerAttack: 298.8,
			hitpoints: 4178,
			healthRecovery: 850,
			regenTime: 26,
			researchCost: 72000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 4,
			townHallLevelRequired: 11,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 45,
			damagePerSecond: 254,
			damagePerAttack: 304.8,
			hitpoints: 4282,
			healthRecovery: 980,
			regenTime: 28,
			researchCost: 76000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 5,
			townHallLevelRequired: 11,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 46,
			damagePerSecond: 259,
			damagePerAttack: 310.8,
			hitpoints: 4389,
			healthRecovery: 980,
			regenTime: 28,
			researchCost: 80000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 5,
			townHallLevelRequired: 11,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 47,
			damagePerSecond: 265,
			damagePerAttack: 318,
			hitpoints: 4499,
			healthRecovery: 980,
			regenTime: 28,
			researchCost: 84000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 5,
			townHallLevelRequired: 11,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 48,
			damagePerSecond: 270,
			damagePerAttack: 324,
			hitpoints: 4611,
			healthRecovery: 980,
			regenTime: 28,
			researchCost: 88000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 5,
			townHallLevelRequired: 11,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 49,
			damagePerSecond: 276,
			damagePerAttack: 331.2,
			hitpoints: 4727,
			healthRecovery: 980,
			regenTime: 28,
			researchCost: 92000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 5,
			townHallLevelRequired: 11,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 50,
			damagePerSecond: 282,
			damagePerAttack: 338.4,
			hitpoints: 4845,
			healthRecovery: 1125,
			regenTime: 30,
			researchCost: 96000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 5,
			townHallLevelRequired: 11,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 51,
			damagePerSecond: 288,
			damagePerAttack: 345.6,
			hitpoints: 4967,
			healthRecovery: 1125,
			regenTime: 30,
			researchCost: 100000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 5,
			townHallLevelRequired: 12,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 52,
			damagePerSecond: 294,
			damagePerAttack: 352.8,
			hitpoints: 5092,
			healthRecovery: 1125,
			regenTime: 30,
			researchCost: 105000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 5,
			townHallLevelRequired: 12,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 53,
			damagePerSecond: 300,
			damagePerAttack: 360,
			hitpoints: 5219,
			healthRecovery: 1125,
			regenTime: 30,
			researchCost: 110000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 5,
			townHallLevelRequired: 12,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 54,
			damagePerSecond: 307,
			damagePerAttack: 368.4,
			hitpoints: 5350,
			healthRecovery: 1125,
			regenTime: 30,
			researchCost: 115000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 5,
			townHallLevelRequired: 12,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 55,
			damagePerSecond: 314,
			damagePerAttack: 376.8,
			hitpoints: 5484,
			healthRecovery: 1300,
			regenTime: 32,
			researchCost: 120000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 5,
			townHallLevelRequired: 12,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 56,
			damagePerSecond: 320,
			damagePerAttack: 384,
			hitpoints: 5622,
			healthRecovery: 1300,
			regenTime: 32,
			researchCost: 125000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 18,
			researchTimeDay: 5,
			townHallLevelRequired: 12,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 57,
			damagePerSecond: 327,
			damagePerAttack: 392.4,
			hitpoints: 5763,
			healthRecovery: 1300,
			regenTime: 32,
			researchCost: 130000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 18,
			researchTimeDay: 5,
			townHallLevelRequired: 12,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 58,
			damagePerSecond: 334,
			damagePerAttack: 400.8,
			hitpoints: 5908,
			healthRecovery: 1300,
			regenTime: 32,
			researchCost: 135000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 18,
			researchTimeDay: 5,
			townHallLevelRequired: 12,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 59,
			damagePerSecond: 341,
			damagePerAttack: 409.2,
			hitpoints: 6055,
			healthRecovery: 1300,
			regenTime: 32,
			researchCost: 140000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 18,
			researchTimeDay: 5,
			townHallLevelRequired: 12,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 60,
			damagePerSecond: 349,
			damagePerAttack: 418.8,
			hitpoints: 6208,
			healthRecovery: 1490,
			regenTime: 34,
			researchCost: 145000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 18,
			researchTimeDay: 5,
			townHallLevelRequired: 12,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 61,
			damagePerSecond: 355,
			damagePerAttack: 426,
			hitpoints: 6363,
			healthRecovery: 1490,
			regenTime: 34,
			researchCost: 150000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 6,
			townHallLevelRequired: 12,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 62,
			damagePerSecond: 362,
			damagePerAttack: 434.4,
			hitpoints: 6522,
			healthRecovery: 1490,
			regenTime: 34,
			researchCost: 155000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 6,
			townHallLevelRequired: 12,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 63,
			damagePerSecond: 370,
			damagePerAttack: 444,
			hitpoints: 6685,
			healthRecovery: 1490,
			regenTime: 34,
			researchCost: 160000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 6,
			townHallLevelRequired: 12,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 64,
			damagePerSecond: 377,
			damagePerAttack: 452.4,
			hitpoints: 6853,
			healthRecovery: 1490,
			regenTime: 34,
			researchCost: 165000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 6,
			townHallLevelRequired: 12,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 65,
			damagePerSecond: 385,
			damagePerAttack: 462,
			hitpoints: 7024,
			healthRecovery: 1700,
			regenTime: 36,
			researchCost: 170000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 6,
			townHallLevelRequired: 12,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 66,
			damagePerSecond: 393,
			damagePerAttack: 471.6,
			hitpoints: 7200,
			healthRecovery: 1700,
			regenTime: 36,
			researchCost: 175000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 6,
			townHallLevelRequired: 13,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 67,
			damagePerSecond: 400,
			damagePerAttack: 480,
			hitpoints: 7378,
			healthRecovery: 1700,
			regenTime: 36,
			researchCost: 180000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 6,
			townHallLevelRequired: 13,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 68,
			damagePerSecond: 408,
			damagePerAttack: 489.6,
			hitpoints: 7557,
			healthRecovery: 1700,
			regenTime: 36,
			researchCost: 185000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 6,
			townHallLevelRequired: 13,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 69,
			damagePerSecond: 417,
			damagePerAttack: 500.4,
			hitpoints: 7735,
			healthRecovery: 1700,
			regenTime: 36,
			researchCost: 190000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 6,
			townHallLevelRequired: 13,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 70,
			damagePerSecond: 425,
			damagePerAttack: 510,
			hitpoints: 7905,
			healthRecovery: 1925,
			regenTime: 38,
			researchCost: 195000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 6,
			townHallLevelRequired: 13,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 71,
			damagePerSecond: 434,
			damagePerAttack: 520.8,
			hitpoints: 8075,
			healthRecovery: 1925,
			regenTime: 38,
			researchCost: 200000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 7,
			townHallLevelRequired: 13,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 72,
			damagePerSecond: 442,
			damagePerAttack: 530.4,
			hitpoints: 8245,
			healthRecovery: 1925,
			regenTime: 38,
			researchCost: 205000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 7,
			townHallLevelRequired: 13,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 73,
			damagePerSecond: 451,
			damagePerAttack: 541.2,
			hitpoints: 8415,
			healthRecovery: 1925,
			regenTime: 38,
			researchCost: 210000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 7,
			townHallLevelRequired: 13,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 74,
			damagePerSecond: 459,
			damagePerAttack: 550.8,
			hitpoints: 8585,
			healthRecovery: 1925,
			regenTime: 38,
			researchCost: 215000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 7,
			townHallLevelRequired: 13,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 75,
			damagePerSecond: 468,
			damagePerAttack: 561.6,
			hitpoints: 8755,
			healthRecovery: 2150,
			regenTime: 40,
			researchCost: 220000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 7,
			townHallLevelRequired: 13,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 76,
			damagePerSecond: 475,
			damagePerAttack: 570,
			hitpoints: 8917,
			healthRecovery: 2150,
			regenTime: 40,
			researchCost: 225000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 7,
			townHallLevelRequired: 14,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 77,
			damagePerSecond: 483,
			damagePerAttack: 579.6,
			hitpoints: 9078,
			healthRecovery: 2150,
			regenTime: 40,
			researchCost: 230000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 7,
			townHallLevelRequired: 14,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 78,
			damagePerSecond: 490,
			damagePerAttack: 588,
			hitpoints: 9240,
			healthRecovery: 2150,
			regenTime: 40,
			researchCost: 235000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 7,
			townHallLevelRequired: 14,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 79,
			damagePerSecond: 498,
			damagePerAttack: 597.6,
			hitpoints: 9401,
			healthRecovery: 2150,
			regenTime: 40,
			researchCost: 240000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 7,
			townHallLevelRequired: 14,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 80,
			damagePerSecond: 506,
			damagePerAttack: 607.2,
			hitpoints: 9563,
			healthRecovery: 2350,
			regenTime: 42,
			researchCost: 245000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 7,
			townHallLevelRequired: 14,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 81,
			damagePerSecond: 513,
			damagePerAttack: 615.6,
			hitpoints: 9690,
			healthRecovery: 2350,
			regenTime: 42,
			researchCost: 250000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			townHallLevelRequired: 15,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 82,
			damagePerSecond: 519,
			damagePerAttack: 622.8,
			hitpoints: 9818,
			healthRecovery: 2350,
			regenTime: 42,
			researchCost: 255000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			townHallLevelRequired: 15,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 83,
			damagePerSecond: 526,
			damagePerAttack: 631.2,
			hitpoints: 9945,
			healthRecovery: 2350,
			regenTime: 42,
			researchCost: 260000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			townHallLevelRequired: 15,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 84,
			damagePerSecond: 533,
			damagePerAttack: 639.6,
			hitpoints: 10073,
			healthRecovery: 2350,
			regenTime: 42,
			researchCost: 265000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			townHallLevelRequired: 15,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 85,
			damagePerSecond: 540,
			damagePerAttack: 648,
			hitpoints: 10200,
			healthRecovery: 2500,
			regenTime: 44,
			researchCost: 270000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			townHallLevelRequired: 15,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 86,
			damagePerSecond: 547,
			damagePerAttack: 656.4,
			hitpoints: 10328,
			healthRecovery: 2500,
			regenTime: 44,
			researchCost: 275000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			townHallLevelRequired: 15,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 87,
			damagePerSecond: 553,
			damagePerAttack: 663.6,
			hitpoints: 10455,
			healthRecovery: 2500,
			regenTime: 44,
			researchCost: 278000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			townHallLevelRequired: 15,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 88,
			damagePerSecond: 560,
			damagePerAttack: 672,
			hitpoints: 10583,
			healthRecovery: 2500,
			regenTime: 44,
			researchCost: 280000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			townHallLevelRequired: 15,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 89,
			damagePerSecond: 567,
			damagePerAttack: 680.4,
			hitpoints: 10710,
			healthRecovery: 2500,
			regenTime: 44,
			researchCost: 282000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			townHallLevelRequired: 15,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 90,
			damagePerSecond: 574,
			damagePerAttack: 688.8,
			hitpoints: 10838,
			healthRecovery: 2650,
			regenTime: 46,
			researchCost: 285000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			townHallLevelRequired: 15,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 91,
			damagePerSecond: 581,
			damagePerAttack: 697.2,
			hitpoints: 10965,
			healthRecovery: 2650,
			regenTime: 46,
			researchCost: 290000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			townHallLevelRequired: 16,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 92,
			damagePerSecond: 587,
			damagePerAttack: 704.4,
			hitpoints: 11093,
			healthRecovery: 2650,
			regenTime: 46,
			researchCost: 300000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			townHallLevelRequired: 16,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 93,
			damagePerSecond: 594,
			damagePerAttack: 712.8,
			hitpoints: 11220,
			healthRecovery: 2650,
			regenTime: 46,
			researchCost: 310000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			townHallLevelRequired: 16,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 94,
			damagePerSecond: 601,
			damagePerAttack: 721.2,
			hitpoints: 11348,
			healthRecovery: 2650,
			regenTime: 46,
			researchCost: 320000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			townHallLevelRequired: 16,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
		{
			level: 95,
			damagePerSecond: 608,
			damagePerAttack: 729.6,
			hitpoints: 11475,
			healthRecovery: 2800,
			regenTime: 48,
			researchCost: 330000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			townHallLevelRequired: 16,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/17/Barbarian_King41.png/revision/latest?cb=20170812112753',
		},
	],
	getLevel: (level: number) => getLevel(troop.levels, level, 'level'),
	getTownHallLevel: (level: number) => getHallLevel(troop.townHallDetails, level, 'townHallLevel'),
}

export default troop
