import * as Constants from '@/constants'
import Army from '@IHomeVillage/troops/army.interface'
import { getLevel } from '@Utils/buildings.utility'

const troop: Army = {
	name: 'Archer',
	description:
		'These sharpshooters like to keep their distance on the battlefield and in life. Nothing makes them happier than single-mindedly taking down their target.',
	maxLevel: 12,
	housingSpace: 1,
	buildingLevelRequired: 2,
	buildingName: Constants.barracks,
	superTroopUnlocked: 'Super Archer',
	training: {
		barracksAvailableSec: 6,
		barracksAvailableMin: 0,
		barracksUpgradingSec: 12,
		barracksUpgradingMin: 0,
	},
	mode: {
		attackType: Constants.ranged,
		unitTypeTarget: Constants.groundAndAir,
		preferredTarget: Constants.none,
		minRange: 0,
		maxRange: 3.5,
		attackSpeed: 1,
		movementSpeed: 24,
	},
	levels: [
		{
			level: 1,
			damagePerSecond: 7,
			damagePerAttack: 7,
			hitpoints: 20,
			researchCost: 0,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 0,
			laboratoryLevelRequired: 0,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/e/ee/Archer1.png/revision/latest?cb=20171007104242',
		},
		{
			level: 2,
			damagePerSecond: 9,
			damagePerAttack: 9,
			hitpoints: 23,
			researchCost: 30000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 3,
			researchTimeDay: 0,
			laboratoryLevelRequired: 1,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/e/ee/Archer1.png/revision/latest?cb=20171007104242',
		},
		{
			level: 3,
			damagePerSecond: 12,
			damagePerAttack: 12,
			hitpoints: 28,
			researchCost: 80000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 6,
			researchTimeDay: 0,
			laboratoryLevelRequired: 3,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/f/f6/Archer3.png/revision/latest?cb=20171007104305',
		},
		{
			level: 4,
			damagePerSecond: 16,
			damagePerAttack: 16,
			hitpoints: 33,
			researchCost: 300000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 0,
			laboratoryLevelRequired: 5,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/f/f6/Archer3.png/revision/latest?cb=20171007104305',
		},
		{
			level: 5,
			damagePerSecond: 20,
			damagePerAttack: 20,
			hitpoints: 40,
			researchCost: 800000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 1,
			laboratoryLevelRequired: 6,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/8/8a/Archer5.png/revision/latest?cb=20171007104326',
		},
		{
			level: 6,
			damagePerSecond: 22,
			damagePerAttack: 22,
			hitpoints: 44,
			researchCost: 2000000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 1,
			laboratoryLevelRequired: 7,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/12/Archer6.png/revision/latest?cb=20171007104349',
		},
		{
			level: 7,
			damagePerSecond: 25,
			damagePerAttack: 25,
			hitpoints: 48,
			researchCost: 2500000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 2,
			laboratoryLevelRequired: 8,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/7/70/Archer7.png/revision/latest?cb=20171007104413',
		},
		{
			level: 8,
			damagePerSecond: 28,
			damagePerAttack: 28,
			hitpoints: 52,
			researchCost: 3200000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 2,
			laboratoryLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/d/d2/Archer8.png/revision/latest?cb=20180607154922',
		},
		{
			level: 9,
			damagePerSecond: 31,
			damagePerAttack: 31,
			hitpoints: 56,
			researchCost: 5600000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 3,
			laboratoryLevelRequired: 10,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/5/51/Archer9.png/revision/latest?cb=20201021075102',
		},
		{
			level: 10,
			damagePerSecond: 34,
			damagePerAttack: 34,
			hitpoints: 60,
			researchCost: 10200000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 6,
			laboratoryLevelRequired: 12,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/1a/Archer10.png/revision/latest?cb=20210413033118',
		},
		{
			level: 11,
			damagePerSecond: 37,
			damagePerAttack: 37,
			hitpoints: 64,
			researchCost: 16000000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 12,
			laboratoryLevelRequired: 13,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/9/98/Archer11.png/revision/latest?cb=20221123222519',
		},
		{
			level: 12,
			damagePerSecond: 40,
			damagePerAttack: 40,
			hitpoints: 68,
			researchCost: 18000000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 13,
			laboratoryLevelRequired: 14,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/63/Archer12.png/revision/latest?cb=20231213071844',
		},
	],
	getLevel: (level: number) => getLevel(troop.levels, level, 'level'),
}

export default troop
