import * as Constants from '@/constants'
import Army from '@IHomeVillage/troops/army.interface'
import { getLevel } from '@Utils/buildings.utility'

const troop: Army = {
	name: 'Barbarian',
	description:
		'This fearless warrior relies on his bulging muscles and striking mustache to wreak havoc in enemy villages. Release a horde of Barbarians and enjoy the mayhem!',
	maxLevel: 12,
	housingSpace: 1,
	buildingLevelRequired: 1,
	buildingName: Constants.barracks,
	superTroopUnlocked: 'Super Barbarian',
	avatarImgUrl:
		'https://static.wikia.nocookie.net/clashofclans/images/8/87/Avatar_Barbarian.png/revision/latest/scale-to-width-down/120?cb=20170525070200',
	training: {
		barracksAvailableSec: 5,
		barracksAvailableMin: 0,
		barracksUpgradingSec: 10,
		barracksUpgradingMin: 0,
	},
	mode: {
		attackType: Constants.melee,
		unitTypeTarget: Constants.ground,
		preferredTarget: Constants.none,
		minRange: 0,
		maxRange: 0.4,
		attackSpeed: 1,
		movementSpeed: 16,
	},
	levels: [
		{
			level: 1,
			damagePerSecond: 8,
			damagePerAttack: 8,
			hitpoints: 45,
			researchCost: 0,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 0,
			laboratoryLevelRequired: 0,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/d/d1/Barbarian1.png/revision/latest?cb=20171006161720',
		},
		{
			level: 2,
			damagePerSecond: 11,
			damagePerAttack: 11,
			hitpoints: 54,
			researchCost: 20000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 2,
			researchTimeDay: 0,
			laboratoryLevelRequired: 1,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/d/d1/Barbarian1.png/revision/latest?cb=20171006161720',
		},
		{
			level: 3,
			damagePerSecond: 14,
			damagePerAttack: 14,
			hitpoints: 65,
			researchCost: 60000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 5,
			researchTimeDay: 0,
			laboratoryLevelRequired: 3,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/5/50/Barbarian3.png/revision/latest?cb=20171006161735',
		},
		{
			level: 4,
			damagePerSecond: 18,
			damagePerAttack: 18,
			hitpoints: 85,
			researchCost: 200000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 0,
			laboratoryLevelRequired: 5,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/5/50/Barbarian3.png/revision/latest?cb=20171006161735',
		},
		{
			level: 5,
			damagePerSecond: 23,
			damagePerAttack: 23,
			hitpoints: 105,
			researchCost: 650000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 1,
			laboratoryLevelRequired: 6,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/7/76/Barbarian5.png/revision/latest?cb=20171006161754',
		},
		{
			level: 6,
			damagePerSecond: 26,
			damagePerAttack: 26,
			hitpoints: 125,
			researchCost: 1400000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 1,
			laboratoryLevelRequired: 7,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/4/41/Barbarian6.png/revision/latest?cb=20171006161809',
		},
		{
			level: 7,
			damagePerSecond: 30,
			damagePerAttack: 30,
			hitpoints: 160,
			researchCost: 2100000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 2,
			laboratoryLevelRequired: 8,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/d/d2/Barbarian7.png/revision/latest?cb=20171006161828',
		},
		{
			level: 8,
			damagePerSecond: 34,
			damagePerAttack: 34,
			hitpoints: 205,
			researchCost: 2800000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 2,
			laboratoryLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/5/51/Barbarian8.png/revision/latest?cb=20180607154444',
		},
		{
			level: 9,
			damagePerSecond: 38,
			damagePerAttack: 38,
			hitpoints: 230,
			researchCost: 5000000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 3,
			laboratoryLevelRequired: 10,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/9/94/Barbarian9.png/revision/latest?cb=20200404145332',
		},
		{
			level: 10,
			damagePerSecond: 42,
			damagePerAttack: 42,
			hitpoints: 250,
			researchCost: 10000000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 6,
			laboratoryLevelRequired: 12,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/f/f8/Barbarian10.png/revision/latest?cb=20210413032910',
		},
		{
			level: 11,
			damagePerSecond: 45,
			damagePerAttack: 45,
			hitpoints: 270,
			researchCost: 16000000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 12,
			laboratoryLevelRequired: 13,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/4/42/Barbarian11.png/revision/latest?cb=20221123222910',
		},
		{
			level: 12,
			damagePerSecond: 48,
			damagePerAttack: 48,
			hitpoints: 290,
			researchCost: 18000000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 13,
			laboratoryLevelRequired: 14,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/1c/Barbarian12.png/revision/latest?cb=20231213071741',
		},
	],
	getLevel: (level: number) => getLevel(troop.levels, level, 'level'),
}

export default troop
