import * as Constants from '@/constants'
import Army from '@IHomeVillage/troops/elixirTroops/dragonRider/army.interface'
import { getLevel } from '@Utils/buildings.utility'

const troop: Army = {
	name: 'Dragon Rider',
	description:
		"This aerial engine of destruction readily and frankly, quite excitedly lays waste to any defense it comes across. The skeleton onboard swears he's not touching the controls.",
	maxLevel: 4,
	housingSpace: 25,
	barracksLevelRequired: 15,
	training: {
		barracksAvailableSec: 10,
		barracksAvailableMin: 4,
		barracksUpgradingSec: 20,
		barracksUpgradingMin: 8,
	},
	mode: {
		attackType: Constants.ranged,
		unitTypeTarget: Constants.groundAndAir,
		preferredTarget: Constants.defenses,
		minRange: 0,
		maxRange: 4,
		attackSpeed: 1.2,
		movementSpeed: 20,
		damageRadius: 2,
	},
	levels: [
		{
			level: 1,
			damagePerSecond: 340,
			damagePerAttack: 408,
			damageUponDeath: 700,
			hitpoints: 4100,
			researchCost: 0,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 0,
			laboratoryLevelRequired: 0,
			baseImgUrl: '',
		},
		{
			level: 2,
			damagePerSecond: 370,
			damagePerAttack: 444,
			damageUponDeath: 800,
			hitpoints: 4400,
			researchCost: 9600000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 9,
			laboratoryLevelRequired: 11,
			baseImgUrl: '',
		},
		{
			level: 3,
			damagePerSecond: 400,
			damagePerAttack: 480,
			damageUponDeath: 900,
			hitpoints: 4700,
			researchCost: 16500000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 14,
			laboratoryLevelRequired: 12,
			baseImgUrl: '',
		},
		{
			level: 4,
			damagePerSecond: 430,
			damagePerAttack: 516,
			damageUponDeath: 1000,
			hitpoints: 5000,
			researchCost: 21500000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 16,
			laboratoryLevelRequired: 14,
			baseImgUrl: '',
		},
	],
	getLevel: (level: number) => getLevel(troop.levels, level, 'level'),
}

export default troop
