import * as Constants from '@/constants'
import Army from '@IHomeVillage/troops/army.interface'
import { getLevel } from '@Utils/buildings.utility'

const troop: Army = {
	name: 'Dragon',
	description:
		'The might of the dragons are known throughout the land. This scaly terror of the skies feels no mercy and nothing will escape the fiery splashes of his breath.',
	maxLevel: 11,
	housingSpace: 20,
	buildingLevelRequired: 9,
	buildingName: Constants.barracks,
	superTroopUnlocked: 'Super Dragon',
	training: {
		barracksAvailableSec: 0,
		barracksAvailableMin: 3,
		barracksUpgradingSec: 0,
		barracksUpgradingMin: 6,
	},
	mode: {
		attackType: Constants.areaSplash,
		unitTypeTarget: Constants.groundAndAir,
		preferredTarget: Constants.none,
		minRange: 0,
		maxRange: 3,
		attackSpeed: 1.25,
		movementSpeed: 16,
	},
	levels: [
		{
			level: 1,
			damagePerSecond: 140,
			damagePerAttack: 175,
			hitpoints: 1900,
			researchCost: 0,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 0,
			laboratoryLevelRequired: 0,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/f/fd/Dragon1.png/revision/latest/scale-to-width-down/130?cb=20210109071116',
		},
		{
			level: 2,
			damagePerSecond: 160,
			damagePerAttack: 200,
			hitpoints: 2100,
			researchCost: 1000000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 18,
			researchTimeDay: 0,
			laboratoryLevelRequired: 5,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/9/91/Dragon2.png/revision/latest/scale-to-width-down/130?cb=20210109071207',
		},
		{
			level: 3,
			damagePerSecond: 180,
			damagePerAttack: 225,
			hitpoints: 2300,
			researchCost: 2000000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 1,
			laboratoryLevelRequired: 6,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/8/82/Dragon3.png/revision/latest/scale-to-width-down/130?cb=20210109071227',
		},
		{
			level: 4,
			damagePerSecond: 210,
			damagePerAttack: 262.5,
			hitpoints: 2700,
			researchCost: 3000000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 3,
			laboratoryLevelRequired: 7,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/7/72/Dragon4.png/revision/latest/scale-to-width-down/130?cb=20210430103352',
		},
		{
			level: 5,
			damagePerSecond: 240,
			damagePerAttack: 300,
			hitpoints: 3100,
			researchCost: 3800000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 4,
			laboratoryLevelRequired: 8,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/5/5d/Dragon5.png/revision/latest/scale-to-width-down/130?cb=20210109071307',
		},
		{
			level: 6,
			damagePerSecond: 270,
			damagePerAttack: 337.5,
			hitpoints: 3400,
			researchCost: 4900000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 6,
			researchTimeDay: 5,
			laboratoryLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/e/ec/Dragon6.png/revision/latest/scale-to-width-down/130?cb=20210109071328',
		},
		{
			level: 7,
			damagePerSecond: 310,
			damagePerAttack: 387.5,
			hitpoints: 3900,
			researchCost: 6300000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 5,
			laboratoryLevelRequired: 10,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/c/c3/Dragon7.png/revision/latest/scale-to-width-down/130?cb=20210109071346',
		},
		{
			level: 8,
			damagePerSecond: 330,
			damagePerAttack: 412.5,
			hitpoints: 4200,
			researchCost: 8800000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 7,
			laboratoryLevelRequired: 11,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/7/77/Dragon8.png/revision/latest/scale-to-width-down/130?cb=20210109071418',
		},
		{
			level: 9,
			damagePerSecond: 350,
			damagePerAttack: 437.5,
			hitpoints: 4500,
			researchCost: 17500000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 12,
			laboratoryLevelRequired: 12,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/a/a0/Dragon9.png/revision/latest/scale-to-width-down/130?cb=20210615093744',
		},
		{
			level: 10,
			damagePerSecond: 370,
			damagePerAttack: 462.5,
			hitpoints: 4900,
			researchCost: 19500000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 14,
			laboratoryLevelRequired: 13,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/9/9b/Dragon10.png/revision/latest/scale-to-width-down/130?cb=20230613094758',
		},
		{
			level: 11,
			damagePerSecond: 390,
			damagePerAttack: 487.5,
			hitpoints: 5200,
			researchCost: 21500000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 16,
			laboratoryLevelRequired: 14,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/0/0b/Dragon11.png/revision/latest/scale-to-width-down/130?cb=20231213081458',
		},
	],
	getLevel: (level: number) => getLevel(troop.levels, level, 'level'),
}

export default troop
