import * as Constants from '@/constants'
import Army from '@IHomeVillage/troops/elixirTroops/electroDragon/army.interface'
import { getLevel } from '@Utils/buildings.utility'

const troop: Army = {
	name: 'Electro Dragon',
	description:
		"Possessing iron-tough scales and a breath of devastating lightning, the Electro Dragon's favorite thing is raining destruction from above. When vanquished, the Electro Dragon even pummels the ground with lightning strikes!",
	maxLevel: 7,
	housingSpace: 30,
	barracksLevelRequired: 13,
	training: {
		barracksAvailableSec: 0,
		barracksAvailableMin: 6,
		barracksUpgradingSec: 0,
		barracksUpgradingMin: 12,
	},
	mode: {
		attackType: Constants.chainLightning,
		unitTypeTarget: Constants.groundAndAir,
		preferredTarget: Constants.none,
		minRange: 0,
		maxRange: 3,
		attackSpeed: 3.5,
		movementSpeed: 13,
		numberOfTargets: 5,
		chainDamageDecay: -20,
	},
	levels: [
		{
			level: 1,
			damagePerSecond: 240,
			damagePerAttack: 840,
			damageWhenDestroyed: 65,
			hitpoints: 3200,
			researchCost: 0,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 0,
			laboratoryLevelRequired: 0,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/16/Electro_Dragon1.png/revision/latest/scale-to-width-down/150?cb=20180608132416',
		},
		{
			level: 2,
			damagePerSecond: 270,
			damagePerAttack: 945,
			damageWhenDestroyed: 75,
			hitpoints: 3700,
			researchCost: 6300000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 5,
			laboratoryLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/16/Electro_Dragon1.png/revision/latest/scale-to-width-down/150?cb=20180608132416',
		},
		{
			level: 3,
			damagePerSecond: 300,
			damagePerAttack: 1050,
			damageWhenDestroyed: 85,
			hitpoints: 4200,
			researchCost: 7000000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 5,
			laboratoryLevelRequired: 10,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/16/Electro_Dragon1.png/revision/latest/scale-to-width-down/150?cb=20180608132416',
		},
		{
			level: 4,
			damagePerSecond: 330,
			damagePerAttack: 1155,
			damageWhenDestroyed: 95,
			hitpoints: 4500,
			researchCost: 9600000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 9,
			laboratoryLevelRequired: 11,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/2/2d/Electro_Dragon4.png/revision/latest/scale-to-width-down/150?cb=20200901090418',
		},
		{
			level: 5,
			damagePerSecond: 360,
			damagePerAttack: 1260,
			damageWhenDestroyed: 105,
			hitpoints: 4800,
			researchCost: 18000000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 12,
			laboratoryLevelRequired: 12,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/9/97/Electro_Dragon5.png/revision/latest/scale-to-width-down/150?cb=20210804085946',
		},
		{
			level: 6,
			damagePerSecond: 390,
			damagePerAttack: 1365,
			damageWhenDestroyed: 115,
			hitpoints: 5100,
			researchCost: 20000000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 14,
			laboratoryLevelRequired: 13,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/2/27/Electro_Dragon6.png/revision/latest/scale-to-width-down/150?cb=20221011043659',
		},
		{
			level: 7,
			damagePerSecond: 420,
			damagePerAttack: 1470,
			damageWhenDestroyed: 125,
			hitpoints: 5300,
			researchCost: 22000000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 16,
			laboratoryLevelRequired: 14,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/2/24/Electro_Dragon7.png/revision/latest/scale-to-width-down/150?cb=20231211145650',
		},
	],
	getLevel: (level: number) => getLevel(troop.levels, level, 'level'),
}

export default troop
