import * as Constants from '@/constants'
import Army from '@IHomeVillage/troops/army.interface'
import { getLevel } from '@Utils/buildings.utility'

const troop: Army = {
	name: 'Giant',
	description:
		"These big guys may seem calm, but show them a turret or cannon and you'll see their fury unleashed! Slow yet durable, these warriors are best used to soak up hits.",
	maxLevel: 12,
	housingSpace: 5,
	buildingLevelRequired: 3,
	buildingName: Constants.barracks,
	superTroopUnlocked: 'Super Giant',
	avatarImgUrl:
		'https://static.wikia.nocookie.net/clashofclans/images/7/7d/Avatar_Giant.png/revision/latest/scale-to-width-down/120?cb=20170525070402',
	training: {
		barracksAvailableSec: 30,
		barracksAvailableMin: 0,
		barracksUpgradingSec: 0,
		barracksUpgradingMin: 1,
	},
	mode: {
		attackType: Constants.melee,
		unitTypeTarget: Constants.ground,
		preferredTarget: Constants.defenses,
		minRange: 0,
		maxRange: 1,
		attackSpeed: 2,
		movementSpeed: 12,
	},
	levels: [
		{
			level: 1,
			damagePerSecond: 11,
			damagePerAttack: 22,
			hitpoints: 300,
			researchCost: 0,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 0,
			laboratoryLevelRequired: 0,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/0/00/Giant1.png/revision/latest/scale-to-width-down/100?cb=20221123234257',
		},
		{
			level: 2,
			damagePerSecond: 14,
			damagePerAttack: 28,
			hitpoints: 360,
			researchCost: 40000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 4,
			researchTimeDay: 0,
			laboratoryLevelRequired: 2,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/0/00/Giant1.png/revision/latest/scale-to-width-down/100?cb=20221123234257',
		},
		{
			level: 3,
			damagePerSecond: 19,
			damagePerAttack: 38,
			hitpoints: 450,
			researchCost: 150000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 8,
			researchTimeDay: 0,
			laboratoryLevelRequired: 4,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/7/7a/Giant3.png/revision/latest/scale-to-width-down/100?cb=20221123234305',
		},
		{
			level: 4,
			damagePerSecond: 24,
			damagePerAttack: 48,
			hitpoints: 600,
			researchCost: 500000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 0,
			laboratoryLevelRequired: 5,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/7/7a/Giant3.png/revision/latest/scale-to-width-down/100?cb=20221123234305',
		},
		{
			level: 5,
			damagePerSecond: 31,
			damagePerAttack: 62,
			hitpoints: 800,
			researchCost: 1200000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 1,
			laboratoryLevelRequired: 6,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/e/ea/Giant5.png/revision/latest/scale-to-width-down/100?cb=20221123234323',
		},
		{
			level: 6,
			damagePerSecond: 43,
			damagePerAttack: 86,
			hitpoints: 1100,
			researchCost: 2000000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 2,
			laboratoryLevelRequired: 7,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/a/a6/Giant6.png/revision/latest/scale-to-width-down/100?cb=20221123234339',
		},
		{
			level: 7,
			damagePerSecond: 55,
			damagePerAttack: 110,
			hitpoints: 1300,
			researchCost: 3000000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 20,
			researchTimeDay: 2,
			laboratoryLevelRequired: 8,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/a/a3/Giant7.png/revision/latest/scale-to-width-down/100?cb=20221123234352',
		},
		{
			level: 8,
			damagePerSecond: 62,
			damagePerAttack: 124,
			hitpoints: 1500,
			researchCost: 3500000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 4,
			laboratoryLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/8/8f/Giant8.png/revision/latest/scale-to-width-down/100?cb=20221123234407',
		},
		{
			level: 9,
			damagePerSecond: 70,
			damagePerAttack: 140,
			hitpoints: 1850,
			researchCost: 5600000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 5,
			laboratoryLevelRequired: 10,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/9/98/Giant9.png/revision/latest/scale-to-width-down/100?cb=20221123234421',
		},
		{
			level: 10,
			damagePerSecond: 78,
			damagePerAttack: 156,
			hitpoints: 2000,
			researchCost: 8000000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 7,
			laboratoryLevelRequired: 11,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/0/02/Giant10.png/revision/latest/scale-to-width-down/100?cb=20221123234439',
		},
		{
			level: 11,
			damagePerSecond: 86,
			damagePerAttack: 172,
			hitpoints: 2200,
			researchCost: 16500000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 12,
			laboratoryLevelRequired: 13,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/0/07/Giant11.png/revision/latest/scale-to-width-down/100?cb=20221123234447',
		},
		{
			level: 12,
			damagePerSecond: 94,
			damagePerAttack: 188,
			hitpoints: 2400,
			researchCost: 18500000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 14,
			laboratoryLevelRequired: 14,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/c/cf/Giant12.png/revision/latest/scale-to-width-down/100?cb=20231213072010',
		},
	],
	getLevel: (level: number) => getLevel(troop.levels, level, 'level'),
}

export default troop
