import * as Constants from '@/constants'
import Army from '@IHomeVillage/troops/elixirTroops/healer/army.interface'
import { getLevel } from '@Utils/buildings.utility'

const troop: Army = {
	name: 'Healer',
	description:
		'This majestic creature lives to protect and aid her fellow troops. Any army is improved with her healing support, but make sure to protect her from air defenses!',
	maxLevel: 9,
	housingSpace: 14,
	barracksLevelRequired: 8,
	training: {
		barracksAvailableSec: 0,
		barracksAvailableMin: 2,
		barracksUpgradingSec: 0,
		barracksUpgradingMin: 4,
	},
	mode: {
		attackType: Constants.healSplash,
		unitTypeTarget: Constants.ground,
		preferredTarget: Constants.none,
		minRange: 0,
		maxRange: 5,
		healSpeed: 0.7,
		movementSpeed: 16,
	},
	effectiveness: [
		{
			totalNumberOfHealers: 1,
			effectivenessOfAdditionalHealer: 100,
			overallEfficency: 100,
		},
		{
			totalNumberOfHealers: 2,
			effectivenessOfAdditionalHealer: 100,
			overallEfficency: 100,
		},
		{
			totalNumberOfHealers: 3,
			effectivenessOfAdditionalHealer: 90,
			overallEfficency: 96.7,
		},
		{
			totalNumberOfHealers: 4,
			effectivenessOfAdditionalHealer: 90,
			overallEfficency: 95,
		},
		{
			totalNumberOfHealers: 5,
			effectivenessOfAdditionalHealer: 70,
			overallEfficency: 90,
		},
		{
			totalNumberOfHealers: 6,
			effectivenessOfAdditionalHealer: 40,
			overallEfficency: 81.7,
		},
		{
			totalNumberOfHealers: 7,
			effectivenessOfAdditionalHealer: 10,
			overallEfficency: 71.4,
		},
		{
			totalNumberOfHealers: 8,
			effectivenessOfAdditionalHealer: 0,
			overallEfficency: 62.5,
		},
	],
	levels: [
		{
			level: 1,
			healingPerSecond: 36,
			healingPerPulse: 25.2,
			healingPerSecondOnHeroes: 19,
			hitpoints: 500,
			researchCost: 0,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 0,
			laboratoryLevelRequired: 0,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/c/c0/Healer1.png/revision/latest/scale-to-width-down/100?cb=20230613094007',
		},
		{
			level: 2,
			healingPerSecond: 48,
			healingPerPulse: 33.6,
			healingPerSecondOnHeroes: 26,
			hitpoints: 700,
			researchCost: 450000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 0,
			laboratoryLevelRequired: 5,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/c/c0/Healer1.png/revision/latest/scale-to-width-down/100?cb=20230613094007',
		},
		{
			level: 3,
			healingPerSecond: 60,
			healingPerPulse: 42,
			healingPerSecondOnHeroes: 33,
			hitpoints: 900,
			researchCost: 900000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 1,
			laboratoryLevelRequired: 6,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/e/eb/Healer3.png/revision/latest/scale-to-width-down/100?cb=20230613094018',
		},
		{
			level: 4,
			healingPerSecond: 66,
			healingPerPulse: 46.2,
			healingPerSecondOnHeroes: 36,
			hitpoints: 1200,
			researchCost: 2700000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 2,
			laboratoryLevelRequired: 7,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/a/a7/Healer4.png/revision/latest/scale-to-width-down/100?cb=20230613094029',
		},
		{
			level: 5,
			healingPerSecond: 72,
			healingPerPulse: 50.4,
			healingPerSecondOnHeroes: 48,
			hitpoints: 1500,
			researchCost: 4200000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 4,
			laboratoryLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/e/ee/Healer5.png/revision/latest/scale-to-width-down/100?cb=20230613094033',
		},
		{
			level: 6,
			healingPerSecond: 72,
			healingPerPulse: 50.4,
			healingPerSecondOnHeroes: 56,
			hitpoints: 1600,
			researchCost: 8000000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 6,
			laboratoryLevelRequired: 11,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/e/ee/Healer5.png/revision/latest/scale-to-width-down/100?cb=20230613094033',
		},
		{
			level: 7,
			healingPerSecond: 72,
			healingPerPulse: 50.4,
			healingPerSecondOnHeroes: 62,
			hitpoints: 1700,
			researchCost: 16000000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 12,
			laboratoryLevelRequired: 12,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/9/98/Healer7.png/revision/latest/scale-to-width-down/100?cb=20230613094039',
		},
		{
			level: 8,
			healingPerSecond: 76,
			healingPerPulse: 53.2,
			healingPerSecondOnHeroes: 65,
			hitpoints: 1800,
			researchCost: 18000000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 6,
			researchTimeDay: 13,
			laboratoryLevelRequired: 13,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/5/5f/Healer8.png/revision/latest/scale-to-width-down/100?cb=20230613094046',
		},
		{
			level: 9,
			healingPerSecond: 80,
			healingPerPulse: 56,
			healingPerSecondOnHeroes: 68,
			hitpoints: 1900,
			researchCost: 21000000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 15,
			laboratoryLevelRequired: 14,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/7/72/Healer9.png/revision/latest/scale-to-width-down/100?cb=20231213081358',
		},
	],
	getLevel: (level: number) => getLevel(troop.levels, level, 'level'),
}

export default troop
