import * as Constants from '@/constants'
import Army from '@IHomeVillage/troops/army.interface'
import { getLevel } from '@Utils/buildings.utility'

const troop: Army = {
	name: 'Miner',
	description:
		'These sneaky shovelers burrow underground, pass beneath walls, and pop up right next to their targets. While underground, Miners cannot be damaged and will not trigger traps, but still gain bonuses from Spells.',
	maxLevel: 10,
	housingSpace: 6,
	buildingLevelRequired: 12,
	buildingName: Constants.barracks,
	superTroopUnlocked: 'Super Miner',
	training: {
		barracksAvailableSec: 30,
		barracksAvailableMin: 0,
		barracksUpgradingSec: 0,
		barracksUpgradingMin: 1,
	},
	mode: {
		attackType: Constants.melee,
		unitTypeTarget: Constants.ground,
		preferredTarget: Constants.none,
		minRange: 0,
		maxRange: 0.5,
		attackSpeed: 1.7,
		movementSpeed: 32,
	},
	levels: [
		{
			level: 1,
			damagePerSecond: 80,
			damagePerAttack: 136,
			hitpoints: 550,
			researchCost: 0,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 0,
			laboratoryLevelRequired: 0,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/b/b6/Miner1.png/revision/latest?cb=20221124014800',
		},
		{
			level: 2,
			damagePerSecond: 88,
			damagePerAttack: 149.6,
			hitpoints: 610,
			researchCost: 2500000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 2,
			laboratoryLevelRequired: 8,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/b/b6/Miner1.png/revision/latest?cb=20221124014800',
		},
		{
			level: 3,
			damagePerSecond: 96,
			damagePerAttack: 163.2,
			hitpoints: 670,
			researchCost: 3200000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 3,
			laboratoryLevelRequired: 8,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/c/ce/Miner3.png/revision/latest?cb=20221124014811',
		},
		{
			level: 4,
			damagePerSecond: 104,
			damagePerAttack: 176.8,
			hitpoints: 730,
			researchCost: 3800000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 4,
			laboratoryLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/c/ce/Miner3.png/revision/latest?cb=20221124014811',
		},
		{
			level: 5,
			damagePerSecond: 112,
			damagePerAttack: 190.4,
			hitpoints: 800,
			researchCost: 5000000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 6,
			researchTimeDay: 4,
			laboratoryLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/d/d2/Miner5.png/revision/latest?cb=20221124014826',
		},
		{
			level: 6,
			damagePerSecond: 120,
			damagePerAttack: 204,
			hitpoints: 900,
			researchCost: 5800000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 7,
			laboratoryLevelRequired: 10,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/d/d2/Miner5.png/revision/latest?cb=20221124014826',
		},
		{
			level: 7,
			damagePerSecond: 128,
			damagePerAttack: 217.6,
			hitpoints: 1000,
			researchCost: 8000000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			laboratoryLevelRequired: 11,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/9/96/Miner7.png/revision/latest?cb=20221124014940',
		},
		{
			level: 8,
			damagePerSecond: 136,
			damagePerAttack: 231.2,
			hitpoints: 1100,
			researchCost: 16500000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 11,
			laboratoryLevelRequired: 12,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/d/d1/Miner8.png/revision/latest?cb=20221124015004',
		},
		{
			level: 9,
			damagePerSecond: 144,
			damagePerAttack: 244.8,
			hitpoints: 1250,
			researchCost: 18500000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 6,
			researchTimeDay: 13,
			laboratoryLevelRequired: 13,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/2/2f/Miner9.png/revision/latest?cb=20221124015020',
		},
		{
			level: 10,
			damagePerSecond: 152,
			damagePerAttack: 258.4,
			hitpoints: 1400,
			researchCost: 20500000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 15,
			laboratoryLevelRequired: 13,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/4/43/Miner10.png/revision/latest?cb=20231213082004',
		},
	],
	getLevel: (level: number) => getLevel(troop.levels, level, 'level'),
}

export default troop
