import * as Constants from '@/constants'
import Army from '@IHomeVillage/troops/army.interface'
import { getLevel } from '@Utils/buildings.utility'

const troop: Army = {
	name: 'P.E.K.K.A',
	description:
		"Is P.E.K.K.A a knight? A samurai? A robot? No one knows! P.E.K.K.A's armor absorbs even the mightiest of blows.",
	maxLevel: 11,
	housingSpace: 25,
	buildingLevelRequired: 10,
	buildingName: Constants.barracks,
	avatarImgUrl:
		'https://static.wikia.nocookie.net/clashofclans/images/1/1a/Avatar_P.E.K.K.A.png/revision/latest/scale-to-width-down/120?cb=20170525070542',
	training: {
		barracksAvailableSec: 0,
		barracksAvailableMin: 3,
		barracksUpgradingSec: 0,
		barracksUpgradingMin: 6,
	},
	mode: {
		attackType: Constants.melee,
		unitTypeTarget: Constants.ground,
		preferredTarget: Constants.none,
		minRange: 0,
		maxRange: 0.8,
		attackSpeed: 18,
		movementSpeed: 16,
	},
	levels: [
		{
			level: 1,
			damagePerSecond: 260,
			damagePerAttack: 468,
			hitpoints: 3000,
			researchCost: 0,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 0,
			laboratoryLevelRequired: 0,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/c/c8/PEKKA1.png/revision/latest?cb=20221126015550',
		},
		{
			level: 2,
			damagePerSecond: 290,
			damagePerAttack: 522,
			hitpoints: 3500,
			researchCost: 1200000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 0,
			laboratoryLevelRequired: 6,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/0/00/PEKKA2.png/revision/latest?cb=20221126015600',
		},
		{
			level: 3,
			damagePerSecond: 320,
			damagePerAttack: 576,
			hitpoints: 4000,
			researchCost: 1800000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 1,
			laboratoryLevelRequired: 6,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/c/cb/PEKKA3.png/revision/latest?cb=20221126020115',
		},
		{
			level: 4,
			damagePerSecond: 360,
			damagePerAttack: 648,
			hitpoints: 4500,
			researchCost: 2800000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 2,
			laboratoryLevelRequired: 7,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/c/ce/PEKKA4.png/revision/latest?cb=20221126020122',
		},
		{
			level: 5,
			damagePerSecond: 410,
			damagePerAttack: 738,
			hitpoints: 5000,
			researchCost: 3200000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 16,
			researchTimeDay: 2,
			laboratoryLevelRequired: 8,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/5/58/PEKKA5.png/revision/latest?cb=20221126015646',
		},
		{
			level: 6,
			damagePerSecond: 470,
			damagePerAttack: 846,
			hitpoints: 5500,
			researchCost: 4200000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 3,
			laboratoryLevelRequired: 8,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/b/bf/PEKKA6.png/revision/latest?cb=20221126015657',
		},
		{
			level: 7,
			damagePerSecond: 540,
			damagePerAttack: 972,
			hitpoints: 5900,
			researchCost: 5200000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 18,
			researchTimeDay: 4,
			laboratoryLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/d/d7/PEKKA7.png/revision/latest?cb=20221126015735',
		},
		{
			level: 8,
			damagePerSecond: 610,
			damagePerAttack: 1098,
			hitpoints: 6300,
			researchCost: 7000000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 6,
			laboratoryLevelRequired: 10,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/0/09/PEKKA8.png/revision/latest?cb=20221126015752',
		},
		{
			level: 9,
			damagePerSecond: 680,
			damagePerAttack: 1224,
			hitpoints: 6700,
			researchCost: 8500000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 7,
			laboratoryLevelRequired: 11,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/a/a1/PEKKA9.png/revision/latest?cb=20221126015805',
		},
		{
			level: 10,
			damagePerSecond: 750,
			damagePerAttack: 1350,
			hitpoints: 7200,
			researchCost: 18000000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 13,
			laboratoryLevelRequired: 13,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/a/a0/PEKKA10.png/revision/latest?cb=20230613095241',
		},
		{
			level: 11,
			damagePerSecond: 810,
			damagePerAttack: 1458,
			hitpoints: 7700,
			researchCost: 20500000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 14,
			laboratoryLevelRequired: 14,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/2/2a/PEKKA11.png/revision/latest?cb=20231213081717',
		},
	],
	getLevel: (level: number) => getLevel(troop.levels, level, 'level'),
}

export default troop
