import * as Constants from '@/constants'
import Army from '@IHomeVillage/troops/army.interface'
import { getLevel } from '@Utils/buildings.utility'

const troop: Army = {
	name: 'Wall Breaker',
	description:
		"Nothing warms a Wall Breaker's cold and undead heart like blowing up walls. A squad of them will make way for your ground units, and they will do it with a BANG!",
	maxLevel: 12,
	housingSpace: 2,
	buildingLevelRequired: 5,
	buildingName: Constants.barracks,
	superTroopUnlocked: 'Super Wallbreaker',
	avatarImgUrl:
		'https://static.wikia.nocookie.net/clashofclans/images/3/36/Avatar_Wall_Breaker.png/revision/latest/scale-to-width-down/120?cb=20200913015114',
	training: {
		barracksAvailableSec: 15,
		barracksAvailableMin: 0,
		barracksUpgradingSec: 30,
		barracksUpgradingMin: 0,
	},
	mode: {
		attackType: Constants.areaSplash,
		unitTypeTarget: Constants.ground,
		preferredTarget: Constants.walls,
		minRange: 0,
		maxRange: 1,
		attackSpeed: 1,
		damageRadius: 2,
		movementSpeed: 24,
	},
	levels: [
		{
			level: 1,
			damagePerSecond: 6,
			damageUponDeath: 6,
			damageVsWalls: 240,
			damageWhenDestroyedVsWalls: 240,
			hitpoints: 20,
			researchCost: 0,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 0,
			laboratoryLevelRequired: 0,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/7/7f/Wall_Breaker1.png/revision/latest?cb=20221124035947',
		},
		{
			level: 2,
			damagePerSecond: 10,
			damageUponDeath: 9,
			damageVsWalls: 400,
			damageWhenDestroyedVsWalls: 360,
			hitpoints: 24,
			researchCost: 100000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 6,
			researchTimeDay: 0,
			laboratoryLevelRequired: 2,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/7/7f/Wall_Breaker1.png/revision/latest?cb=20221124035947',
		},
		{
			level: 3,
			damagePerSecond: 15,
			damageUponDeath: 13,
			damageVsWalls: 600,
			damageWhenDestroyedVsWalls: 520,
			hitpoints: 29,
			researchCost: 250000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 0,
			laboratoryLevelRequired: 4,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/9/91/Wall_Breaker3.png/revision/latest?cb=20221124035954',
		},
		{
			level: 4,
			damagePerSecond: 20,
			damageUponDeath: 16,
			damageVsWalls: 800,
			damageWhenDestroyedVsWalls: 640,
			hitpoints: 35,
			researchCost: 600000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 18,
			researchTimeDay: 0,
			laboratoryLevelRequired: 5,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/9/91/Wall_Breaker3.png/revision/latest?cb=20221124035954',
		},
		{
			level: 5,
			damagePerSecond: 43,
			damageUponDeath: 23,
			damageVsWalls: 1720,
			damageWhenDestroyedVsWalls: 920,
			hitpoints: 53,
			researchCost: 1200000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 1,
			laboratoryLevelRequired: 6,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/a/ac/Wall_Breaker5.png/revision/latest?cb=20221124040007',
		},
		{
			level: 6,
			damagePerSecond: 55,
			damageUponDeath: 30,
			damageVsWalls: 2200,
			damageWhenDestroyedVsWalls: 1200,
			hitpoints: 72,
			researchCost: 2500000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 1,
			laboratoryLevelRequired: 8,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/b/be/Wall_Breaker6.png/revision/latest?cb=20221124040016',
		},
		{
			level: 7,
			damagePerSecond: 66,
			damageUponDeath: 36,
			damageVsWalls: 2640,
			damageWhenDestroyedVsWalls: 1440,
			hitpoints: 82,
			researchCost: 4200000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 3,
			researchTimeDay: 2,
			laboratoryLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/7/7b/Wall_Breaker7.png/revision/latest?cb=20221124040034',
		},
		{
			level: 8,
			damagePerSecond: 75,
			damageUponDeath: 42,
			damageVsWalls: 3000,
			damageWhenDestroyedVsWalls: 1680,
			hitpoints: 92,
			researchCost: 6500000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 3,
			laboratoryLevelRequired: 10,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/7/7b/Wall_Breaker7.png/revision/latest?cb=20221124040034',
		},
		{
			level: 9,
			damagePerSecond: 86,
			damageUponDeath: 48,
			damageVsWalls: 3440,
			damageWhenDestroyedVsWalls: 1920,
			hitpoints: 112,
			researchCost: 8000000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 6,
			laboratoryLevelRequired: 11,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/7/7b/Wall_Breaker7.png/revision/latest?cb=20221124040034',
		},
		{
			level: 10,
			damagePerSecond: 94,
			damageUponDeath: 54,
			damageVsWalls: 3760,
			damageWhenDestroyedVsWalls: 2160,
			hitpoints: 130,
			researchCost: 11000000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 12,
			laboratoryLevelRequired: 12,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/15/Wall_Breaker10.png/revision/latest?cb=20221124040046',
		},
		{
			level: 11,
			damagePerSecond: 102,
			damageUponDeath: 60,
			damageVsWalls: 4080,
			damageWhenDestroyedVsWalls: 2400,
			hitpoints: 140,
			researchCost: 16500000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 12,
			laboratoryLevelRequired: 13,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/4/43/Wall_Breaker11.png/revision/latest?cb=20221124040109',
		},
		{
			level: 12,
			damagePerSecond: 110,
			damageUponDeath: 66,
			damageVsWalls: 4400,
			damageWhenDestroyedVsWalls: 2640,
			hitpoints: 150,
			researchCost: 19000000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 14,
			laboratoryLevelRequired: 14,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/c/cb/Wall_Breaker12.png/revision/latest?cb=20231213072624',
		},
	],
	getLevel: (level: number) => getLevel(troop.levels, level, 'level'),
}

export default troop
