import * as Constants from '@/constants'
import Army from '@IBuilderBase/troops/army.interface'
import { getLevel, getHallLevel } from '@Utils/buildings.utility'

const troop: Army = {
	name: 'Battle Machine',
	description:
		"The Master Builder's prize invention smashes enemy buildings to bits. What better way is there to show who's the best builder around? Unlock the Electric Hammer ability to give opponents a real pounding!",
	maxLevel: 35,
	baseImgUrl:
		'https://static.wikia.nocookie.net/clashofclans/images/7/7a/Avatar_Hero_Battle_Machine.png/revision/latest/scale-to-width-down/100?cb=20230518083349',
	mode: {
		attackType: Constants.melee,
		unitTypeTarget: Constants.ground,
		preferredTarget: Constants.none,
		minRange: 0,
		maxRange: 1.25,
		attackSpeed: 1.2,
		movementSpeed: 16,
		abilityCooldown: 13,
		duration: 3,
	},
	builderHallDetails: [
		{ builderHallLevel: 1, availableCount: 0, maxLevel: 0 },
		{ builderHallLevel: 2, availableCount: 0, maxLevel: 0 },
		{ builderHallLevel: 3, availableCount: 0, maxLevel: 0 },
		{ builderHallLevel: 4, availableCount: 0, maxLevel: 0 },
		{ builderHallLevel: 5, availableCount: 1, maxLevel: 5 },
		{ builderHallLevel: 6, availableCount: 1, maxLevel: 10 },
		{ builderHallLevel: 7, availableCount: 1, maxLevel: 20 },
		{ builderHallLevel: 8, availableCount: 1, maxLevel: 25 },
		{ builderHallLevel: 9, availableCount: 1, maxLevel: 30 },
		{ builderHallLevel: 10, availableCount: 1, maxLevel: 35 },
	],
	abilityDetails: [
		{
			chargeLevel: 1,
			attackType: Constants.none,
			chainDamageDecay: 0,
			levels: [
				{
					level: 1,
					damagePerSecond: 360,
					damagePerAttack: 432,
					healthRecovery: 800,
					numberOfTargets: 1,
				},
				{
					level: 2,
					damagePerSecond: 400,
					damagePerAttack: 480,
					healthRecovery: 850,
					numberOfTargets: 1,
				},
				{
					level: 3,
					damagePerSecond: 440,
					damagePerAttack: 528,
					healthRecovery: 900,
					numberOfTargets: 1,
				},
				{
					level: 4,
					damagePerSecond: 480,
					damagePerAttack: 576,
					healthRecovery: 950,
					numberOfTargets: 1,
				},
				{
					level: 5,
					damagePerSecond: 520,
					damagePerAttack: 624,
					healthRecovery: 1000,
					numberOfTargets: 1,
				},
				{
					level: 6,
					damagePerSecond: 560,
					damagePerAttack: 672,
					healthRecovery: 1050,
					numberOfTargets: 1,
				},
				{
					level: 7,
					damagePerSecond: 600,
					damagePerAttack: 716,
					healthRecovery: 1100,
					numberOfTargets: 1,
				},
			],
		},
		{
			chargeLevel: 2,
			attackType: Constants.chainLightning,
			chainDamageDecay: -50,
			levels: [
				{
					level: 1,
					damagePerSecond: 585,
					damagePerAttack: 702,
					healthRecovery: 1600,
					numberOfTargets: 1,
				},
				{
					level: 2,
					damagePerSecond: 650,
					damagePerAttack: 780,
					healthRecovery: 1700,
					numberOfTargets: 1,
				},
				{
					level: 3,
					damagePerSecond: 715,
					damagePerAttack: 858,
					healthRecovery: 1800,
					numberOfTargets: 2,
				},
				{
					level: 4,
					damagePerSecond: 780,
					damagePerAttack: 936,
					healthRecovery: 1900,
					numberOfTargets: 2,
				},
				{
					level: 5,
					damagePerSecond: 845,
					damagePerAttack: 1014,
					healthRecovery: 2000,
					numberOfTargets: 2,
				},
				{
					level: 6,
					damagePerSecond: 910,
					damagePerAttack: 1092,
					healthRecovery: 2100,
					numberOfTargets: 2,
				},
				{
					level: 7,
					damagePerSecond: 975,
					damagePerAttack: 1170,
					healthRecovery: 2200,
					numberOfTargets: 2,
				},
			],
		},
		{
			chargeLevel: 3,
			attackType: Constants.chainLightning,
			chainDamageDecay: 30,
			levels: [
				{
					level: 1,
					damagePerSecond: 810,
					damagePerAttack: 972,
					healthRecovery: 2400,
					numberOfTargets: 1,
				},
				{
					level: 2,
					damagePerSecond: 900,
					damagePerAttack: 1080,
					healthRecovery: 2550,
					numberOfTargets: 1,
				},
				{
					level: 3,
					damagePerSecond: 990,
					damagePerAttack: 1188,
					healthRecovery: 2700,
					numberOfTargets: 3,
				},
				{
					level: 4,
					damagePerSecond: 1080,
					damagePerAttack: 1296,
					healthRecovery: 2850,
					numberOfTargets: 3,
				},
				{
					level: 5,
					damagePerSecond: 1170,
					damagePerAttack: 1404,
					healthRecovery: 3000,
					numberOfTargets: 3,
				},
				{
					level: 6,
					damagePerSecond: 1260,
					damagePerAttack: 1512,
					healthRecovery: 3150,
					numberOfTargets: 3,
				},
				{
					level: 7,
					damagePerSecond: 1350,
					damagePerAttack: 1620,
					healthRecovery: 3300,
					numberOfTargets: 3,
				},
			],
		},
	],
	levels: [
		{
			level: 1,
			damagePerSecond: 125,
			damagePerAttack: 150,
			hitpoints: 3000,
			abilityLevel: 0,
			researchCost: 900000,
			researchCostResource: Constants.builderElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 0,
			builderHallLevelRequired: 5,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/4/44/Battle_Machine1.png/revision/latest?cb=20170526043502',
		},
		{
			level: 2,
			damagePerSecond: 127,
			damagePerAttack: 152.4,
			hitpoints: 3070,
			abilityLevel: 0,
			researchCost: 1000000,
			researchCostResource: Constants.builderElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 0,
			builderHallLevelRequired: 5,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/4/44/Battle_Machine1.png/revision/latest?cb=20170526043502',
		},
		{
			level: 3,
			damagePerSecond: 130,
			damagePerAttack: 156,
			hitpoints: 3140,
			abilityLevel: 0,
			researchCost: 1100000,
			researchCostResource: Constants.builderElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 0,
			builderHallLevelRequired: 5,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/4/44/Battle_Machine1.png/revision/latest?cb=20170526043502',
		},
		{
			level: 4,
			damagePerSecond: 132,
			damagePerAttack: 158.4,
			hitpoints: 3210,
			abilityLevel: 0,
			researchCost: 1200000,
			researchCostResource: Constants.builderElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 1,
			builderHallLevelRequired: 5,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/4/44/Battle_Machine1.png/revision/latest?cb=20170526043502',
		},
		{
			level: 5,
			damagePerSecond: 135,
			damagePerAttack: 162,
			hitpoints: 3280,
			abilityLevel: 1,
			researchCost: 1300000,
			researchCostResource: Constants.builderElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 1,
			builderHallLevelRequired: 5,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/4/44/Battle_Machine1.png/revision/latest?cb=20170526043502',
		},
		{
			level: 6,
			damagePerSecond: 137,
			damagePerAttack: 164.4,
			hitpoints: 3350,
			abilityLevel: 1,
			researchCost: 1500000,
			researchCostResource: Constants.builderElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 1,
			builderHallLevelRequired: 6,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/4/44/Battle_Machine1.png/revision/latest?cb=20170526043502',
		},
		{
			level: 7,
			damagePerSecond: 140,
			damagePerAttack: 168,
			hitpoints: 3420,
			abilityLevel: 1,
			researchCost: 1600000,
			researchCostResource: Constants.builderElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 1,
			builderHallLevelRequired: 6,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/4/44/Battle_Machine1.png/revision/latest?cb=20170526043502',
		},
		{
			level: 8,
			damagePerSecond: 142,
			damagePerAttack: 170.4,
			hitpoints: 3490,
			abilityLevel: 1,
			researchCost: 1700000,
			researchCostResource: Constants.builderElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 2,
			builderHallLevelRequired: 6,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/4/44/Battle_Machine1.png/revision/latest?cb=20170526043502',
		},
		{
			level: 9,
			damagePerSecond: 145,
			damagePerAttack: 174,
			hitpoints: 3560,
			abilityLevel: 1,
			researchCost: 1800000,
			researchCostResource: Constants.builderElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 2,
			builderHallLevelRequired: 6,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/4/44/Battle_Machine1.png/revision/latest?cb=20170526043502',
		},
		{
			level: 10,
			damagePerSecond: 147,
			damagePerAttack: 176.4,
			hitpoints: 3630,
			abilityLevel: 2,
			researchCost: 1900000,
			researchCostResource: Constants.builderElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 2,
			builderHallLevelRequired: 6,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/5/53/Battle_Machine10.png/revision/latest?cb=20170526043503',
		},
		{
			level: 11,
			damagePerSecond: 150,
			damagePerAttack: 180,
			hitpoints: 3700,
			abilityLevel: 2,
			researchCost: 2100000,
			researchCostResource: Constants.builderElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 2,
			builderHallLevelRequired: 7,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/5/53/Battle_Machine10.png/revision/latest?cb=20170526043503',
		},
		{
			level: 12,
			damagePerSecond: 154,
			damagePerAttack: 184.8,
			hitpoints: 3770,
			abilityLevel: 2,
			researchCost: 2200000,
			researchCostResource: Constants.builderElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 3,
			builderHallLevelRequired: 7,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/5/53/Battle_Machine10.png/revision/latest?cb=20170526043503',
		},
		{
			level: 13,
			damagePerSecond: 157,
			damagePerAttack: 188.4,
			hitpoints: 3840,
			abilityLevel: 2,
			researchCost: 2300000,
			researchCostResource: Constants.builderElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 3,
			builderHallLevelRequired: 7,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/5/53/Battle_Machine10.png/revision/latest?cb=20170526043503',
		},
		{
			level: 14,
			damagePerSecond: 160,
			damagePerAttack: 192,
			hitpoints: 3910,
			abilityLevel: 2,
			researchCost: 2400000,
			researchCostResource: Constants.builderElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 3,
			builderHallLevelRequired: 7,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/5/53/Battle_Machine10.png/revision/latest?cb=20170526043503',
		},
		{
			level: 15,
			damagePerSecond: 164,
			damagePerAttack: 196.8,
			hitpoints: 3980,
			abilityLevel: 3,
			researchCost: 2500000,
			researchCostResource: Constants.builderElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 3,
			builderHallLevelRequired: 7,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/5/53/Battle_Machine10.png/revision/latest?cb=20170526043503',
		},
		{
			level: 16,
			damagePerSecond: 167,
			damagePerAttack: 200.4,
			hitpoints: 4050,
			abilityLevel: 3,
			researchCost: 2600000,
			researchCostResource: Constants.builderElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 4,
			builderHallLevelRequired: 7,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/5/53/Battle_Machine10.png/revision/latest?cb=20170526043503',
		},
		{
			level: 17,
			damagePerSecond: 170,
			damagePerAttack: 204,
			hitpoints: 4120,
			abilityLevel: 3,
			researchCost: 2700000,
			researchCostResource: Constants.builderElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 4,
			builderHallLevelRequired: 7,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/5/53/Battle_Machine10.png/revision/latest?cb=20170526043503',
		},
		{
			level: 18,
			damagePerSecond: 174,
			damagePerAttack: 208.8,
			hitpoints: 4190,
			abilityLevel: 3,
			researchCost: 2800000,
			researchCostResource: Constants.builderElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 4,
			builderHallLevelRequired: 7,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/5/53/Battle_Machine10.png/revision/latest?cb=20170526043503',
		},
		{
			level: 19,
			damagePerSecond: 177,
			damagePerAttack: 212.4,
			hitpoints: 4260,
			abilityLevel: 3,
			researchCost: 2900000,
			researchCostResource: Constants.builderElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 4,
			builderHallLevelRequired: 7,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/5/53/Battle_Machine10.png/revision/latest?cb=20170526043503',
		},
		{
			level: 20,
			damagePerSecond: 180,
			damagePerAttack: 216,
			hitpoints: 4330,
			abilityLevel: 4,
			researchCost: 3000000,
			researchCostResource: Constants.builderElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 4,
			builderHallLevelRequired: 7,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6f/Battle_Machine20.png/revision/latest?cb=20170526043503',
		},
		{
			level: 21,
			damagePerSecond: 186,
			damagePerAttack: 223.2,
			hitpoints: 4400,
			abilityLevel: 4,
			researchCost: 3100000,
			researchCostResource: Constants.builderElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 5,
			builderHallLevelRequired: 8,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6f/Battle_Machine20.png/revision/latest?cb=20170526043503',
		},
		{
			level: 22,
			damagePerSecond: 192,
			damagePerAttack: 230.4,
			hitpoints: 4470,
			abilityLevel: 4,
			researchCost: 3200000,
			researchCostResource: Constants.builderElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 5,
			builderHallLevelRequired: 8,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6f/Battle_Machine20.png/revision/latest?cb=20170526043503',
		},
		{
			level: 23,
			damagePerSecond: 198,
			damagePerAttack: 237.6,
			hitpoints: 4540,
			abilityLevel: 4,
			researchCost: 3300000,
			researchCostResource: Constants.builderElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 5,
			builderHallLevelRequired: 8,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6f/Battle_Machine20.png/revision/latest?cb=20170526043503',
		},
		{
			level: 24,
			damagePerSecond: 204,
			damagePerAttack: 244.8,
			hitpoints: 4610,
			abilityLevel: 4,
			researchCost: 3400000,
			researchCostResource: Constants.builderElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 5,
			builderHallLevelRequired: 8,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6f/Battle_Machine20.png/revision/latest?cb=20170526043503',
		},
		{
			level: 25,
			damagePerSecond: 210,
			damagePerAttack: 252,
			hitpoints: 4680,
			abilityLevel: 5,
			researchCost: 3500000,
			researchCostResource: Constants.builderElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 5,
			builderHallLevelRequired: 8,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6f/Battle_Machine20.png/revision/latest?cb=20170526043503',
		},
		{
			level: 26,
			damagePerSecond: 218,
			damagePerAttack: 261.6,
			hitpoints: 4750,
			abilityLevel: 5,
			researchCost: 3600000,
			researchCostResource: Constants.builderElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 6,
			builderHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/c/cf/Battle_Machine26.png/revision/latest?cb=20170526043504',
		},
		{
			level: 27,
			damagePerSecond: 226,
			damagePerAttack: 271.2,
			hitpoints: 4820,
			abilityLevel: 5,
			researchCost: 3700000,
			researchCostResource: Constants.builderElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 6,
			builderHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/c/cf/Battle_Machine26.png/revision/latest?cb=20170526043504',
		},
		{
			level: 28,
			damagePerSecond: 234,
			damagePerAttack: 280.8,
			hitpoints: 4890,
			abilityLevel: 5,
			researchCost: 3800000,
			researchCostResource: Constants.builderElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 6,
			builderHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/c/cf/Battle_Machine26.png/revision/latest?cb=20170526043504',
		},
		{
			level: 29,
			damagePerSecond: 242,
			damagePerAttack: 290.4,
			hitpoints: 4960,
			abilityLevel: 5,
			researchCost: 3900000,
			researchCostResource: Constants.builderElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 6,
			builderHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/c/cf/Battle_Machine26.png/revision/latest?cb=20170526043504',
		},
		{
			level: 30,
			damagePerSecond: 250,
			damagePerAttack: 300,
			hitpoints: 5030,
			abilityLevel: 6,
			researchCost: 4000000,
			researchCostResource: Constants.builderElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 6,
			builderHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/7/7c/Battle_Machine30.png/revision/latest?cb=20190621204043',
		},
		{
			level: 31,
			damagePerSecond: 258,
			damagePerAttack: 309.6,
			hitpoints: 5100,
			abilityLevel: 6,
			researchCost: 4100000,
			researchCostResource: Constants.builderElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 7,
			builderHallLevelRequired: 10,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/7/7c/Battle_Machine30.png/revision/latest?cb=20190621204043',
		},
		{
			level: 32,
			damagePerSecond: 266,
			damagePerAttack: 319.2,
			hitpoints: 5170,
			abilityLevel: 6,
			researchCost: 4200000,
			researchCostResource: Constants.builderElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 7,
			builderHallLevelRequired: 10,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/7/7c/Battle_Machine30.png/revision/latest?cb=20190621204043',
		},
		{
			level: 33,
			damagePerSecond: 274,
			damagePerAttack: 328.8,
			hitpoints: 5240,
			abilityLevel: 6,
			researchCost: 4300000,
			researchCostResource: Constants.builderElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 7,
			builderHallLevelRequired: 10,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/7/7c/Battle_Machine30.png/revision/latest?cb=20190621204043',
		},
		{
			level: 34,
			damagePerSecond: 282,
			damagePerAttack: 338.4,
			hitpoints: 5310,
			abilityLevel: 6,
			researchCost: 4400000,
			researchCostResource: Constants.builderElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 7,
			builderHallLevelRequired: 10,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/7/7c/Battle_Machine30.png/revision/latest?cb=20190621204043',
		},
		{
			level: 35,
			damagePerSecond: 290,
			damagePerAttack: 348,
			hitpoints: 5380,
			abilityLevel: 7,
			researchCost: 4500000,
			researchCostResource: Constants.builderElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 7,
			builderHallLevelRequired: 10,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/7/7c/Battle_Machine30.png/revision/latest?cb=20190621204043',
		},
	],
	getLevel: (level: number) => getLevel(troop.levels, level, 'level'),
	getBuilderHallLevel: (level: number) => getHallLevel(troop.builderHallDetails, level, 'builderHallLevel'),
}

export default troop
