import * as Constants from '@/constants'
import Army from '@IHomeVillage/troops/army.interface'
import { getLevel } from '@Utils/buildings.utility'

const troop: Army = {
	name: 'Log Launcher',
	description:
		"While the Log Launcher certainly isn't the fastest or the sturdiest, it is definitely among the meanest. The trunk-throwing contraption pummels everything in front of it with endless logs to open up a path to the enemy Town Hall. Immune to spell effects.",
	maxLevel: 5,
	housingSpace: 1,
	buildingLevelRequired: 5,
	buildingName: Constants.workshop,
	avatarImgUrl:
		'https://static.wikia.nocookie.net/clashofclans/images/7/73/Avatar_Log_Launcher.png/revision/latest/scale-to-width-down/120?cb=20210106010931',
	training: {
		barracksAvailableSec: 0,
		barracksAvailableMin: 20,
		barracksUpgradingSec: 0,
		barracksUpgradingMin: 40,
	},
	mode: {
		attackType: Constants.areaSplash,
		unitTypeTarget: Constants.ground,
		preferredTarget: Constants.walls4,
		attackSpeed: 3,
		movementSpeed: 5,
		hitpointDecayPerSecond: 156,
	},
	levels: [
		{
			level: 1,
			damagePerSecond: 140,
			damagePerAttack: 420,
			damageVsWalls: 1680,
			pointBlankDamage: 2900,
			lifetime: 25.64,
			hitpoints: 4000,
			researchCost: 0,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 0,
			laboratoryLevelRequired: 0,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/d/db/Log_Launcher1.png/revision/latest/scale-to-width-down/100?cb=20201208045811',
		},
		{
			level: 2,
			damagePerSecond: 160,
			damagePerAttack: 480,
			damageVsWalls: 1920,
			pointBlankDamage: 3000,
			lifetime: 28.2,
			hitpoints: 4400,
			researchCost: 4800000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 5,
			laboratoryLevelRequired: 10,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/b/b3/Log_Launcher2.png/revision/latest/scale-to-width-down/100?cb=20201208045812',
		},
		{
			level: 3,
			damagePerSecond: 180,
			damagePerAttack: 540,
			damageVsWalls: 2160,
			pointBlankDamage: 3100,
			lifetime: 30.76,
			hitpoints: 4800,
			researchCost: 6500000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 7,
			laboratoryLevelRequired: 10,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/3/3c/Log_Launcher3.png/revision/latest/scale-to-width-down/100?cb=20201208045812',
		},
		{
			level: 4,
			damagePerSecond: 200,
			damagePerAttack: 600,
			damageVsWalls: 2400,
			pointBlankDamage: 3200,
			lifetime: 33.33,
			hitpoints: 5200,
			researchCost: 8500000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			laboratoryLevelRequired: 11,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/2/2b/Log_Launcher4.png/revision/latest/scale-to-width-down/100?cb=20201208045812',
		},
		{
			level: 5,
			damagePerSecond: 220,
			damagePerAttack: 660,
			damageVsWalls: 2640,
			pointBlankDamage: 3400,
			lifetime: 35.25,
			hitpoints: 5500,
			researchCost: 18000000,
			researchCostResource: Constants.elixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 12,
			laboratoryLevelRequired: 14,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/f/ff/Log_Launcher5.png/revision/latest/scale-to-width-down/100?cb=20240225085906',
		},
	],
	getLevel: (level: number) => getLevel(troop.levels, level, 'level'),
}

export default troop
