import * as Constants from '@/constants'
import ResourceBuilding from '@IHomeVillage/resources/goldMine/resource.interface'
import { getHallLevel, getLevel, getSize } from '@Utils/buildings.utility'

const building: ResourceBuilding = {
	name: 'Elixir Collector',
	description:
		'Elixir is pumped from the Ley Lines coursing underneath your village. Upgrade your Elixir Collectors to maximize elixir production.',
	maxCount: 7,
	width: 3,
	height: 3,
	maxLevel: 15,
	townHallDetails: [
		{ townHallLevel: 1, availableCount: 1, maxLevel: 2 },
		{ townHallLevel: 2, availableCount: 2, maxLevel: 4 },
		{ townHallLevel: 3, availableCount: 3, maxLevel: 6 },
		{ townHallLevel: 4, availableCount: 4, maxLevel: 8 },
		{ townHallLevel: 5, availableCount: 5, maxLevel: 10 },
		{ townHallLevel: 6, availableCount: 6, maxLevel: 10 },
		{ townHallLevel: 7, availableCount: 6, maxLevel: 11 },
		{ townHallLevel: 8, availableCount: 6, maxLevel: 12 },
		{ townHallLevel: 9, availableCount: 7, maxLevel: 12 },
		{ townHallLevel: 10, availableCount: 7, maxLevel: 13 },
		{ townHallLevel: 11, availableCount: 7, maxLevel: 14 },
		{ townHallLevel: 12, availableCount: 7, maxLevel: 15 },
		{ townHallLevel: 13, availableCount: 7, maxLevel: 15 },
		{ townHallLevel: 14, availableCount: 7, maxLevel: 15 },
		{ townHallLevel: 15, availableCount: 7, maxLevel: 15 },
		{ townHallLevel: 16, availableCount: 7, maxLevel: 15 },
	],
	levels: [
		{
			level: 1,
			capacity: 1000,
			productionRatePerHr: 200,
			hitpoints: 400,
			boostCost: 0,
			timeToFillSec: 0,
			timeToFillMin: 0,
			timeToFillHour: 5,
			timeToFillDay: 0,
			buildCost: 150,
			buildCostResource: Constants.gold,
			buildTimeSec: 10,
			buildTimeMin: 0,
			buildTimeHour: 0,
			buildTimeDay: 0,
			exp: 3,
			townHallLevelRequired: 1,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/5/5e/Elixir_Collector1.png/revision/latest/scale-to-width-down/100?cb=20180109122134',
		},
		{
			level: 2,
			capacity: 2000,
			productionRatePerHr: 400,
			hitpoints: 440,
			boostCost: 0,
			timeToFillSec: 0,
			timeToFillMin: 0,
			timeToFillHour: 5,
			timeToFillDay: 0,
			buildCost: 300,
			buildCostResource: Constants.gold,
			buildTimeSec: 0,
			buildTimeMin: 1,
			buildTimeHour: 0,
			buildTimeDay: 0,
			exp: 7,
			townHallLevelRequired: 1,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/0/05/Elixir_Collector2.png/revision/latest/scale-to-width-down/100?cb=20180109122118',
		},
		{
			level: 3,
			capacity: 3000,
			productionRatePerHr: 600,
			hitpoints: 480,
			boostCost: 0,
			timeToFillSec: 0,
			timeToFillMin: 0,
			timeToFillHour: 5,
			timeToFillDay: 0,
			buildCost: 700,
			buildCostResource: Constants.gold,
			buildTimeSec: 0,
			buildTimeMin: 4,
			buildTimeHour: 0,
			buildTimeDay: 0,
			exp: 15,
			townHallLevelRequired: 2,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/6d/Elixir_Collector3.png/revision/latest/scale-to-width-down/100?cb=20180109122147',
		},
		{
			level: 4,
			capacity: 5000,
			productionRatePerHr: 800,
			hitpoints: 520,
			boostCost: 0,
			timeToFillSec: 0,
			timeToFillMin: 15,
			timeToFillHour: 6,
			timeToFillDay: 0,
			buildCost: 1400,
			buildCostResource: Constants.gold,
			buildTimeSec: 0,
			buildTimeMin: 10,
			buildTimeHour: 0,
			buildTimeDay: 0,
			exp: 24,
			townHallLevelRequired: 2,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/9/95/Elixir_Collector4.png/revision/latest/scale-to-width-down/100?cb=20180109122200',
		},
		{
			level: 5,
			capacity: 10000,
			productionRatePerHr: 1000,
			hitpoints: 560,
			boostCost: 4,
			timeToFillSec: 0,
			timeToFillMin: 0,
			timeToFillHour: 10,
			timeToFillDay: 0,
			buildCost: 3000,
			buildCostResource: Constants.gold,
			buildTimeSec: 0,
			buildTimeMin: 40,
			buildTimeHour: 0,
			buildTimeDay: 0,
			exp: 48,
			townHallLevelRequired: 3,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/4/44/Elixir_Collector5.png/revision/latest/scale-to-width-down/100?cb=20180109122215',
		},
		{
			level: 6,
			capacity: 20000,
			productionRatePerHr: 1300,
			hitpoints: 600,
			boostCost: 5,
			timeToFillSec: 5,
			timeToFillMin: 23,
			timeToFillHour: 15,
			timeToFillDay: 0,
			buildCost: 7000,
			buildCostResource: Constants.gold,
			buildTimeSec: 0,
			buildTimeMin: 0,
			buildTimeHour: 3,
			buildTimeDay: 0,
			exp: 103,
			townHallLevelRequired: 3,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/0/07/Elixir_Collector6.png/revision/latest/scale-to-width-down/100?cb=20180109122232',
		},
		{
			level: 7,
			capacity: 30000,
			productionRatePerHr: 1600,
			hitpoints: 640,
			boostCost: 6,
			timeToFillSec: 0,
			timeToFillMin: 45,
			timeToFillHour: 18,
			timeToFillDay: 0,
			buildCost: 14000,
			buildCostResource: Constants.gold,
			buildTimeSec: 0,
			buildTimeMin: 0,
			buildTimeHour: 6,
			buildTimeDay: 0,
			exp: 146,
			townHallLevelRequired: 4,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/3/35/Elixir_Collector7.png/revision/latest/scale-to-width-down/100?cb=20180109122255',
		},
		{
			level: 8,
			capacity: 50000,
			productionRatePerHr: 1900,
			hitpoints: 680,
			boostCost: 7,
			timeToFillSec: 57,
			timeToFillMin: 18,
			timeToFillHour: 2,
			timeToFillDay: 1,
			buildCost: 28000,
			buildCostResource: Constants.gold,
			buildTimeSec: 0,
			buildTimeMin: 0,
			buildTimeHour: 6,
			buildTimeDay: 0,
			exp: 146,
			townHallLevelRequired: 4,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/f/fc/Elixir_Collector8.png/revision/latest/scale-to-width-down/100?cb=20180109122310',
		},
		{
			level: 9,
			capacity: 75000,
			productionRatePerHr: 2200,
			hitpoints: 720,
			boostCost: 8,
			timeToFillSec: 27,
			timeToFillMin: 5,
			timeToFillHour: 10,
			timeToFillDay: 1,
			buildCost: 56000,
			buildCostResource: Constants.gold,
			buildTimeSec: 0,
			buildTimeMin: 0,
			buildTimeHour: 10,
			buildTimeDay: 0,
			exp: 189,
			townHallLevelRequired: 5,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/7/79/Elixir_Collector9.png/revision/latest/scale-to-width-down/100?cb=20180109122324',
		},
		{
			level: 10,
			capacity: 100000,
			productionRatePerHr: 2800,
			hitpoints: 780,
			boostCost: 9,
			timeToFillSec: 52,
			timeToFillMin: 42,
			timeToFillHour: 11,
			timeToFillDay: 1,
			buildCost: 75000,
			buildCostResource: Constants.gold,
			buildTimeSec: 0,
			buildTimeMin: 0,
			buildTimeHour: 10,
			buildTimeDay: 0,
			exp: 189,
			townHallLevelRequired: 5,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/f/f0/Elixir_Collector10.png/revision/latest/scale-to-width-down/100?cb=20180109122349',
		},
		{
			level: 11,
			capacity: 150000,
			productionRatePerHr: 3500,
			hitpoints: 860,
			boostCost: 10,
			timeToFillSec: 26,
			timeToFillMin: 51,
			timeToFillHour: 18,
			timeToFillDay: 1,
			buildCost: 85000,
			buildCostResource: Constants.gold,
			buildTimeSec: 0,
			buildTimeMin: 0,
			buildTimeHour: 12,
			buildTimeDay: 0,
			exp: 207,
			townHallLevelRequired: 7,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/9/9f/Elixir_Collector11.png/revision/latest/scale-to-width-down/100?cb=20180109122406',
		},
		{
			level: 12,
			capacity: 200000,
			productionRatePerHr: 4200,
			hitpoints: 960,
			boostCost: 10,
			timeToFillSec: 9,
			timeToFillMin: 37,
			timeToFillHour: 23,
			timeToFillDay: 1,
			buildCost: 170000,
			buildCostResource: Constants.gold,
			buildTimeSec: 0,
			buildTimeMin: 0,
			buildTimeHour: 16,
			buildTimeDay: 0,
			exp: 240,
			townHallLevelRequired: 8,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/4/4f/Elixir_Collector12.png/revision/latest/scale-to-width-down/100?cb=20180109122421',
		},
		{
			level: 13,
			capacity: 250000,
			productionRatePerHr: 4900,
			hitpoints: 1080,
			boostCost: 11,
			timeToFillSec: 14,
			timeToFillMin: 1,
			timeToFillHour: 3,
			timeToFillDay: 2,
			buildCost: 400000,
			buildCostResource: Constants.gold,
			buildTimeSec: 0,
			buildTimeMin: 0,
			buildTimeHour: 20,
			buildTimeDay: 0,
			exp: 268,
			townHallLevelRequired: 10,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/12/Elixir_Collector13.png/revision/latest/scale-to-width-down/100?cb=20200902075904',
		},
		{
			level: 14,
			capacity: 300000,
			productionRatePerHr: 5600,
			hitpoints: 1180,
			boostCost: 11,
			timeToFillSec: 18,
			timeToFillMin: 34,
			timeToFillHour: 5,
			timeToFillDay: 2,
			buildCost: 800000,
			buildCostResource: Constants.gold,
			buildTimeSec: 0,
			buildTimeMin: 0,
			buildTimeHour: 16,
			buildTimeDay: 1,
			exp: 379,
			townHallLevelRequired: 11,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/4/49/Elixir_Collector14.png/revision/latest/scale-to-width-down/100?cb=20210113220549',
		},
		{
			level: 15,
			capacity: 350000,
			productionRatePerHr: 6300,
			hitpoints: 1280,
			boostCost: 11,
			timeToFillSec: 20,
			timeToFillMin: 33,
			timeToFillHour: 7,
			timeToFillDay: 2,
			buildCost: 1200000,
			buildCostResource: Constants.gold,
			buildTimeSec: 0,
			buildTimeMin: 0,
			buildTimeHour: 18,
			buildTimeDay: 2,
			exp: 487,
			townHallLevelRequired: 12,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/7/7f/Elixir_Collector15.png/revision/latest/scale-to-width-down/100?cb=20211209201554',
		},
	],
	getSize: () => getSize(building.width, building.height),
	getLevel: (level: number) => getLevel(building.levels, level, 'level'),
	getTownHallLevel: (level: number) => getHallLevel(building.townHallDetails, level, 'townHallLevel'),
}

export default building
