import * as Constants from '@/constants'
import Building from '@IBuilderBase/other/clockTower/other.interface'
import { getHallLevel, getLevel, getSize } from '@Utils/buildings.utility'

const building: Building = {
	name: 'Clock Tower',
	description:
		'The Clock Tower makes things happen faster in your village! Collect resources, research and build faster.',
	maxCount: 1,
	width: 4,
	height: 4,
	maxLevel: 10,
	ruinImgUrl:
		'https://static.wikia.nocookie.net/clashofclans/images/f/f6/Clock_Tower_Ruin.png/revision/latest/scale-to-width-down/100?cb=20200901095355',
	builderHallDetails: [
		{ builderHallLevel: 1, availableCount: 0, maxLevel: 0, stage1MaxCount: 0, stage2MaxCount: 0 },
		{ builderHallLevel: 2, availableCount: 0, maxLevel: 0, stage1MaxCount: 0, stage2MaxCount: 0 },
		{ builderHallLevel: 3, availableCount: 0, maxLevel: 0, stage1MaxCount: 0, stage2MaxCount: 0 },
		{ builderHallLevel: 4, availableCount: 1, maxLevel: 4, stage1MaxCount: 0, stage2MaxCount: 0 },
		{ builderHallLevel: 5, availableCount: 1, maxLevel: 5, stage1MaxCount: 0, stage2MaxCount: 0 },
		{ builderHallLevel: 6, availableCount: 1, maxLevel: 6, stage1MaxCount: 1, stage2MaxCount: 0 },
		{ builderHallLevel: 7, availableCount: 1, maxLevel: 7, stage1MaxCount: 1, stage2MaxCount: 0 },
		{ builderHallLevel: 8, availableCount: 1, maxLevel: 8, stage1MaxCount: 1, stage2MaxCount: 0 },
		{ builderHallLevel: 9, availableCount: 1, maxLevel: 9, stage1MaxCount: 1, stage2MaxCount: 0 },
		{ builderHallLevel: 10, availableCount: 1, maxLevel: 10, stage1MaxCount: 1, stage2MaxCount: 0 },
	],
	levels: [
		{
			level: 1,
			hitpoints: 650,
			boostDuration: 14,
			timeGainedPerBoostSec: 0,
			timeGainedPerBoostMin: 6,
			timeGainedPerBoostHour: 2,
			timeGainedPerBoostDay: 0,
			relativeBoost: 9.4,
			catchUpPointOfConstruction: 1,
			catchUpPointOfBoost: 0,
			buildCost: 150000,
			buildCostResource: Constants.builderGold,
			buildTimeSec: 0,
			buildTimeMin: 0,
			buildTimeHour: 2,
			buildTimeDay: 0,
			exp: 84,
			builderHallLevelRequired: 4,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/e/ee/Clock_Tower1.png/revision/latest/scale-to-width-down/100?cb=20180512121553',
		},
		{
			level: 2,
			hitpoints: 800,
			boostDuration: 16,
			timeGainedPerBoostSec: 0,
			timeGainedPerBoostMin: 24,
			timeGainedPerBoostHour: 2,
			timeGainedPerBoostDay: 0,
			relativeBoost: 10.8,
			catchUpPointOfConstruction: 10,
			catchUpPointOfBoost: 0,
			buildCost: 180000,
			buildCostResource: Constants.builderGold,
			buildTimeSec: 0,
			buildTimeMin: 0,
			buildTimeHour: 3,
			buildTimeDay: 0,
			exp: 103,
			builderHallLevelRequired: 4,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/2/2b/Clock_Tower2.png/revision/latest/scale-to-width-down/100?cb=20180512121605',
		},
		{
			level: 3,
			hitpoints: 975,
			boostDuration: 18,
			timeGainedPerBoostSec: 0,
			timeGainedPerBoostMin: 42,
			timeGainedPerBoostHour: 2,
			timeGainedPerBoostDay: 0,
			relativeBoost: 12.1,
			catchUpPointOfConstruction: 14,
			catchUpPointOfBoost: 0,
			buildCost: 220000,
			buildCostResource: Constants.builderGold,
			buildTimeSec: 0,
			buildTimeMin: 0,
			buildTimeHour: 4,
			buildTimeDay: 0,
			exp: 120,
			builderHallLevelRequired: 4,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/8/81/Clock_Tower3.png/revision/latest/scale-to-width-down/100?cb=20180512121620',
		},
		{
			level: 4,
			hitpoints: 1150,
			boostDuration: 20,
			timeGainedPerBoostSec: 0,
			timeGainedPerBoostMin: 0,
			timeGainedPerBoostHour: 3,
			timeGainedPerBoostDay: 0,
			relativeBoost: 13.4,
			catchUpPointOfConstruction: 20,
			catchUpPointOfBoost: 0,
			buildCost: 300000,
			buildCostResource: Constants.builderGold,
			buildTimeSec: 0,
			buildTimeMin: 0,
			buildTimeHour: 6,
			buildTimeDay: 0,
			exp: 146,
			builderHallLevelRequired: 4,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/4/4f/Clock_Tower4.png/revision/latest/scale-to-width-down/100?cb=20180512121635',
		},
		{
			level: 5,
			hitpoints: 1350,
			boostDuration: 22,
			timeGainedPerBoostSec: 0,
			timeGainedPerBoostMin: 18,
			timeGainedPerBoostHour: 3,
			timeGainedPerBoostDay: 0,
			relativeBoost: 14.8,
			catchUpPointOfConstruction: 40,
			catchUpPointOfBoost: 0,
			buildCost: 700000,
			buildCostResource: Constants.builderGold,
			buildTimeSec: 0,
			buildTimeMin: 0,
			buildTimeHour: 12,
			buildTimeDay: 0,
			exp: 207,
			builderHallLevelRequired: 5,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/1f/Clock_Tower5.png/revision/latest/scale-to-width-down/100?cb=20180512121647',
		},
		{
			level: 6,
			hitpoints: 1600,
			boostDuration: 24,
			timeGainedPerBoostSec: 0,
			timeGainedPerBoostMin: 36,
			timeGainedPerBoostHour: 3,
			timeGainedPerBoostDay: 0,
			relativeBoost: 16.1,
			catchUpPointOfConstruction: 80,
			catchUpPointOfBoost: 1,
			buildCost: 1200000,
			buildCostResource: Constants.builderGold,
			buildTimeSec: 0,
			buildTimeMin: 0,
			buildTimeHour: 0,
			buildTimeDay: 1,
			exp: 293,
			builderHallLevelRequired: 6,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/3/37/Clock_Tower6.png/revision/latest/scale-to-width-down/100?cb=20180512121704',
		},
		{
			level: 7,
			hitpoints: 1850,
			boostDuration: 26,
			timeGainedPerBoostSec: 0,
			timeGainedPerBoostMin: 54,
			timeGainedPerBoostHour: 3,
			timeGainedPerBoostDay: 0,
			relativeBoost: 17.4,
			catchUpPointOfConstruction: 160,
			catchUpPointOfBoost: 15,
			buildCost: 1700000,
			buildCostResource: Constants.builderGold,
			buildTimeSec: 0,
			buildTimeMin: 0,
			buildTimeHour: 0,
			buildTimeDay: 2,
			exp: 415,
			builderHallLevelRequired: 7,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/9/92/Clock_Tower7.png/revision/latest/scale-to-width-down/100?cb=20170927114354',
		},
		{
			level: 8,
			hitpoints: 2150,
			boostDuration: 28,
			timeGainedPerBoostSec: 0,
			timeGainedPerBoostMin: 12,
			timeGainedPerBoostHour: 4,
			timeGainedPerBoostDay: 0,
			relativeBoost: 18.7,
			catchUpPointOfConstruction: 240,
			catchUpPointOfBoost: 30,
			buildCost: 2200000,
			buildCostResource: Constants.builderGold,
			buildTimeSec: 0,
			buildTimeMin: 0,
			buildTimeHour: 0,
			buildTimeDay: 3,
			exp: 509,
			builderHallLevelRequired: 8,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/c/c9/Clock_Tower8.png/revision/latest/scale-to-width-down/100?cb=20170927114413',
		},
		{
			level: 9,
			hitpoints: 2450,
			boostDuration: 30,
			timeGainedPerBoostSec: 0,
			timeGainedPerBoostMin: 30,
			timeGainedPerBoostHour: 4,
			timeGainedPerBoostDay: 0,
			relativeBoost: 20,
			catchUpPointOfConstruction: 320,
			catchUpPointOfBoost: 48,
			buildCost: 2700000,
			buildCostResource: Constants.builderGold,
			buildTimeSec: 0,
			buildTimeMin: 0,
			buildTimeHour: 0,
			buildTimeDay: 4,
			exp: 587,
			builderHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/d/dd/Clock_Tower9.png/revision/latest/scale-to-width-down/100?cb=20190617025510',
		},
		{
			level: 10,
			hitpoints: 2750,
			boostDuration: 32,
			timeGainedPerBoostSec: 0,
			timeGainedPerBoostMin: 48,
			timeGainedPerBoostHour: 4,
			timeGainedPerBoostDay: 0,
			relativeBoost: 21.3,
			catchUpPointOfConstruction: 400,
			catchUpPointOfBoost: 67,
			buildCost: 3700000,
			buildCostResource: Constants.builderGold,
			buildTimeSec: 0,
			buildTimeMin: 0,
			buildTimeHour: 0,
			buildTimeDay: 5,
			exp: 657,
			builderHallLevelRequired: 10,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/f/fd/Clock_Tower10.png/revision/latest/scale-to-width-down/100?cb=20230518073813',
		},
	],
	getSize: () => getSize(building.width, building.height),
	getLevel: (level: number) => getLevel(building.levels, level, 'level'),
	getBuilderHallLevel: (level: number) => getHallLevel(building.builderHallDetails, level, 'builderHallLevel'),
}

export default building
