import WallBuilding from '@IBuilderBase/wall/wall.interface'
import { getHallLevel, getLevel, getSize } from '@Utils/buildings.utility'

const building: WallBuilding = {
	name: 'Walls',
	description:
		'Walls are great for keeping your village safe and your enemies in the line of fire.',
	maxCount: 180,
	width: 1,
	height: 1,
	maxLevel: 10,
	builderHallDetails: [
		{
			builderHallLevel: 1,
			availableCount: 10,
			maxLevel: 1,
			stage1MaxCount: 0,
			stage2MaxCount: 0,
		},
		{
			builderHallLevel: 2,
			availableCount: 20,
			maxLevel: 3,
			stage1MaxCount: 0,
			stage2MaxCount: 0,
		},
		{
			builderHallLevel: 3,
			availableCount: 50,
			maxLevel: 3,
			stage1MaxCount: 0,
			stage2MaxCount: 0,
		},
		{
			builderHallLevel: 4,
			availableCount: 75,
			maxLevel: 4,
			stage1MaxCount: 0,
			stage2MaxCount: 0,
		},
		{
			builderHallLevel: 5,
			availableCount: 100,
			maxLevel: 5,
			stage1MaxCount: 0,
			stage2MaxCount: 0,
		},
		{
			builderHallLevel: 6,
			availableCount: 120,
			maxLevel: 6,
			stage1MaxCount: 0,
			stage2MaxCount: 0,
		},
		{
			builderHallLevel: 7,
			availableCount: 140,
			maxLevel: 7,
			stage1MaxCount: 0,
			stage2MaxCount: 0,
		},
		{
			builderHallLevel: 8,
			availableCount: 160,
			maxLevel: 8,
			stage1MaxCount: 0,
			stage2MaxCount: 0,
		},
		{
			builderHallLevel: 9,
			availableCount: 180,
			maxLevel: 9,
			stage1MaxCount: 0,
			stage2MaxCount: 0,
		},
		{
			builderHallLevel: 10,
			availableCount: 180,
			maxLevel: 10,
			stage1MaxCount: 0,
			stage2MaxCount: 0,
		},
	],
	levels: [
		{
			level: 1,
			hitpoints: 900,
			builderGoldBuildCost: 1000,
			builderGoldCumulativeCost: 1000,
			builderElixirBuildCost: 0,
			builderElixirCumulativeCost: 0,
			wallRingCost: 0,
			builderHallLevelRequired: 1,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/f/fb/Wall1B.png/revision/latest/scale-to-width-down/55?cb=20170927102315',
		},
		{
			level: 2,
			hitpoints: 1100,
			builderGoldBuildCost: 2000,
			builderGoldCumulativeCost: 3000,
			builderElixirBuildCost: 0,
			builderElixirCumulativeCost: 0,
			wallRingCost: 1,
			builderHallLevelRequired: 3,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/9/99/Wall2B.png/revision/latest/scale-to-width-down/55?cb=20170927102333',
		},
		{
			level: 3,
			hitpoints: 1300,
			builderGoldBuildCost: 10000,
			builderGoldCumulativeCost: 13000,
			builderElixirBuildCost: 0,
			builderElixirCumulativeCost: 0,
			wallRingCost: 1,
			builderHallLevelRequired: 3,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/9/91/Wall3B.png/revision/latest/scale-to-width-down/55?cb=20170927102352',
		},
		{
			level: 4,
			hitpoints: 1600,
			builderGoldBuildCost: 50000,
			builderGoldCumulativeCost: 63000,
			builderElixirBuildCost: 0,
			builderElixirCumulativeCost: 0,
			wallRingCost: 1,
			builderHallLevelRequired: 4,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/b/b6/Wall4B.png/revision/latest/scale-to-width-down/55?cb=20170927102413',
		},
		{
			level: 5,
			hitpoints: 1900,
			builderGoldBuildCost: 150000,
			builderGoldCumulativeCost: 213000,
			builderElixirBuildCost: 0,
			builderElixirCumulativeCost: 0,
			wallRingCost: 1,
			builderHallLevelRequired: 5,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/4/4f/Wall5B.png/revision/latest/scale-to-width-down/55?cb=20170927102434',
		},
		{
			level: 6,
			hitpoints: 2200,
			builderGoldBuildCost: 240000,
			builderGoldCumulativeCost: 453000,
			builderElixirBuildCost: 0,
			builderElixirCumulativeCost: 0,
			wallRingCost: 1,
			builderHallLevelRequired: 6,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/f/f3/Wall6B.png/revision/latest/scale-to-width-down/55?cb=20170927102501',
		},
		{
			level: 7,
			hitpoints: 2500,
			builderGoldBuildCost: 400000,
			builderGoldCumulativeCost: 853000,
			builderElixirBuildCost: 400000,
			builderElixirCumulativeCost: 400000,
			wallRingCost: 1,
			builderHallLevelRequired: 7,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/a/a2/Wall7B.png/revision/latest/scale-to-width-down/55?cb=20170927102546',
		},
		{
			level: 8,
			hitpoints: 2750,
			builderGoldBuildCost: 600000,
			builderGoldCumulativeCost: 1453000,
			builderElixirBuildCost: 600000,
			builderElixirCumulativeCost: 1000000,
			wallRingCost: 2,
			builderHallLevelRequired: 8,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/b/b7/Wall8B.png/revision/latest/scale-to-width-down/55?cb=20170927102606',
		},
		{
			level: 9,
			hitpoints: 3050,
			builderGoldBuildCost: 800000,
			builderGoldCumulativeCost: 2253000,
			builderElixirBuildCost: 800000,
			builderElixirCumulativeCost: 1800000,
			wallRingCost: 2,
			builderHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/10/Wall9B.png/revision/latest/scale-to-width-down/55?cb=20190616234919',
		},
		{
			level: 10,
			hitpoints: 3350,
			builderGoldBuildCost: 1000000,
			builderGoldCumulativeCost: 3253000,
			builderElixirBuildCost: 1000000,
			builderElixirCumulativeCost: 2800000,
			wallRingCost: 2,
			builderHallLevelRequired: 10,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/10/Wall10B.png/revision/latest/scale-to-width-down/55?cb=20230517053328',
		},
	],
	getSize: () => getSize(building.width, building.height),
	getLevel: (level: number) => getLevel(building.levels, level, 'level'),
	getBuilderHallLevel: (level: number) =>
		getHallLevel(building.builderHallDetails, level, 'builderHallLevel'),
}

export default building
