import * as Constants from '@/constants'
import BuilderHallBuilding from '@IBuilderBase/builderHall/builderHall.interface'
import { getHallLevel, getLevel, getSize } from '@Utils/buildings.utility'

const building: BuilderHallBuilding = {
	name: 'Builder Hall',
	description:
		'Home of the Master Builder and the main objective in battle. Destroying a Builder Hall awards a Star in attacks. Destroying 50% of buildings in a stage gains you a second Star, while 100% destruction awards three Stars for the stage. Upgrade the Builder Hall to unlock advanced buildings and troops!',
	width: 4,
	height: 4,
	maxLevel: 10,
	builderHallDetails: [
		{
			builderHallLevel: 1,
			availableCount: 1,
			maxLevel: 1,
			stage1MaxCount: 0,
			stage2MaxCount: 0,
		},
		{
			builderHallLevel: 2,
			availableCount: 1,
			maxLevel: 2,
			stage1MaxCount: 0,
			stage2MaxCount: 0,
		},
		{
			builderHallLevel: 3,
			availableCount: 1,
			maxLevel: 3,
			stage1MaxCount: 0,
			stage2MaxCount: 0,
		},
		{
			builderHallLevel: 4,
			availableCount: 1,
			maxLevel: 4,
			stage1MaxCount: 0,
			stage2MaxCount: 0,
		},
		{
			builderHallLevel: 5,
			availableCount: 1,
			maxLevel: 5,
			stage1MaxCount: 0,
			stage2MaxCount: 0,
		},
		{
			builderHallLevel: 6,
			availableCount: 1,
			maxLevel: 6,
			stage1MaxCount: 1,
			stage2MaxCount: 0,
		},
		{
			builderHallLevel: 7,
			availableCount: 1,
			maxLevel: 7,
			stage1MaxCount: 1,
			stage2MaxCount: 0,
		},
		{
			builderHallLevel: 8,
			availableCount: 1,
			maxLevel: 8,
			stage1MaxCount: 1,
			stage2MaxCount: 0,
		},
		{
			builderHallLevel: 9,
			availableCount: 1,
			maxLevel: 9,
			stage1MaxCount: 1,
			stage2MaxCount: 0,
		},
		{
			builderHallLevel: 10,
			availableCount: 1,
			maxLevel: 10,
			stage1MaxCount: 1,
			stage2MaxCount: 0,
		},
	],
	levels: [
		{
			level: 1,
			hitpoints: 650,
			builderGoldCapacity: 50000,
			builderElixirCapacity: 50000,
			buildCost: 0,
			buildCostResource: Constants.builderGold,
			buildTimeSec: 0,
			buildTimeMin: 0,
			buildTimeHour: 0,
			buildTimeDay: 0,
			exp: 0,
			maximumNumberOfBuildingsAvailable: 0,
			builderHallLevelRequired: 1,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/19/Builder_Hall1.png/revision/latest/scale-to-width-down/100?cb=20230516070448',
		},
		{
			level: 2,
			hitpoints: 800,
			builderGoldCapacity: 75000,
			builderElixirCapacity: 75000,
			buildCost: 3500,
			buildCostResource: Constants.builderGold,
			buildTimeSec: 5,
			buildTimeMin: 0,
			buildTimeHour: 0,
			buildTimeDay: 0,
			exp: 2,
			maximumNumberOfBuildingsAvailable: 10,
			builderHallLevelRequired: 2,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/0/03/Builder_Hall2.png/revision/latest/scale-to-width-down/100?cb=20230516070504',
		},
		{
			level: 3,
			hitpoints: 975,
			builderGoldCapacity: 100000,
			builderElixirCapacity: 100000,
			buildCost: 30000,
			buildCostResource: Constants.builderGold,
			buildTimeSec: 0,
			buildTimeMin: 0,
			buildTimeHour: 1,
			buildTimeDay: 0,
			exp: 60,
			maximumNumberOfBuildingsAvailable: 18,
			builderHallLevelRequired: 3,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/3/38/Builder_Hall3.png/revision/latest/scale-to-width-down/100?cb=20230516070513',
		},
		{
			level: 4,
			hitpoints: 1150,
			builderGoldCapacity: 150000,
			builderElixirCapacity: 150000,
			buildCost: 200000,
			buildCostResource: Constants.builderGold,
			buildTimeSec: 0,
			buildTimeMin: 0,
			buildTimeHour: 0,
			buildTimeDay: 1,
			exp: 293,
			maximumNumberOfBuildingsAvailable: 23,
			builderHallLevelRequired: 4,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/b/be/Builder_Hall4.png/revision/latest/scale-to-width-down/100?cb=20230516070524',
		},
		{
			level: 5,
			hitpoints: 1350,
			builderGoldCapacity: 900000,
			builderElixirCapacity: 900000,
			buildCost: 400000,
			buildCostResource: Constants.builderGold,
			buildTimeSec: 0,
			buildTimeMin: 0,
			buildTimeHour: 0,
			buildTimeDay: 2,
			exp: 415,
			maximumNumberOfBuildingsAvailable: 27,
			builderHallLevelRequired: 5,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/2/22/Builder_Hall5.png/revision/latest/scale-to-width-down/100?cb=20230516070530',
		},
		{
			level: 6,
			hitpoints: 1600,
			builderGoldCapacity: 900000,
			builderElixirCapacity: 900000,
			buildCost: 1200000,
			buildCostResource: Constants.builderGold,
			buildTimeSec: 0,
			buildTimeMin: 0,
			buildTimeHour: 0,
			buildTimeDay: 3,
			exp: 509,
			maximumNumberOfBuildingsAvailable: 39,
			builderHallLevelRequired: 6,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/2/29/Builder_Hall6.png/revision/latest/scale-to-width-down/100?cb=20230516070542',
		},
		{
			level: 7,
			hitpoints: 1850,
			builderGoldCapacity: 1100000,
			builderElixirCapacity: 1100000,
			buildCost: 1800000,
			buildCostResource: Constants.builderGold,
			buildTimeSec: 0,
			buildTimeMin: 0,
			buildTimeHour: 0,
			buildTimeDay: 4,
			exp: 587,
			maximumNumberOfBuildingsAvailable: 44,
			builderHallLevelRequired: 7,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/7/7f/Builder_Hall7.png/revision/latest/scale-to-width-down/100?cb=20230516070552',
		},
		{
			level: 8,
			hitpoints: 2150,
			builderGoldCapacity: 1300000,
			builderElixirCapacity: 1300000,
			buildCost: 2800000,
			buildCostResource: Constants.builderGold,
			buildTimeSec: 0,
			buildTimeMin: 0,
			buildTimeHour: 0,
			buildTimeDay: 5,
			exp: 657,
			maximumNumberOfBuildingsAvailable: 50,
			builderHallLevelRequired: 8,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/0/0e/Builder_Hall8.png/revision/latest/scale-to-width-down/100?cb=20230516070604',
		},
		{
			level: 9,
			hitpoints: 2450,
			builderGoldCapacity: 1500000,
			builderElixirCapacity: 1500000,
			buildCost: 3800000,
			buildCostResource: Constants.builderGold,
			buildTimeSec: 0,
			buildTimeMin: 0,
			buildTimeHour: 0,
			buildTimeDay: 6,
			exp: 720,
			maximumNumberOfBuildingsAvailable: 54,
			builderHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/4/43/Builder_Hall9.png/revision/latest/scale-to-width-down/100?cb=20230516070619',
		},
		{
			level: 10,
			hitpoints: 2750,
			builderGoldCapacity: 1500000,
			builderElixirCapacity: 1500000,
			buildCost: 4800000,
			buildCostResource: Constants.builderGold,
			buildTimeSec: 0,
			buildTimeMin: 0,
			buildTimeHour: 0,
			buildTimeDay: 7,
			exp: 777,
			maximumNumberOfBuildingsAvailable: 55,
			builderHallLevelRequired: 10,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/8/87/Builder_Hall10.png/revision/latest/scale-to-width-down/100?cb=20230516070454',
		},
	],
	getSize: () => getSize(building.width, building.height),
	getLevel: (level: number) => getLevel(building.levels, level, 'level'),
	getBuilderHallLevel: (level: number) => getHallLevel(building.builderHallDetails, level, 'builderHallLevel'),
}

export default building
