import * as Constants from '@/constants'
import DefenseBuilding from '@IBuilderBase/defenses/firecrackers/defense.interface'
import { getHallLevel, getLevel, getSize } from '@Utils/buildings.utility'

const building: DefenseBuilding = {
	name: 'Firecrackers',
	description: "Keep flying pests away with flurries of small rockets! It's like a bug zapper, but prettier.",
	maxCount: 5,
	width: 2,
	height: 2,
	maxLevel: 10,
	mode: {
		damageType: Constants.singleTarget,
		unitTypeTarget: Constants.air,
		minRange: 0,
		maxRange: 9,
		shots: 3,
		attackSpeed: 0.8,
	},
	builderHallDetails: [
		{
			builderHallLevel: 1,
			availableCount: 0,
			maxLevel: 0,
			stage1MaxCount: 0,
			stage2MaxCount: 0,
		},
		{
			builderHallLevel: 2,
			availableCount: 0,
			maxLevel: 0,
			stage1MaxCount: 0,
			stage2MaxCount: 0,
		},
		{
			builderHallLevel: 3,
			availableCount: 1,
			maxLevel: 3,
			stage1MaxCount: 0,
			stage2MaxCount: 0,
		},
		{
			builderHallLevel: 4,
			availableCount: 1,
			maxLevel: 4,
			stage1MaxCount: 0,
			stage2MaxCount: 0,
		},
		{
			builderHallLevel: 5,
			availableCount: 2,
			maxLevel: 5,
			stage1MaxCount: 0,
			stage2MaxCount: 0,
		},
		{
			builderHallLevel: 6,
			availableCount: 2,
			maxLevel: 6,
			stage1MaxCount: 5,
			stage2MaxCount: 5,
		},
		{
			builderHallLevel: 7,
			availableCount: 3,
			maxLevel: 7,
			stage1MaxCount: 5,
			stage2MaxCount: 5,
		},
		{
			builderHallLevel: 8,
			availableCount: 4,
			maxLevel: 8,
			stage1MaxCount: 5,
			stage2MaxCount: 5,
		},
		{
			builderHallLevel: 9,
			availableCount: 5,
			maxLevel: 9,
			stage1MaxCount: 5,
			stage2MaxCount: 5,
		},
		{
			builderHallLevel: 10,
			availableCount: 5,
			maxLevel: 10,
			stage1MaxCount: 5,
			stage2MaxCount: 5,
		},
	],
	levels: [
		{
			level: 1,
			damagePerSecond: 55,
			damagePerShot: 19,
			hitpoints: 400,
			buildCost: 40000,
			buildCostResource: Constants.builderGold,
			buildTimeSec: 0,
			buildTimeMin: 15,
			buildTimeHour: 0,
			buildTimeDay: 0,
			exp: 30,
			builderHallLevelRequired: 3,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/b/b7/Firecrackers1.png/revision/latest/scale-to-width-down/100?cb=20230516073633',
		},
		{
			level: 2,
			damagePerSecond: 61,
			damagePerShot: 21,
			hitpoints: 460,
			buildCost: 80000,
			buildCostResource: Constants.builderGold,
			buildTimeSec: 0,
			buildTimeMin: 0,
			buildTimeHour: 2,
			buildTimeDay: 0,
			exp: 84,
			builderHallLevelRequired: 3,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/4/40/Firecrackers2.png/revision/latest/scale-to-width-down/100?cb=20230516073642',
		},
		{
			level: 3,
			damagePerSecond: 67,
			damagePerShot: 23,
			hitpoints: 530,
			buildCost: 120000,
			buildCostResource: Constants.builderGold,
			buildTimeSec: 0,
			buildTimeMin: 0,
			buildTimeHour: 4,
			buildTimeDay: 0,
			exp: 120,
			builderHallLevelRequired: 3,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/c/c3/Firecrackers3.png/revision/latest/scale-to-width-down/100?cb=20230516073647',
		},
		{
			level: 4,
			damagePerSecond: 73,
			damagePerShot: 25,
			hitpoints: 610,
			buildCost: 300000,
			buildCostResource: Constants.builderGold,
			buildTimeSec: 0,
			buildTimeMin: 0,
			buildTimeHour: 12,
			buildTimeDay: 0,
			exp: 207,
			builderHallLevelRequired: 4,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/0/06/Firecrackers4.png/revision/latest/scale-to-width-down/100?cb=20230516073652',
		},
		{
			level: 5,
			damagePerSecond: 79,
			damagePerShot: 27,
			hitpoints: 700,
			buildCost: 800000,
			buildCostResource: Constants.builderGold,
			buildTimeSec: 0,
			buildTimeMin: 0,
			buildTimeHour: 0,
			buildTimeDay: 1,
			exp: 293,
			builderHallLevelRequired: 5,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/c/c6/Firecrackers5.png/revision/latest/scale-to-width-down/100?cb=20230516073659',
		},
		{
			level: 6,
			damagePerSecond: 87,
			damagePerShot: 30,
			hitpoints: 850,
			buildCost: 1200000,
			buildCostResource: Constants.builderGold,
			buildTimeSec: 0,
			buildTimeMin: 0,
			buildTimeHour: 0,
			buildTimeDay: 2,
			exp: 415,
			builderHallLevelRequired: 6,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/9/97/Firecrackers6.png/revision/latest/scale-to-width-down/100?cb=20230516073704',
		},
		{
			level: 7,
			damagePerSecond: 96,
			damagePerShot: 33,
			hitpoints: 1000,
			buildCost: 2000000,
			buildCostResource: Constants.builderGold,
			buildTimeSec: 0,
			buildTimeMin: 0,
			buildTimeHour: 0,
			buildTimeDay: 4,
			exp: 587,
			builderHallLevelRequired: 7,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/f/fa/Firecrackers7.png/revision/latest/scale-to-width-down/100?cb=20230516073710',
		},
		{
			level: 8,
			damagePerSecond: 105,
			damagePerShot: 36,
			hitpoints: 1150,
			buildCost: 3000000,
			buildCostResource: Constants.builderGold,
			buildTimeSec: 0,
			buildTimeMin: 0,
			buildTimeHour: 0,
			buildTimeDay: 6,
			exp: 720,
			builderHallLevelRequired: 8,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/9/94/Firecrackers8.png/revision/latest/scale-to-width-down/100?cb=20230516073718',
		},
		{
			level: 9,
			damagePerSecond: 117,
			damagePerShot: 40,
			hitpoints: 1300,
			buildCost: 4000000,
			buildCostResource: Constants.builderGold,
			buildTimeSec: 0,
			buildTimeMin: 0,
			buildTimeHour: 0,
			buildTimeDay: 8,
			exp: 831,
			builderHallLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/8/88/Firecrackers9.png/revision/latest/scale-to-width-down/100?cb=20230516073723',
		},
		{
			level: 10,
			damagePerSecond: 128,
			damagePerShot: 44,
			hitpoints: 1500,
			buildCost: 5000000,
			buildCostResource: Constants.builderGold,
			buildTimeSec: 0,
			buildTimeMin: 0,
			buildTimeHour: 0,
			buildTimeDay: 9,
			exp: 881,
			builderHallLevelRequired: 10,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/5/54/Firecrackers10.png/revision/latest/scale-to-width-down/100?cb=20230516073609',
		},
	],
	getSize: () => getSize(building.width, building.height),
	getLevel: (level: number) => getLevel(building.levels, level, 'level'),
	getBuilderHallLevel: (level: number) => getHallLevel(building.builderHallDetails, level, 'builderHallLevel'),
}

export default building
