import * as Constants from '@/constants'
import Army from '@IHomeVillage/troops/elixirTroops/golem/army.interface'
import { getLevel } from '@Utils/buildings.utility'

const troop: Army = {
	name: 'Golem',
	description:
		"The mighty Golem loves to soak up damage! When destroyed, it explodes and splits into Golemites. The resulting Golemites have one-fifth the Golem's strength and hitpoints.",
	maxLevel: 13,
	housingSpace: 30,
	barracksLevelRequired: 4,
	training: {
		barracksAvailableSec: 0,
		barracksAvailableMin: 5,
		barracksUpgradingSec: 0,
		barracksUpgradingMin: 10,
	},
	mode: {
		attackType: Constants.melee,
		unitTypeTarget: Constants.ground,
		preferredTarget: Constants.defenses,
		minRange: 0,
		maxRange: 1,
		attackSpeed: 2.4,
		movementSpeed: 12,
		damageRadius: 1.5,
	},
	levels: [
		{
			level: 1,
			damagePerSecond: 35,
			damagePerAttack: 84,
			damageUponDeath: 350,
			golemitesSpawned: 2,
			hitpoints: 5100,
			researchCost: 0,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 0,
			laboratoryLevelRequired: 0,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/5/5d/Golem1.png/revision/latest/scale-to-width-down/90?cb=20170825104614',
		},
		{
			level: 2,
			damagePerSecond: 40,
			damagePerAttack: 96,
			damageUponDeath: 400,
			golemitesSpawned: 2,
			hitpoints: 5400,
			researchCost: 8000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 6,
			researchTimeDay: 1,
			laboratoryLevelRequired: 6,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/5/5d/Golem1.png/revision/latest/scale-to-width-down/90?cb=20170825104614',
		},
		{
			level: 3,
			damagePerSecond: 45,
			damagePerAttack: 108,
			damageUponDeath: 450,
			golemitesSpawned: 2,
			hitpoints: 5700,
			researchCost: 12000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 2,
			laboratoryLevelRequired: 7,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/e/e8/Golem3.png/revision/latest/scale-to-width-down/90?cb=20170825104615',
		},
		{
			level: 4,
			damagePerSecond: 50,
			damagePerAttack: 120,
			damageUponDeath: 500,
			golemitesSpawned: 2,
			hitpoints: 6000,
			researchCost: 20000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 3,
			laboratoryLevelRequired: 7,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/e/e8/Golem3.png/revision/latest/scale-to-width-down/90?cb=20170825104615',
		},
		{
			level: 5,
			damagePerSecond: 55,
			damagePerAttack: 132,
			damageUponDeath: 550,
			golemitesSpawned: 2,
			hitpoints: 6300,
			researchCost: 37000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 18,
			researchTimeDay: 3,
			laboratoryLevelRequired: 8,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/f/ff/Golem5.png/revision/latest/scale-to-width-down/90?cb=20170825104615',
		},
		{
			level: 6,
			damagePerSecond: 60,
			damagePerAttack: 144,
			damageUponDeath: 600,
			golemitesSpawned: 2,
			hitpoints: 6600,
			researchCost: 53000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 6,
			researchTimeDay: 4,
			laboratoryLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/5/57/Golem6.png/revision/latest/scale-to-width-down/90?cb=20170825104615',
		},
		{
			level: 7,
			damagePerSecond: 65,
			damagePerAttack: 156,
			damageUponDeath: 650,
			golemitesSpawned: 2,
			hitpoints: 6900,
			researchCost: 77000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 5,
			laboratoryLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/0/03/Golem7.png/revision/latest/scale-to-width-down/90?cb=20171011091945',
		},
		{
			level: 8,
			damagePerSecond: 70,
			damagePerAttack: 168,
			damageUponDeath: 700,
			golemitesSpawned: 3,
			hitpoints: 7200,
			researchCost: 100000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 5,
			laboratoryLevelRequired: 10,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/4/4d/Golem8.png/revision/latest/scale-to-width-down/90?cb=20180607160924',
		},
		{
			level: 9,
			damagePerSecond: 75,
			damagePerAttack: 180,
			damageUponDeath: 750,
			golemitesSpawned: 3,
			hitpoints: 7500,
			researchCost: 125000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 6,
			laboratoryLevelRequired: 10,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/6/69/Golem9.png/revision/latest/scale-to-width-down/90?cb=20201211063733',
		},
		{
			level: 10,
			damagePerSecond: 80,
			damagePerAttack: 192,
			damageUponDeath: 800,
			golemitesSpawned: 3,
			hitpoints: 8000,
			researchCost: 160000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 7,
			laboratoryLevelRequired: 11,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/7/79/Golem10.png/revision/latest/scale-to-width-down/90?cb=20201211064035',
		},
		{
			level: 11,
			damagePerSecond: 85,
			damagePerAttack: 204,
			damageUponDeath: 850,
			golemitesSpawned: 3,
			hitpoints: 8400,
			researchCost: 230000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 12,
			laboratoryLevelRequired: 12,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/f/fa/Golem11.png/revision/latest/scale-to-width-down/90?cb=20211012224050',
		},
		{
			level: 12,
			damagePerSecond: 90,
			damagePerAttack: 216,
			damageUponDeath: 900,
			golemitesSpawned: 3,
			hitpoints: 8800,
			researchCost: 330000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 6,
			researchTimeDay: 13,
			laboratoryLevelRequired: 13,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/4/4b/Golem12.png/revision/latest/scale-to-width-down/90?cb=20221011044309',
		},
		{
			level: 13,
			damagePerSecond: 95,
			damagePerAttack: 228,
			damageUponDeath: 950,
			golemitesSpawned: 4,
			hitpoints: 9200,
			researchCost: 350000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 15,
			laboratoryLevelRequired: 14,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/e/ef/Golem13.png/revision/latest/scale-to-width-down/90?cb=20231211145652',
		},
	],
	getLevel: (level: number) => getLevel(troop.levels, level, 'level'),
}

export default troop
