import * as Constants from '@/constants'
import Army from '@IHomeVillage/troops/elixirTroops/iceGolem/army.interface'
import { getLevel } from '@Utils/buildings.utility'

const troop: Army = {
	name: 'Ice Golem',
	description:
		'The Ice Golem has a chilling personality and absolutely zero sense of humour. He frosts over everything he touches, freezes his surroundings when destroyed and ices up when talked to at a party. On defense his freeze effect is smaller and has a shorter duration.',
	maxLevel: 7,
	housingSpace: 15,
	barracksLevelRequired: 8,
	training: {
		barracksAvailableSec: 30,
		barracksAvailableMin: 2,
		barracksUpgradingSec: 0,
		barracksUpgradingMin: 5,
	},
	mode: {
		attackType: Constants.melee,
		unitTypeTarget: Constants.ground,
		preferredTarget: Constants.defenses,
		minRange: 0,
		maxRange: 1,
		attackSpeed: 2.4,
		movementSpeed: 12,
		freezeRadius: 7.5,
	},
	levels: [
		{
			level: 1,
			damagePerSecond: 24,
			damagePerAttack: 57.6,
			freezeTimeAfterDeathOnOffense: 4,
			freezeTimeAfterDeathOnDefense: 2,
			hitpoints: 2600,
			researchCost: 0,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 0,
			laboratoryLevelRequired: 0,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/0/0a/Ice_Golem1.png/revision/latest/scale-to-width-down/100?cb=20230613100113',
		},
		{
			level: 2,
			damagePerSecond: 28,
			damagePerAttack: 67.2,
			freezeTimeAfterDeathOnOffense: 4.75,
			freezeTimeAfterDeathOnDefense: 2.25,
			hitpoints: 2800,
			researchCost: 55000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 20,
			researchTimeDay: 2,
			laboratoryLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/0/0a/Ice_Golem1.png/revision/latest/scale-to-width-down/100?cb=20230613100113',
		},
		{
			level: 3,
			damagePerSecond: 32,
			damagePerAttack: 76.8,
			freezeTimeAfterDeathOnOffense: 5.5,
			freezeTimeAfterDeathOnDefense: 2.5,
			hitpoints: 3000,
			researchCost: 85000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 4,
			laboratoryLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/8/84/Ice_Golem3.png/revision/latest/scale-to-width-down/100?cb=20230613100128',
		},
		{
			level: 4,
			damagePerSecond: 36,
			damagePerAttack: 86.4,
			freezeTimeAfterDeathOnOffense: 6.25,
			freezeTimeAfterDeathOnDefense: 2.75,
			hitpoints: 3200,
			researchCost: 100000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 5,
			laboratoryLevelRequired: 10,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/8/84/Ice_Golem3.png/revision/latest/scale-to-width-down/100?cb=20230613100128',
		},
		{
			level: 5,
			damagePerSecond: 40,
			damagePerAttack: 96,
			freezeTimeAfterDeathOnOffense: 7,
			freezeTimeAfterDeathOnDefense: 3,
			hitpoints: 3400,
			researchCost: 125000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 6,
			laboratoryLevelRequired: 10,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/5/5e/Ice_Golem5.png/revision/latest/scale-to-width-down/100?cb=20230613100135',
		},
		{
			level: 6,
			damagePerSecond: 44,
			damagePerAttack: 105.6,
			freezeTimeAfterDeathOnOffense: 7.5,
			freezeTimeAfterDeathOnDefense: 3.25,
			hitpoints: 3600,
			researchCost: 240000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 11,
			laboratoryLevelRequired: 12,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/5/5e/Ice_Golem5.png/revision/latest/scale-to-width-down/100?cb=20230613100135',
		},
		{
			level: 7,
			damagePerSecond: 48,
			damagePerAttack: 115.2,
			freezeTimeAfterDeathOnOffense: 8,
			freezeTimeAfterDeathOnDefense: 3.5,
			hitpoints: 3900,
			researchCost: 335000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 6,
			researchTimeDay: 13,
			laboratoryLevelRequired: 13,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/9/99/Ice_Golem7.png/revision/latest/scale-to-width-down/100?cb=20230613100141',
		},
	],
	getLevel: (level: number) => getLevel(troop.levels, level, 'level'),
}

export default troop
