import * as Constants from '@/constants'
import Army from '@IHomeVillage/troops/elixirTroops/lavaHound/army.interface'
import { getLevel } from '@Utils/buildings.utility'

const troop: Army = {
	name: 'Lava Hound',
	description:
		"These fiery beasts can't resist chasing after Air Defenses, providing excellent protection for other troops. Once destroyed, they erupt into many smaller, weaker menaces.",
	maxLevel: 6,
	housingSpace: 30,
	barracksLevelRequired: 6,
	superTroopUnlocked: 'Ice Hound',
	training: {
		barracksAvailableSec: 0,
		barracksAvailableMin: 5,
		barracksUpgradingSec: 0,
		barracksUpgradingMin: 10,
	},
	mode: {
		attackType: Constants.melee,
		unitTypeTarget: Constants.ground,
		preferredTarget: Constants.airDefense,
		minRange: 0,
		maxRange: 1,
		attackSpeed: 2,
		movementSpeed: 20,
	},
	levels: [
		{
			level: 1,
			damagePerSecond: 10,
			damagePerAttack: 20,
			damageUponDeath: 100,
			lavaPupsOnOffense: 8,
			lavaPupsOnDefense: 8,
			hitpoints: 6100,
			researchCost: 0,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 0,
			laboratoryLevelRequired: 0,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/12/Lava_Hound1.png/revision/latest/scale-to-width-down/70?cb=20171007165452',
		},
		{
			level: 2,
			damagePerSecond: 12,
			damagePerAttack: 24,
			damageUponDeath: 150,
			lavaPupsOnOffense: 10,
			lavaPupsOnDefense: 9,
			hitpoints: 6500,
			researchCost: 28000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 12,
			researchTimeDay: 2,
			laboratoryLevelRequired: 7,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/1/12/Lava_Hound1.png/revision/latest/scale-to-width-down/70?cb=20171007165452',
		},
		{
			level: 3,
			damagePerSecond: 14,
			damagePerAttack: 28,
			damageUponDeath: 200,
			lavaPupsOnOffense: 12,
			lavaPupsOnDefense: 10,
			hitpoints: 6800,
			researchCost: 43000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 4,
			laboratoryLevelRequired: 8,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/b/b0/Lava_Hound3.png/revision/latest/scale-to-width-down/70?cb=20171007165512',
		},
		{
			level: 4,
			damagePerSecond: 16,
			damagePerAttack: 32,
			damageUponDeath: 250,
			lavaPupsOnOffense: 14,
			lavaPupsOnDefense: 11,
			hitpoints: 7200,
			researchCost: 85000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 6,
			researchTimeDay: 6,
			laboratoryLevelRequired: 9,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/b/b0/Lava_Hound4.png/revision/latest/scale-to-width-down/70?cb=20171007165541',
		},
		{
			level: 5,
			damagePerSecond: 18,
			damagePerAttack: 36,
			damageUponDeath: 300,
			lavaPupsOnOffense: 16,
			lavaPupsOnDefense: 12,
			hitpoints: 7600,
			researchCost: 120000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 7,
			laboratoryLevelRequired: 10,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/0/01/Lava_Hound5.png/revision/latest/scale-to-width-down/70?cb=20180607161248',
		},
		{
			level: 6,
			damagePerSecond: 20,
			damagePerAttack: 40,
			damageUponDeath: 350,
			lavaPupsOnOffense: 18,
			lavaPupsOnDefense: 13,
			hitpoints: 8000,
			researchCost: 160000,
			researchCostResource: Constants.darkElixir,
			researchTimeSec: 0,
			researchTimeMin: 0,
			researchTimeHour: 0,
			researchTimeDay: 8,
			laboratoryLevelRequired: 11,
			baseImgUrl:
				'https://static.wikia.nocookie.net/clashofclans/images/f/f7/Lava_Hound6.png/revision/latest/scale-to-width-down/70?cb=20200901090417',
		},
	],
	getLevel: (level: number) => getLevel(troop.levels, level, 'level'),
}

export default troop
